var cards=[
{c:'ai',t:'大语言模型',n:'ChatGPT',d:'OpenAI 推出的顶级对话式 AI，支持文本、图像、语音多模态交互。',u:'https://chat.openai.com',tag:'GPT·多模态',ic:'💬'},
{c:'ai',t:'大语言模型',n:'Claude',d:'Anthropic 开发的安全可靠大模型，擅长长文本分析与深度推理。',u:'https://claude.ai',tag:'长文本·安全',ic:'🧠'},
{c:'ai',t:'大语言模型',n:'Gemini',d:'Google DeepMind 打造的新一代多模态大模型，整合搜索与推理。',u:'https://gemini.google.com',tag:'Google·多模态',ic:'♊'},
{c:'ai',t:'大语言模型',n:'DeepSeek',d:'深度求索推出的高性能开源大模型，编程与推理能力突出。',u:'https://chat.deepseek.com',tag:'开源·编程',ic:'🔮'},
{c:'ai',t:'大语言模型',n:'Kimi',d:'月之暗面推出的超长上下文 AI 助手，支持 200 万字输入。',u:'https://kimi.moonshot.cn',tag:'长上下文·国产',ic:'🌙'},
{c:'ai',t:'大语言模型',n:'通义千问',d:'阿里云自研大语言模型，提供对话、编程、翻译等多场景服务。',u:'https://tongyi.aliyun.com',tag:'阿里·国产',ic:'☁️'},
{c:'ai',t:'大语言模型',n:'文心一言',d:'百度推出的知识增强大语言模型，深度整合百度搜索生态。',u:'https://yiyan.baidu.com',tag:'百度·知识增强',ic:'📘'},
{c:'ai',t:'大语言模型',n:'豆包',d:'字节跳动旗下 AI 对话助手，集成抖音生态与多模态能力。',u:'https://www.doubao.com',tag:'字节·多模态',ic:'🫘'},
{c:'ai',t:'大语言模型',n:'Grok',d:'xAI（马斯克旗下）推出的幽默风格 AI 助手，实时访问 X 平台数据。',u:'https://grok.com',tag:'xAI·实时',ic:'🚀'},
{c:'ai',t:'大语言模型',n:'Perplexity',d:'AI 驱动的智能搜索引擎，结合大模型与实时网页检索。',u:'https://www.perplexity.ai',tag:'搜索·研究',ic:'🔎'},
{c:'ai',t:'大语言模型',n:'智谱清言',d:'智谱 AI 推出的 GLM 系列大模型对话产品，支持多模态交互。',u:'https://chatglm.cn',tag:'GLM·国产',ic:'💎'},
{c:'ai',t:'大语言模型',n:'讯飞星火',d:'科大讯飞自研大模型，深耕语音交互与教育办公场景。',u:'https://xinghuo.xfyun.cn',tag:'讯飞·语音',ic:'🔥'},
{c:'ai',t:'大语言模型',n:'百川智能',d:'百川 AI 推出的 Baichuan 系列大模型平台，中文评测突出。',u:'https://www.baichuan-ai.com',tag:'百川·国产',ic:'🌊'},
{c:'ai',t:'大语言模型',n:'腾讯混元',d:'腾讯自研大模型，深度嵌入微信、腾讯会议等产品矩阵。',u:'https://hunyuan.tencent.com',tag:'腾讯·生态',ic:'🐧'},
{c:'ai',t:'大语言模型',n:'腾讯元宝',d:'腾讯 AI 助手应用，融合混元大模型与公众号内容生态。',u:'https://yuanbao.tencent.com',tag:'腾讯·助手',ic:'💰'},
{c:'ai',t:'大语言模型',n:'海螺 AI',d:'Minimax 推出的 AI 对话产品，语音合成能力业界领先。',u:'https://hailuoai.com',tag:'Minimax·语音',ic:'🐚'},
{c:'ai',t:'大语言模型',n:'阶跃星辰',d:'Step 系列大模型，数学推理与多模态能力突出。',u:'https://www.stepfun.com',tag:'Step·数学',ic:'⭐'},
{c:'ai',t:'大语言模型',n:'Cohere',d:'企业级大语言模型平台，Command R 系列专注 RAG 与多语言。',u:'https://cohere.com',tag:'企业·RAG',ic:'🏢'},
{c:'ai',t:'大语言模型',n:'Mistral Le Chat',d:'法国 Mistral AI 官方对话产品，支持多语言与联网搜索。',u:'https://chat.mistral.ai',tag:'欧洲·Mistral',ic:'🇫🇷'},
{c:'ai',t:'大语言模型',n:'Character.ai',d:'AI 角色扮演与对话平台，创建和互动各类虚拟角色。',u:'https://character.ai',tag:'角色·互动',ic:'🎭'},
{c:'ai',t:'大语言模型',n:'Poe',d:'Quora 旗下多模型聚合 AI 平台，一站体验数十种大语言模型。',u:'https://poe.com',tag:'聚合·Quora',ic:'📦'},
{c:'ai',t:'大语言模型',n:'HuggingChat',d:'Hugging Face 开源 AI 对话，可自由切换多种开源模型。',u:'https://huggingface.co/chat',tag:'开源·自由',ic:'🤗'},
{c:'ai',t:'大语言模型',n:'Anthropic Console',d:'Claude API 开发者控制台，构建和部署 AI 应用。',u:'https://console.anthropic.com',tag:'API·开发者',ic:'🏗️'},
{c:'ai',t:'大语言模型',n:'Meta AI',d:'Meta 推出的免费 AI 助手，集成 Llama 系列模型能力。',u:'https://www.meta.ai',tag:'Meta·免费',ic:'🅼'},
{c:'ai',t:'大语言模型',n:'Pi',d:'Inflection AI 打造的情感化 AI 对话助手，对话自然温暖。',u:'https://pi.ai',tag:'情感·Inflection',ic:'π'},
{c:'ai',t:'大语言模型',n:'DeepSeek 平台',d:'DeepSeek API 开发平台，提供模型推理与微调服务。',u:'https://platform.deepseek.com',tag:'API·微调',ic:'🖥️'},
{c:'ai',t:'大语言模型',n:'Google AI Studio',d:'Google 官方 AI 原型开发平台，免费使用 Gemini 系列模型。',u:'https://aistudio.google.com',tag:'Google·原型',ic:'🅶'},
{c:'ai',t:'大语言模型',n:'Reka AI',d:'前 DeepMind 团队创立的多模态大模型，视觉理解能力突出。',u:'https://www.reka.ai',tag:'多模态·DeepMind系',ic:'🌟'},
{c:'ai',t:'大语言模型',n:'AI21 Labs',d:'以色列 AI 公司推出 Jurassic 系列大模型，企业级语言理解。',u:'https://www.ai21.com',tag:'企业·以色列',ic:'🇮🇱'},
{c:'ai',t:'大语言模型',n:'Writer',d:'企业级全栈 AI 写作平台，Palmyra 模型专为商业场景打造。',u:'https://writer.com',tag:'企业·全栈',ic:'✒️'},

{c:'ai',t:'AI搜索',n:'秘塔 AI 搜索',d:'中文 AI 搜索引擎，可深入学术与专业领域检索。',u:'https://metaso.cn',tag:'搜索·学术',ic:'🔍'},
{c:'ai',t:'AI搜索',n:'天工 AI 搜索',d:'昆仑万维推出的 AI 搜索产品，支持多轮深度研究。',u:'https://www.tiangong.cn',tag:'搜索·深度',ic:'🌤️'},
{c:'ai',t:'AI搜索',n:'Devv',d:'面向开发者的 AI 搜索引擎，精准检索编程与技术文档。',u:'https://devv.ai',tag:'编程·搜索',ic:'👾'},
{c:'ai',t:'AI搜索',n:'You.com',d:'以隐私为核心的 AI 搜索引擎，支持多种 AI 模式切换。',u:'https://you.com',tag:'隐私·搜索',ic:'🔒'},
{c:'ai',t:'AI搜索',n:'Phind',d:'专为开发者打造的 AI 答案引擎，结合实时搜索与代码生成。',u:'https://www.phind.com',tag:'代码·搜索',ic:'💡'},
{c:'ai',t:'AI搜索',n:'博查 AI 搜索',d:'字节旗下 AI 搜索产品，聚合全网信息智能回答。',u:'https://www.bochaai.com',tag:'字节·搜索',ic:'🎯'},
{c:'ai',t:'AI搜索',n:'Brave Search',d:'Brave 浏览器内置 AI 搜索引擎，隐私优先无追踪。',u:'https://search.brave.com',tag:'隐私·独立',ic:'🦁'},
{c:'ai',t:'AI搜索',n:'Consensus',d:'AI 驱动的学术论文搜索引擎，用研究证据回答问题。',u:'https://consensus.app',tag:'学术·论文',ic:'🎓'},
{c:'ai',t:'AI搜索',n:'Andi Search',d:'AI 原生搜索引擎，以对话形式呈现结构化答案。',u:'https://andisearch.com',tag:'对话·结构',ic:'🧠'},

{c:'ai',t:'AI写作办公',n:'Gamma',d:'AI 驱动的演示文稿与文档生成工具，一键创建精美 PPT。',u:'https://gamma.app',tag:'PPT·AI',ic:'📊'},
{c:'ai',t:'AI写作办公',n:'Jasper',d:'老牌 AI 营销写作助手，支持品牌化内容批量生成。',u:'https://www.jasper.ai',tag:'营销·写作',ic:'✍️'},
{c:'ai',t:'AI写作办公',n:'Copy.ai',d:'AI 销售与营销写作平台，专注 GTM 工作流自动化。',u:'https://www.copy.ai',tag:'销售·自动化',ic:'📋'},
{c:'ai',t:'AI写作办公',n:'Grammarly',d:'全球领先的 AI 写作辅助工具，语法检查与风格优化。',u:'https://www.grammarly.com',tag:'语法·英文',ic:'✅'},
{c:'ai',t:'AI写作办公',n:'通义听悟',d:'阿里云 AI 音视频转写工具，支持实时翻译与摘要生成。',u:'https://tingwu.aliyun.com',tag:'转写·翻译',ic:'👂'},
{c:'ai',t:'AI写作办公',n:'讯飞听见',d:'科大讯飞语音转文字平台，会议记录与访谈利器。',u:'https://www.iflyrec.com',tag:'语音转写·会议',ic:'🎙️'},
{c:'ai',t:'AI写作办公',n:'Otter.ai',d:'AI 会议记录与转录工具，实时生成会议笔记与摘要。',u:'https://otter.ai',tag:'会议·转录',ic:'🦦'},
{c:'ai',t:'AI写作办公',n:'Notion AI',d:'Notion 内置 AI 写作助手，笔记、文档与知识库一体化。',u:'https://www.notion.so/product/ai',tag:'笔记·知识库',ic:'📝'},
{c:'ai',t:'AI写作办公',n:'WPS AI',d:'金山办公 WPS 内置 AI 助手，文档、表格、PPT 智能处理。',u:'https://ai.wps.cn',tag:'办公套件·国产',ic:'📑'},
{c:'ai',t:'AI写作办公',n:'Rytr',d:'高性价比 AI 写作助手，支持 40+ 用例与多语种内容生成。',u:'https://rytr.me',tag:'多语种·高性价比',ic:'✍️'},
{c:'ai',t:'AI写作办公',n:'Writesonic',d:'AI 内容生成与营销写作平台，企业级 SEO 优化文章创作。',u:'https://writesonic.com',tag:'SEO·营销',ic:'🚀'},
{c:'ai',t:'AI写作办公',n:'Jenni AI',d:'AI 学术写作与研究助手，论文与报告写作的最佳伴侣。',u:'https://jenni.ai',tag:'学术·论文',ic:'🎓'},

{c:'ai',t:'AI设计',n:'Canva',d:'全球最流行的在线设计平台，深度集成 AI 图像与排版功能。',u:'https://www.canva.com',tag:'设计·模板',ic:'🖌️'},
{c:'ai',t:'AI设计',n:'Microsoft Designer',d:'微软 AI 设计工具，通过自然语言生成海报、社媒图像。',u:'https://designer.microsoft.com',tag:'微软·海报',ic:'🪟'},
{c:'ai',t:'AI设计',n:'Galileo AI',d:'用自然语言描述即可生成 UI 界面设计稿的 AI 工具。',u:'https://www.usegalileo.ai',tag:'UI生成·设计稿',ic:'🎨'},
{c:'ai',t:'AI设计',n:'Uizard',d:'AI 驱动的产品原型设计工具，草图一键转交互原型。',u:'https://uizard.io',tag:'原型·草图',ic:'📱'},
{c:'ai',t:'AI设计',n:'即时 AI',d:'即时设计推出的 AI UI 生成工具，中文界面设计首选。',u:'https://js.design/ai',tag:'国产·UI',ic:'🇨🇳'},

{c:'ai',t:'AI绘画',n:'Midjourney',d:'最受欢迎的 AI 图像生成工具，以艺术风格和质量著称。',u:'https://www.midjourney.com',tag:'艺术·高质量',ic:'🎨'},
{c:'ai',t:'AI绘画',n:'Stable Diffusion',d:'Stability AI 的开源图像生成模型，可本地部署自由创作。',u:'https://stability.ai',tag:'开源·可部署',ic:'🖼️'},
{c:'ai',t:'AI绘画',n:'DALL·E',d:'OpenAI 开发的图像生成模型，与 ChatGPT 深度整合。',u:'https://openai.com/dall-e-3',tag:'OpenAI·精准',ic:'✨'},
{c:'ai',t:'AI绘画',n:'ComfyUI',d:'功能强大的 Stable Diffusion 节点式工作流界面，灵活高效。',u:'https://github.com/comfyanonymous/ComfyUI',tag:'工作流·开源',ic:'🔧'},
{c:'ai',t:'AI绘画',n:'Leonardo AI',d:'游戏资产级 AI 图像生成平台，提供模型微调与画布编辑。',u:'https://leonardo.ai',tag:'游戏·微调',ic:'🎮'},
{c:'ai',t:'AI绘画',n:'Firefly',d:'Adobe 推出的商用安全 AI 图像生成工具，深度集成 PS。',u:'https://firefly.adobe.com',tag:'Adobe·商用安全',ic:'🦋'},
{c:'ai',t:'AI绘画',n:'通义万相',d:'阿里云推出的 AI 创意绘画平台，支持文生图与风格迁移。',u:'https://tongyi.aliyun.com/wanxiang',tag:'阿里·创意',ic:'🖼️'},
{c:'ai',t:'AI绘画',n:'文心一格',d:'百度出品的 AI 艺术与创意辅助平台，中文理解优秀。',u:'https://yige.baidu.com',tag:'百度·中文',ic:'🖌️'},
{c:'ai',t:'AI绘画',n:'SeaArt',d:'专注于动漫风格的 AI 绘画平台，模型与 LoRA 资源丰富。',u:'https://www.seaart.ai',tag:'动漫·LoRA',ic:'🌸'},
{c:'ai',t:'AI绘画',n:'Krea AI',d:'AI 实时图像生成与增强工具，边画边生成创意无限。',u:'https://www.krea.ai',tag:'实时·增强',ic:'🎯'},
{c:'ai',t:'AI绘画',n:'Clipdrop',d:'Jasper 旗下 AI 图像处理工具套件，去除背景与增强画质。',u:'https://clipdrop.co',tag:'工具套件·增强',ic:'📸'},
{c:'ai',t:'AI绘画',n:'Tensor.art',d:'AI 图像分享与模型工作流社区，在线免费生成 AI 绘画。',u:'https://tensor.art',tag:'社区·免费',ic:'🎨'},

{c:'ai',t:'AI视频',n:'Runway',d:'专业级 AI 视频生成与编辑平台，支持 Gen-3 等前沿模型。',u:'https://runwayml.com',tag:'视频生成·编辑',ic:'🎬'},
{c:'ai',t:'AI视频',n:'Pika',d:'简单易用的 AI 视频生成工具，支持文本转视频及视频编辑。',u:'https://pika.art',tag:'文生视频·易用',ic:'🎥'},
{c:'ai',t:'AI视频',n:'可灵 Kling',d:'快手推出的 AI 视频生成大模型，支持文生视频和图生视频。',u:'https://kling.kuaishou.com',tag:'快手·国产',ic:'🎞️'},
{c:'ai',t:'AI视频',n:'Sora',d:'OpenAI 出品的革命性文生视频模型，物理世界模拟能力极强。',u:'https://openai.com/sora',tag:'OpenAI·物理模拟',ic:'🌌'},
{c:'ai',t:'AI视频',n:'HeyGen',d:'AI 数字人视频生成平台，支持真人克隆与多语言口型同步。',u:'https://www.heygen.com',tag:'数字人·克隆',ic:'🤖'},
{c:'ai',t:'AI视频',n:'Synthesia',d:'企业级 AI 虚拟主播视频生成，无需真人出镜制作专业视频。',u:'https://www.synthesia.io',tag:'虚拟人·企业',ic:'🎭'},
{c:'ai',t:'AI视频',n:'Luma AI',d:'3D 与视频生成 AI 平台，Dream Machine 效果惊艳。',u:'https://lumalabs.ai',tag:'3D·DreamMachine',ic:'📸'},
{c:'ai',t:'AI视频',n:'即梦',d:'剪映旗下 AI 视频生成工具，文生视频与图生视频一体化。',u:'https://jimeng.jianying.com',tag:'剪映·国产',ic:'💭'},
{c:'ai',t:'AI视频',n:'Pixverse',d:'免费 AI 视频生成平台，支持文生视频与动漫风格。',u:'https://pixverse.ai',tag:'免费·动漫',ic:'✨'},
{c:'ai',t:'AI视频',n:'Vidu',d:'生数科技推出的长时长 AI 视频生成模型，一致性表现优异。',u:'https://www.vidu.studio',tag:'长视频·U-Net',ic:'🎯'},
{c:'ai',t:'AI视频',n:'剪映',d:'抖音官方视频剪辑工具，AI 字幕、调色与模板一键生成。',u:'https://www.capcut.cn',tag:'剪辑·AI',ic:'✂️'},
{c:'ai',t:'AI视频',n:'Haiper AI',d:'前 DeepMind 团队创立的 AI 视频生成平台，生成质量优秀。',u:'https://haiper.ai',tag:'DeepMind系·生成',ic:'🎬'},
{c:'ai',t:'AI视频',n:'Genmo',d:'AI 创意视频与动画生成工具，支持交互式视频创作。',u:'https://www.genmo.ai',tag:'创意·动画',ic:'✨'},
{c:'ai',t:'AI视频',n:'invideo AI',d:'AI 一键生成专业营销视频，输入话题自动产出成片。',u:'https://invideo.io',tag:'营销·自动',ic:'🎥'},
{c:'ai',t:'AI视频',n:'Fliki',d:'AI 文本转视频配音工具，博客转视频与社交媒体创作利器。',u:'https://fliki.ai',tag:'配音·文本转视频',ic:'🎙️'},
{c:'ai',t:'AI视频',n:'Descript',d:'下一代 AI 视频与播客编辑器，脚本编辑即可改变视频内容。',u:'https://www.descript.com',tag:'编辑·播客',ic:'🎧'},

{c:'ai',t:'AI音频',n:'Suno',d:'AI 音乐生成平台，输入歌词或描述即可创作完整歌曲。',u:'https://suno.ai',tag:'音乐创作·歌词',ic:'🎵'},
{c:'ai',t:'AI音频',n:'Udio',d:'高质量 AI 音乐生成工具，由前 Google DeepMind 研究员打造。',u:'https://www.udio.com',tag:'音乐·高保真',ic:'🎹'},
{c:'ai',t:'AI音频',n:'ElevenLabs',d:'目前最逼真的 AI 语音合成与克隆平台，支持多语言。',u:'https://elevenlabs.io',tag:'语音克隆·TTS',ic:'🗣️'},
{c:'ai',t:'AI音频',n:'魔音工坊',d:'出门问问旗下的 AI 配音工具，提供数百种拟人化音色。',u:'https://www.moyin.com',tag:'配音·中文',ic:'🎤'},
{c:'ai',t:'AI音频',n:'Murf AI',d:'专业 AI 配音平台，适用于播客、有声书与视频配音。',u:'https://murf.ai',tag:'配音·专业',ic:'🎧'},
{c:'ai',t:'AI音频',n:'Play.ht',d:'超现实 AI 语音生成器，支持语音克隆与多语种 TTS。',u:'https://play.ht',tag:'TTS·多语种',ic:'🔊'},
{c:'ai',t:'AI音频',n:'Speak',d:'AI 语言学习 App，通过语音交互练习英语与韩语口语。',u:'https://www.speak.com',tag:'语言学习·口语',ic:'🗣️'},
{c:'ai',t:'AI音频',n:'AIVA',d:'古典与影视配乐 AI 作曲家，全球首个注册 AI 音乐协会成员。',u:'https://www.aiva.ai',tag:'古典·配乐',ic:'🎻'},
{c:'ai',t:'AI音频',n:'Soundraw',d:'AI 自动生成免版税音乐，按情绪与风格定制个性化配乐。',u:'https://soundraw.io',tag:'免版税·定制',ic:'🎶'},
{c:'ai',t:'AI音频',n:'Boomy',d:'AI 音乐创作与流媒体发行一体化，生成音乐直接上传平台。',u:'https://boomy.com',tag:'创作·发行',ic:'🎸'},

{c:'ai',t:'AI编程',n:'GitHub Copilot',d:'GitHub 与 OpenAI 联合推出的 AI 编程助手，深度集成 IDE。',u:'https://github.com/features/copilot',tag:'代码补全·IDE',ic:'👨‍💻'},
{c:'ai',t:'AI编程',n:'Cursor',d:'基于 VS Code 的 AI 原生代码编辑器，编程体验极致智能。',u:'https://cursor.sh',tag:'编辑器·智能',ic:'🖱️'},
{c:'ai',t:'AI编程',n:'Windsurf',d:'Codeium 推出的 AI 原生 IDE，支持多文件智能编辑与重构。',u:'https://codeium.com/windsurf',tag:'IDE·多文件',ic:'🌊'},
{c:'ai',t:'AI编程',n:'v0.dev',d:'Vercel 推出的 AI 前端界面生成工具，通过自然语言生成 UI。',u:'https://v0.dev',tag:'UI生成·Vercel',ic:'🖌️'},
{c:'ai',t:'AI编程',n:'Bolt.new',d:'StackBlitz 推出的 AI 全栈应用生成器，直接在浏览器构建应用。',u:'https://bolt.new',tag:'全栈·浏览器',ic:'⚡'},
{c:'ai',t:'AI编程',n:'通义灵码',d:'阿里云推出的免费 AI 编程助手，兼容主流 IDE。',u:'https://tongyi.aliyun.com/lingma',tag:'阿里·免费',ic:'🐴'},
{c:'ai',t:'AI编程',n:'Replit',d:'在线代码编辑与托管平台，AI 加持的一键应用部署。',u:'https://replit.com',tag:'在线IDE·部署',ic:'🔄'},
{c:'ai',t:'AI编程',n:'Sourcegraph Cody',d:'基于代码图的 AI 编程助手，理解全仓库上下文。',u:'https://sourcegraph.com',tag:'代码图·上下文',ic:'📐'},
{c:'ai',t:'AI编程',n:'CodeRabbit',d:'AI 代码审查助手，自动审查 PR 提供改进建议。',u:'https://www.coderabbit.ai',tag:'代码审查·PR',ic:'🐰'},
{c:'ai',t:'AI编程',n:'Tabnine',d:'老牌 AI 代码补全引擎，支持本地模型保障代码隐私。',u:'https://www.tabnine.com',tag:'本地·隐私',ic:'🔐'},
{c:'ai',t:'AI编程',n:'Zed',d:'Rust 编写的高性能代码编辑器，深度集成 AI 协作编程。',u:'https://zed.dev',tag:'Rust·高性能',ic:'⚡'},
{c:'ai',t:'AI编程',n:'Tabby',d:'开源自托管的 AI 代码助手，数据完全可控可私有化部署。',u:'https://tabbyml.com',tag:'自托管·开源',ic:'🐈'},
{c:'ai',t:'AI编程',n:'Cline',d:'VS Code 开源 AI 编程代理，用自然语言指挥 AI 写代码。',u:'https://cline.bot',tag:'代理·开源',ic:'🤖'},
{c:'ai',t:'AI编程',n:'Lovable',d:'AI 全栈应用生成器，用自然语言描述即可构建完整 Web 应用。',u:'https://lovable.dev',tag:'全栈·自然语言',ic:'❤️'},
{c:'ai',t:'AI编程',n:'Tempo',d:'AI React 组件生成工具，用自然语言设计前端界面。',u:'https://tempo.new',tag:'React·UI',ic:'⏱️'},
{c:'ai',t:'AI编程',n:'Anima',d:'设计稿转代码 AI 工具，Figma 一键导出 React 组件。',u:'https://www.animaapp.com',tag:'设计转代码·Figma',ic:'🖌️'},
{c:'ai',t:'AI编程',n:'Locofy',d:'设计稿转前端代码平台，加速从设计到生产的转换流程。',u:'https://www.locofy.ai',tag:'设计转代码·生产',ic:'🚀'},
{c:'ai',t:'AI编程',n:'Builder.io',d:'AI 可视化 CMS 页面构建器，用自然语言生成高性能页面。',u:'https://www.builder.io',tag:'可视化·CMS',ic:'🏗️'},

{c:'ai',t:'AI Agent',n:'AutoGPT',d:'开源自主 AI Agent 框架，让 AI 自动分解和执行复杂任务。',u:'https://github.com/Significant-Gravitas/AutoGPT',tag:'自主·开源',ic:'🤖'},
{c:'ai',t:'AI Agent',n:'Dify',d:'开源的 LLM 应用开发平台，可视化编排 AI 工作流与 Agent。',u:'https://dify.ai',tag:'工作流·可视化',ic:'🧩'},
{c:'ai',t:'AI Agent',n:'扣子 Coze',d:'字节跳动推出的 AI Bot 开发平台，零代码搭建智能助手。',u:'https://www.coze.cn',tag:'字节·零代码',ic:'🤖'},
{c:'ai',t:'AI Agent',n:'Coze',d:'字节跳动国际版 AI Bot 平台，集成 Discord 和 Telegram。',u:'https://www.coze.com',tag:'国际版·Bot',ic:'🌐'},
{c:'ai',t:'AI Agent',n:'Manus',d:'通用型 AI Agent，能独立完成复杂任务的自主智能体。',u:'https://manus.im',tag:'通用Agent·自主',ic:'✋'},
{c:'ai',t:'AI Agent',n:'百宝箱',d:'百度智能云的 AI Agent 平台，快速构建智能体应用。',u:'https://agents.baidu.com',tag:'百度·Agent',ic:'🎁'},
{c:'ai',t:'AI Agent',n:'LangGraph',d:'LangChain 出品的 Agent 编排框架，构建状态化多智能体。',u:'https://langchain.com/langgraph',tag:'编排·状态化',ic:'🕸️'},
{c:'ai',t:'AI Agent',n:'CrewAI',d:'多 Agent 协作框架，定义角色让多个 AI 智能体协同工作。',u:'https://www.crewai.com',tag:'多Agent·协作',ic:'👥'},
{c:'ai',t:'AI Agent',n:'Relevance AI',d:'无代码 AI 团队构建平台，用 Agent 自动化业务流程。',u:'https://relevanceai.com',tag:'无代码·自动化',ic:'🤖'},
{c:'ai',t:'AI Agent',n:'Superagent',d:'开源的 AI 代理框架，快速构建自定义 AI 助理。',u:'https://superagent.sh',tag:'开源·可定制',ic:'🦸'},
{c:'ai',t:'AI Agent',n:'Botpress',d:'开源对话 AI 平台，可视化搭建企业级 AI 聊天机器人。',u:'https://botpress.com',tag:'开源·对话',ic:'💬'},
{c:'ai',t:'AI Agent',n:'SmythOS',d:'AI 智能体操作系统，拖拽式构建与部署多 Agent 工作流。',u:'https://smythos.com',tag:'可视化·部署',ic:'🔄'},

{c:'ai',t:'3D生成',n:'Meshy',d:'AI 3D 模型生成器，文字和图片一键转为高质量 3D 模型。',u:'https://www.meshy.ai',tag:'文生3D·PBR',ic:'🧊'},
{c:'ai',t:'3D生成',n:'Tripo AI',d:'快速 3D AI 模型生成平台，文生 3D 和图生 3D 一体化。',u:'https://www.tripo3d.ai',tag:'文生3D·材质',ic:'🔺'},
{c:'ai',t:'3D生成',n:'CSM AI',d:'Common Sense Machines，图片与视频转 3D 世界模型。',u:'https://csm.ai',tag:'图生3D·世界模型',ic:'🌍'},
{c:'ai',t:'3D生成',n:'Rodin',d:'文本和图片生成高质量 3D 头像与数字资产的 AI 平台。',u:'https://hyper3d.ai',tag:'头像·资产',ic:'🗿'},
{c:'ai',t:'3D生成',n:'Spline AI',d:'AI 辅助实时 3D 设计与协作平台，浏览器端零门槛创作。',u:'https://spline.design',tag:'实时·浏览器',ic:'🎮'},
{c:'ai',t:'3D生成',n:'DeepMotion',d:'AI 动作捕捉与 3D 动画生成，视频一键转骨骼动画。',u:'https://www.deepmotion.com',tag:'动捕·动画',ic:'🏃'},
{c:'ai',t:'3D生成',n:'Kaedim',d:'AI 图片转 3D 模型，为游戏开发者快速生成游戏资产。',u:'https://www.kaedim3d.com',tag:'游戏·资产',ic:'🎮'},
{c:'ai',t:'3D生成',n:'Ready Player Me',d:'跨游戏跨平台 3D 虚拟化身平台，一张自拍即可生成。',u:'https://readyplayer.me',tag:'化身·跨平台',ic:'🧑'},

{c:'ai',t:'数字人',n:'小冰',d:'微软小冰独立后的 AI Being 平台，覆盖虚拟人与数字人技术。',u:'https://www.xiaoice.com',tag:'AI Being·微软系',ic:'❄️'},
{c:'ai',t:'数字人',n:'D-ID',d:'AI 生成式数字人视频，让照片开口说话技术开创者。',u:'https://www.d-id.com',tag:'照片说话·AI视频',ic:'🖼️'},
{c:'ai',t:'数字人',n:'Hour One',d:'企业级 AI 虚拟主播视频生成，专业数字人制作平台。',u:'https://hourone.ai',tag:'企业·主播',ic:'🎬'},
{c:'ai',t:'数字人',n:'DeepBrain AI',d:'AI Studios 虚拟人视频制作平台，支持多语种数字人。',u:'https://www.deepbrain.io',tag:'多语种·AI Studio',ic:'🧠'},
{c:'ai',t:'数字人',n:'腾讯智影',d:'腾讯 AI 数字人视频创作平台，在线生成虚拟主播视频。',u:'https://zenvideo.qq.com',tag:'腾讯·创作',ic:'🎥'},

{c:'ai',t:'AI for Science',n:'AlphaFold DB',d:'DeepMind 蛋白质结构预测数据库，加速生命科学研究。',u:'https://alphafold.ebi.ac.uk',tag:'蛋白质·DeepMind',ic:'🧬'},
{c:'ai',t:'AI for Science',n:'RoseTTAFold',d:'华盛顿大学蛋白质结构预测工具，AI 驱动计算生物学。',u:'https://rosettafold.bakerlab.org',tag:'蛋白质·学术',ic:'🔬'},
{c:'ai',t:'AI for Science',n:'NVIDIA BioNeMo',d:'NVIDIA AI 药物研发平台，加速分子模拟与新药发现。',u:'https://www.nvidia.com/en-us/clara/bionemo',tag:'药物·NVIDIA',ic:'💊'},
{c:'ai',t:'AI for Science',n:'Isomorphic Labs',d:'DeepMind 分拆的 AI 药物发现公司，诺奖级团队创业。',u:'https://www.isomorphiclabs.com',tag:'药物发现·DeepMind系',ic:'🧪'},
{c:'ai',t:'AI for Science',n:'Recursion',d:'AI 驱动的药物发现与研发平台，已上市临床阶段公司。',u:'https://www.recursion.com',tag:'药物·临床',ic:'🏥'},

{c:'ai',t:'AI 医疗',n:'Viz.ai',d:'AI 中风检测与急救协调平台，FDA 获批，显著缩短救治时间。',u:'https://www.viz.ai',tag:'急救·中风',ic:'🏥'},
{c:'ai',t:'AI 医疗',n:'PathAI',d:'AI 病理诊断平台，辅助医生提高癌症诊断准确率。',u:'https://www.pathai.com',tag:'病理·癌症',ic:'🔬'},
{c:'ai',t:'AI 医疗',n:'Aidoc',d:'AI 放射科辅助诊断，实时分析 CT 与 MRI 影像标记异常。',u:'https://www.aidoc.com',tag:'放射·影像',ic:'🩻'},
{c:'ai',t:'AI 医疗',n:'Butterfly Network',d:'AI 驱动的手持式超声设备，让超声诊断更加可及。',u:'https://www.butterflynetwork.com',tag:'超声·手持',ic:'🦋'},
{c:'ai',t:'AI 医疗',n:'Tempus',d:'AI 驱动的个性化癌症诊疗平台，基因组与临床数据融合。',u:'https://www.tempus.com',tag:'癌症·基因组',ic:'🧬'},
{c:'ai',t:'AI 医疗',n:'推想科技',d:'中国 AI 医疗影像龙头，胸肺与脑部疾病智能筛查领先。',u:'https://www.infervision.com',tag:'影像·肺结节',ic:'🫁'},

{c:'ai',t:'AI 法律',n:'Harvey AI',d:'OpenAI 投资的 AI 法律助手，律所级法律研究与文档生成。',u:'https://www.harvey.ai',tag:'法律研究·文档',ic:'⚖️'},
{c:'ai',t:'AI 法律',n:'Lawgeex',d:'AI 合同审查与合规平台，自动比对合同条款与法律标准。',u:'https://www.lawgeex.com',tag:'合同审查·合规',ic:'📋'},
{c:'ai',t:'AI 法律',n:'Ironclad',d:'企业级合同生命周期管理，AI 驱动的合同创建与分析。',u:'https://ironcladapp.com',tag:'合同管理·企业',ic:'🛡️'},
{c:'ai',t:'AI 法律',n:'Everlaw',d:'AI 电子证据开示与诉讼支持平台，法律科技独角兽。',u:'https://www.everlaw.com',tag:'证据·诉讼',ic:'🔍'},
{c:'ai',t:'AI 法律',n:'幂律智能',d:'中国 AI 法律服务先锋，智能合同审查与知识管理平台。',u:'https://www.powerlaw.ai',tag:'国产·合同',ic:'🇨🇳'},

{c:'ai',t:'AI 金融',n:'Kensho',d:'S&P Global 旗下 AI 金融分析平台，自然语言查询市场数据。',u:'https://www.kensho.com',tag:'金融分析·S&P',ic:'📊'},
{c:'ai',t:'AI 金融',n:'Alpaca',d:'AI 驱动的量化交易 API 平台，用代码实现自动化交易策略。',u:'https://alpaca.markets',tag:'量化·API',ic:'🦙'},
{c:'ai',t:'AI 金融',n:'QuantConnect',d:'开源量化交易研究平台，支持多语言算法回测与实盘交易。',u:'https://www.quantconnect.com',tag:'量化·回测',ic:'📈'},
{c:'ai',t:'AI 金融',n:'AlphaSense',d:'AI 市场情报平台，搜索海量研报与会议记录发现投资信号。',u:'https://www.alpha-sense.com',tag:'市场情报·投研',ic:'💡'},
{c:'ai',t:'AI 金融',n:'Numerai',d:'AI 驱动的去中心化对冲基金，数据科学家竞赛预测股市。',u:'https://numer.ai',tag:'对冲基金·竞赛',ic:'🧪'},
{c:'ai',t:'AI 金融',n:'Kavout',d:'AI 量化选股平台，Kai 评分系统结合多因子智能筛选。',u:'https://www.kavout.com',tag:'选股·多因子',ic:'🔮'},

{c:'ai',t:'AI 教育',n:'Khanmigo',d:'可汗学院推出的 AI 导师，苏格拉底式引导激发主动思考。',u:'https://www.khanmigo.ai',tag:'导师·引导',ic:'🧑‍🏫'},
{c:'ai',t:'AI 教育',n:'Duolingo Max',d:'多邻国 AI 强化版，对话式角色扮演练习真实语言场景。',u:'https://www.duolingo.com/max',tag:'语言·角色扮演',ic:'🦉'},
{c:'ai',t:'AI 教育',n:'Quizlet',d:'AI 驱动的学习记忆平台，自动生成闪卡与测验题目。',u:'https://quizlet.com',tag:'记忆·闪卡',ic:'📝'},
{c:'ai',t:'AI 教育',n:'Century Tech',d:'AI 自适应学习平台，根据学生能力动态调整学习路径。',u:'https://www.century.tech',tag:'自适应·个性化',ic:'🎓'},
{c:'ai',t:'AI 教育',n:'Carnegie Learning',d:'卡内基梅隆大学衍生的 AI 数学教育公司，认知科学研究驱动。',u:'https://www.carnegielearning.com',tag:'数学·认知',ic:'🔢'},
{c:'ai',t:'AI 教育',n:'Squirrel AI',d:'松鼠 AI，中国自适应教育领军者，AI 精准诊断知识薄弱点。',u:'https://www.squirrelai.com',tag:'自适应·国产',ic:'🐿️'},

{c:'ai',t:'AI 营销',n:'Persado',d:'AI 营销语言生成平台，NLP 优化广告文案与邮件营销效果。',u:'https://www.persado.com',tag:'文案·优化',ic:'📧'},
{c:'ai',t:'AI 营销',n:'Phrasee',d:'AI 品牌语言优化工具，确保营销内容符合品牌调性。',u:'https://phrasee.co',tag:'品牌·调性',ic:'🎯'},
{c:'ai',t:'AI 营销',n:'Albert AI',d:'自主 AI 数字营销平台，自动优化跨渠道广告投放策略。',u:'https://albert.ai',tag:'广告·投放',ic:'📊'},
{c:'ai',t:'AI 营销',n:'Anyword',d:'AI 营销文案生成与效果预测，数据驱动内容优化。',u:'https://anyword.com',tag:'文案·预测',ic:'📈'},
{c:'ai',t:'AI 营销',n:'Optimove',d:'AI 客户关系营销平台，预测客户行为驱动精准个性化营销。',u:'https://www.optimove.com',tag:'CRM·个性化',ic:'🎯'},
{c:'ai',t:'AI 营销',n:'Pencil',d:'AI 广告创意生成与 A/B 测试平台，数据驱动创意迭代。',u:'https://www.pencil.com',tag:'创意·A/B测试',ic:'✏️'},

{c:'robot',t:'人形机器人',n:'Tesla Optimus',d:'特斯拉推出的通用人形机器人，旨在替代人类执行重复性劳动。',u:'https://www.tesla.com/optimus',tag:'特斯拉·通用',ic:'🤖'},
{c:'robot',t:'人形机器人',n:'Figure AI',d:'OpenAI 投资的通用人形机器人公司，目标是商业化量产。',u:'https://www.figure.ai',tag:'OpenAI·商业化',ic:'🦿'},
{c:'robot',t:'人形机器人',n:'Boston Dynamics',d:'全球最知名的高动态机器人公司，以 Atlas 和 Spot 著称。',u:'https://bostondynamics.com',tag:'动态·四足',ic:'🐕'},
{c:'robot',t:'人形机器人',n:'Unitree 宇树',d:'中国领先的四足与人形机器人公司，产品覆盖消费到工业。',u:'https://www.unitree.com',tag:'四足·国产',ic:'🐾'},
{c:'robot',t:'人形机器人',n:'1X Technologies',d:'OpenAI 投资的挪威人形机器人公司，专注于家庭服务场景。',u:'https://www.1x.tech',tag:'家庭·轻量',ic:'🏠'},
{c:'robot',t:'人形机器人',n:'Agility Robotics',d:'Digit 人形机器人制造商，专注物流仓储场景的商业化应用。',u:'https://agilityrobotics.com',tag:'物流·仓储',ic:'📦'},
{c:'robot',t:'人形机器人',n:'傅利叶智能',d:'中国通用人形机器人 GR-1 开发商，布局康复与通用场景。',u:'https://www.fftai.com',tag:'康复·国产',ic:'🏥'},
{c:'robot',t:'人形机器人',n:'智元机器人',d:'华为前高管创办的具身智能公司，推动人形机器人产业化。',u:'https://www.agibot.com',tag:'具身智能·华为系',ic:'🧬'},
{c:'robot',t:'人形机器人',n:'Apptronik',d:'NASA 合作的通用人形机器人 Apollo，聚焦物流与制造。',u:'https://apptronik.com',tag:'NASA·物流',ic:'🚀'},
{c:'robot',t:'人形机器人',n:'优必选科技',d:'中国人形机器人第一股，Walker 系列人形机器人行业领先。',u:'https://www.ubtrobot.com',tag:'Walker·国产',ic:'🤖'},
{c:'robot',t:'人形机器人',n:'达闼机器人',d:'云端智能机器人公司，Cloud Ginger 主打服务场景。',u:'https://www.cloudminds.com',tag:'云端智能·服务',ic:'☁️'},
{c:'robot',t:'人形机器人',n:'逐际动力',d:'EngineAI，专注于通用人形机器人运动智能与控制。',u:'https://www.engineai.com.cn',tag:'运动智能·国产',ic:'🏃'},
{c:'robot',t:'人形机器人',n:'Clone Robotics',d:'人工肌肉驱动的人形机器人，仿生肌腱技术模拟人类运动。',u:'https://www.clonerobotics.com',tag:'仿生·人工肌肉',ic:'🦾'},
{c:'robot',t:'人形机器人',n:'PAL Robotics',d:'西班牙人形与服务机器人公司，REEM 系列享誉欧洲。',u:'https://pal-robotics.com',tag:'欧洲·服务',ic:'🇪🇸'},
{c:'robot',t:'人形机器人',n:'Beyond Imagination',d:'BEOMNI 人形远程操作机器人，用 VR 遥控实现远程作业。',u:'https://beyondimagination.co',tag:'远程·VR',ic:'🕶️'},

{c:'robot',t:'工业机器人',n:'ABB Robotics',d:'全球工业机器人巨头，提供全系列协作与工业机器人。',u:'https://new.abb.com/products/robotics',tag:'工业·协作',ic:'⚙️'},
{c:'robot',t:'工业机器人',n:'FANUC',d:'日本发那科，全球装机量最大的工业机器人制造商。',u:'https://www.fanuc.com',tag:'日本·CNC',ic:'🏭'},
{c:'robot',t:'工业机器人',n:'KUKA',d:'德国库卡机器人，汽车制造与工业自动化领域的标杆。',u:'https://www.kuka.com',tag:'德国·汽车',ic:'🚗'},
{c:'robot',t:'工业机器人',n:'Yaskawa 安川',d:'日本安川电机，伺服电机与工业机器人全球领先。',u:'https://www.yaskawa.com',tag:'日本·伺服',ic:'🔌'},
{c:'robot',t:'工业机器人',n:'埃斯顿自动化',d:'国产工业机器人龙头，覆盖焊接、搬运、喷涂全场景。',u:'https://www.estun.com',tag:'国产·全场景',ic:'🇨🇳'},
{c:'robot',t:'工业机器人',n:'新松机器人',d:'中国机器人产业国家队，工业与服务机器人全覆盖。',u:'https://www.siasun.com',tag:'国家队·全面',ic:'🤖'},

{c:'robot',t:'服务机器人',n:'普渡机器人',d:'全球餐饮配送机器人领导者，覆盖送餐、回盘、消毒。',u:'https://www.pudutech.com',tag:'餐饮·配送',ic:'🍽️'},
{c:'robot',t:'服务机器人',n:'擎朗智能',d:'商用服务机器人公司，餐饮酒店配送机器人畅销海外。',u:'https://www.keenon.com',tag:'商用·配送',ic:'🤖'},
{c:'robot',t:'服务机器人',n:'高仙机器人',d:'清洁机器人行业龙头，商用清洁与无人环卫全覆盖。',u:'https://www.gs-robot.com',tag:'清洁·环卫',ic:'🧹'},
{c:'robot',t:'服务机器人',n:'追觅科技',d:'从扫地机器人到仿生四足机器人，消费机器人创新者。',u:'https://www.dreame.com',tag:'消费级·扫地',ic:'🏡'},
{c:'robot',t:'服务机器人',n:'科沃斯',d:'中国扫地机器人领军品牌，家庭服务机器人生态完善。',u:'https://www.ecovacs.com',tag:'扫地·家庭',ic:'🧽'},
{c:'robot',t:'服务机器人',n:'石头科技',d:'高端扫地机器人品牌，清洁算法与导航技术领先。',u:'https://www.roborock.com',tag:'高端·导航',ic:'🪨'},
{c:'robot',t:'服务机器人',n:'大疆 RoboMaster',d:'DJI 教育机器人系列，编程与竞技一体的人工智能学习平台。',u:'https://www.dji.com/robomaster-s1',tag:'教育·竞技',ic:'🏆'},

{c:'robot',t:'机器人平台',n:'ROS.org',d:'机器人操作系统（Robot Operating System）官方网站与社区。',u:'https://www.ros.org',tag:'开源·框架',ic:'⚙️'},
{c:'robot',t:'机器人平台',n:'NVIDIA Isaac',d:'NVIDIA 机器人开发平台，提供仿真、训练与部署全套方案。',u:'https://developer.nvidia.com/isaac',tag:'NVIDIA·仿真',ic:'🟢'},
{c:'robot',t:'机器人平台',n:'ROS 2',d:'下一代机器人操作系统，为工业级应用提供更强实时性。',u:'https://docs.ros.org/en/rolling',tag:'实时·工业',ic:'📡'},
{c:'robot',t:'机器人平台',n:'Universal Robots',d:'协作机器人鼻祖，UR 系列全球装机量遥遥领先。',u:'https://www.universal-robots.com',tag:'协作·易部署',ic:'🤝'},
{c:'robot',t:'机器人平台',n:'MuJoCo',d:'Google DeepMind 开源物理引擎，机器人仿真研究首选。',u:'https://mujoco.org',tag:'物理引擎·开源',ic:'🔬'},
{c:'robot',t:'机器人平台',n:'NVIDIA Omniverse',d:'NVIDIA 3D 协作与仿真平台，驱动机器人数字孪生开发。',u:'https://www.nvidia.com/en-us/omniverse',tag:'数字孪生·NVIDIA',ic:'🌐'},
{c:'robot',t:'机器人平台',n:'CoppeliaSim',d:'专业机器人仿真软件，支持多种物理引擎与编程语言。',u:'https://www.coppeliarobotics.com',tag:'仿真·多语言',ic:'🔧'},
{c:'robot',t:'机器人平台',n:'Webots',d:'开源跨平台机器人仿真软件，Cyberbotics 出品学术首选。',u:'https://cyberbotics.com',tag:'开源·跨平台',ic:'🤖'},
{c:'robot',t:'机器人平台',n:'Gazebo',d:'OSRF 维护的开源 3D 机器人仿真器，ROS 生态核心组件。',u:'https://gazebosim.org',tag:'开源·3D仿真',ic:'🏗️'},

{c:'robot',t:'自动驾驶',n:'Waymo',d:'Alphabet 旗下自动驾驶公司，全球 L4 自动驾驶技术标杆。',u:'https://waymo.com',tag:'L4·Alphabet',ic:'🚗'},
{c:'robot',t:'自动驾驶',n:'Cruise',d:'通用汽车旗下自动驾驶子公司，深耕城市 Robotaxi 运营。',u:'https://www.getcruise.com',tag:'GM·Robotaxi',ic:'🚕'},
{c:'robot',t:'自动驾驶',n:'百度 Apollo',d:'百度自动驾驶开放平台，提供车路行云一体化方案。',u:'https://www.apollo.auto',tag:'百度·开放平台',ic:'🇨🇳'},
{c:'robot',t:'自动驾驶',n:'文远知行 WeRide',d:'全球领先的 L4 级自动驾驶公司，覆盖出行与货运。',u:'https://www.weride.ai',tag:'L4·出行货运',ic:'🚌'},
{c:'robot',t:'自动驾驶',n:'小马智行 Pony.ai',d:'中美两地同步运营的自动驾驶公司，技术实力强劲。',u:'https://www.pony.ai',tag:'中美·L4',ic:'🐴'},
{c:'robot',t:'自动驾驶',n:'Mobileye',d:'英特尔旗下自动驾驶视觉芯片公司，ADAS 市场领导者。',u:'https://www.mobileye.com',tag:'视觉·ADAS',ic:'👁️'},
{c:'robot',t:'自动驾驶',n:'Nuro',d:'专注最后一公里自动驾驶配送的公司，无人配送车已商用。',u:'https://www.nuro.ai',tag:'配送·商用',ic:'📦'},
{c:'robot',t:'自动驾驶',n:'Aurora',d:'自动驾驶技术研发平台，聚焦货运卡车与乘用车自动驾驶。',u:'https://aurora.tech',tag:'货运·乘用',ic:'🚛'},
{c:'robot',t:'自动驾驶',n:'Zoox',d:'亚马逊旗下全自动驾驶公司，打造无方向盘的 Robotaxi。',u:'https://zoox.com',tag:'亚马逊·Robotaxi',ic:'🚗'},
{c:'robot',t:'自动驾驶',n:'TuSimple',d:'自动驾驶卡车技术公司，专注长途干线物流自动驾驶。',u:'https://www.tusimple.com',tag:'卡车·物流',ic:'🚚'},
{c:'robot',t:'自动驾驶',n:'Embark Trucks',d:'自动驾驶卡车软件公司，为物流车队提供高速自动驾驶方案。',u:'https://embarktrucks.com',tag:'卡车·高速',ic:'🛣️'},

{c:'robot',t:'无人机',n:'Skydio',d:'美国 AI 自主无人机领导者，全自主避障飞行无出其右。',u:'https://www.skydio.com',tag:'自主·AI避障',ic:'🛸'},
{c:'robot',t:'无人机',n:'亿航智能 EHang',d:'全球首家上市的载人级自动驾驶飞行器公司。',u:'https://www.ehang.com',tag:'载人·eVTOL',ic:'🚁'},
{c:'robot',t:'无人机',n:'Zipline',d:'医疗物资无人机配送全球领导者，服务非洲与美国。',u:'https://www.flyzipline.com',tag:'医疗·配送',ic:'💉'},
{c:'robot',t:'无人机',n:'Wing',d:'Google 母公司 Alphabet 旗下无人机配送服务。',u:'https://wing.com',tag:'Alphabet·配送',ic:'📦'},
{c:'robot',t:'无人机',n:'极飞科技 XAG',d:'中国智慧农业无人化技术领导者，农业无人机全球领先。',u:'https://www.xag.cn',tag:'农业·国产',ic:'🌾'},

{c:'robot',t:'手术机器人',n:'Intuitive Surgical',d:'达芬奇手术机器人制造商，微创外科手术机器人的开创者。',u:'https://www.intuitive.com',tag:'达芬奇·微创',ic:'🏥'},
{c:'robot',t:'手术机器人',n:'Medtronic Hugo',d:'美敦力 Hugo 手术机器人系统，拓展机器人辅助手术边界。',u:'https://www.medtronic.com',tag:'美敦力·RAS',ic:'⚕️'},
{c:'robot',t:'手术机器人',n:'CMR Surgical',d:'英国手术机器人公司 Versius，模块化便携设计领先。',u:'https://cmrsurgical.com',tag:'英国·模块化',ic:'🇬🇧'},
{c:'robot',t:'手术机器人',n:'天智航',d:'中国骨科手术机器人领导者，TiRobot 系列国内装机第一。',u:'https://www.tmed.com.cn',tag:'骨科·国产',ic:'🦴'},

{c:'robot',t:'物流机器人',n:'极智嘉 Geek+',d:'全球仓储物流 AMR 机器人领军企业，服务 40+ 国家。',u:'https://www.geekplus.com',tag:'仓储·AMR',ic:'📦'},
{c:'robot',t:'物流机器人',n:'Locus Robotics',d:'美国仓储 AMR 机器人公司，人机协同提升拣选效率。',u:'https://locusrobotics.com',tag:'拣选·协同',ic:'🤖'},
{c:'robot',t:'物流机器人',n:'海柔创新',d:'HAI ROBOTICS，箱式仓储机器人首创者，ACR 系统全球领先。',u:'https://www.hairobotics.com',tag:'箱式·ACR',ic:'📬'},
{c:'robot',t:'物流机器人',n:'Seegrid',d:'美国无人叉车与物流机器人公司，视觉导航技术深厚。',u:'https://seegrid.com',tag:'叉车·视觉导航',ic:'🛒'},

{c:'robot',t:'外骨骼',n:'Ekso Bionics',d:'工业与医疗外骨骼先驱，EksoNR 获 FDA 批准用于康复。',u:'https://www.eksobionics.com',tag:'工业·医疗',ic:'🦾'},
{c:'robot',t:'外骨骼',n:'ReWalk Robotics',d:'全球首个获 FDA 批准的个人外骨骼系统，助力截瘫行走。',u:'https://rewalk.com',tag:'FDA·截瘫',ic:'🚶'},
{c:'robot',t:'外骨骼',n:'SuitX',d:'模块化工业外骨骼，Ottobock 旗下品牌降低工伤风险。',u:'https://www.suitx.com',tag:'模块·工业',ic:'🛡️'},

{c:'robot',t:'农业机器人',n:'Blue River Technology',d:'John Deere 旗下 AI 农业公司，精准识别并处理每一株作物。',u:'https://www.bluerivertechnology.com',tag:'精准·杂草识别',ic:'🌿'},
{c:'robot',t:'农业机器人',n:'FarmBot',d:'开源的自动化微型农场机器人，全程自动播种与灌溉。',u:'https://farm.bot',tag:'开源·微型农场',ic:'🌾'},
{c:'robot',t:'农业机器人',n:'Carbon Robotics',d:'AI 激光除草机器人，用高功率激光精准消灭杂草零农药。',u:'https://carbonrobotics.com',tag:'激光·除草',ic:'⚡'},
{c:'robot',t:'农业机器人',n:'丰疆智能',d:'中国智慧农业机器人头部企业，自动驾驶农机落地多国。',u:'https://www.fj-dynamics.com',tag:'农机·国产',ic:'🚜'},
{c:'robot',t:'农业机器人',n:'Iron Ox',d:'AI 温室农业机器人，全自动化蔬菜种植以减少资源消耗。',u:'https://ironox.com',tag:'温室·种植',ic:'🥬'},

{c:'robot',t:'水下机器人',n:'Oceaneering',d:'全球领先的深海工程与 ROV 遥控水下机器人服务商。',u:'https://www.oceaneering.com',tag:'深海·ROV',ic:'🌊'},
{c:'robot',t:'水下机器人',n:'Saab Seaeye',d:'萨博旗下电动水下机器人，用于海洋勘探与水下检测。',u:'https://www.saabseaeye.com',tag:'勘探·检测',ic:'⚓'},
{c:'robot',t:'水下机器人',n:'Blue Robotics',d:'开源海洋机器人组件供应商，水下推进器与 ROV 套件。',u:'https://bluerobotics.com',tag:'开源·组件',ic:'🔷'},
{c:'robot',t:'水下机器人',n:'深之蓝',d:'中国水下智能装备领军者，消费级与工业级水下机器人齐备。',u:'https://www.deepinfar.com',tag:'国产·水下',ic:'🤿'},

{c:'robot',t:'机器人赛事',n:'RoboCup',d:'机器人世界杯，全球最权威的机器人竞技与学术交流赛事。',u:'https://www.robocup.org',tag:'竞技·学术',ic:'🏆'},
{c:'robot',t:'机器人赛事',n:'FIRST Robotics',d:'全球最大的青少年机器人竞赛组织，激发下一代工程师。',u:'https://www.firstinspires.org',tag:'青少年·教育',ic:'🤖'},
{c:'robot',t:'机器人赛事',n:'VEX Robotics',d:'全球规模最大的中小学生机器人竞赛平台之一。',u:'https://www.vexrobotics.com',tag:'学生·竞赛',ic:'⚙️'},
{c:'robot',t:'机器人赛事',n:'Maker Faire',d:'全球创客与机器人爱好者盛会，展示各类 DIY 机器人项目。',u:'https://makerfaire.com',tag:'创客·DIY',ic:'🛠️'},

{c:'robot',t:'机器人教育',n:'LEGO Education',d:'乐高教育系列，SPIKE Prime 和 Mindstorms 编程机器人。',u:'https://education.lego.com',tag:'乐高·编程',ic:'🧱'},
{c:'robot',t:'机器人教育',n:'Arduino',d:'开源电子原型平台，机器人设计与创客教育入门首选。',u:'https://www.arduino.cc',tag:'开源·电子',ic:'⚡'},
{c:'robot',t:'机器人教育',n:'Raspberry Pi',d:'微型单板计算机，机器人控制与 AI 边缘计算理想平台。',u:'https://www.raspberrypi.com',tag:'单板·边缘',ic:'🥧'},
{c:'robot',t:'机器人教育',n:'micro:bit',d:'BBC 主导的微型编程教育计算机，全球学校广泛采用。',u:'https://microbit.org',tag:'微型·编程',ic:'🔲'},
{c:'robot',t:'机器人教育',n:'Makeblock',d:'中国 STEAM 教育机器人品牌，mBot 系列全球畅销。',u:'https://www.makeblock.com',tag:'STEAM·国产',ic:'🤖'},

{c:'models',t:'模型平台',n:'Hugging Face',d:'全球最大的 AI 模型社区与开源平台，托管数十万模型与数据集。',u:'https://huggingface.co',tag:'社区·开源',ic:'🤗'},
{c:'models',t:'模型平台',n:'ModelScope 魔搭',d:'阿里云推出的中文 AI 模型开源社区，汇集国内优质模型。',u:'https://modelscope.cn',tag:'阿里·国产',ic:'🧩'},
{c:'models',t:'模型平台',n:'Ollama',d:'本地运行大语言模型的最简单方式，支持 Llama、Mistral 等。',u:'https://ollama.ai',tag:'本地部署·简易',ic:'🦙'},
{c:'models',t:'模型平台',n:'Replicate',d:'一键运行和部署开源 AI 模型的云平台，API 简单易用。',u:'https://replicate.com',tag:'云运行·API',ic:'☁️'},
{c:'models',t:'模型平台',n:'Civitai',d:'Stable Diffusion 模型与 LoRA 的最大分享社区，创作者天堂。',u:'https://civitai.com',tag:'SD模型·社区',ic:'🏛️'},
{c:'models',t:'模型平台',n:'OpenRouter',d:'统一的 LLM API 网关，一站调用 200+ 模型，按量付费。',u:'https://openrouter.ai',tag:'API网关·多模型',ic:'🔀'},
{c:'models',t:'模型平台',n:'Together AI',d:'开源模型推理与微调平台，提供极速 GPU 推理 API。',u:'https://www.together.ai',tag:'推理·微调',ic:'⚡'},
{c:'models',t:'模型平台',n:'Fireworks AI',d:'极低延迟的开源模型推理平台，专为生产环境优化。',u:'https://fireworks.ai',tag:'低延迟·生产',ic:'🎆'},
{c:'models',t:'模型平台',n:'Groq',d:'LPU 推理引擎驱动的极速 LLM 推理服务，毫秒级响应。',u:'https://groq.com',tag:'LPU·极速',ic:'💨'},
{c:'models',t:'模型平台',n:'OctoAI',d:'高效 AI 推理优化与模型部署平台，大幅降低部署成本。',u:'https://octo.ai',tag:'推理优化·降本',ic:'🐙'},
{c:'models',t:'模型平台',n:'Anyscale',d:'Ray 框架商业化平台，大规模分布式 AI 推理与训练引擎。',u:'https://www.anyscale.com',tag:'Ray·分布式',ic:'⚡'},
{c:'models',t:'模型平台',n:'Modal',d:'高性能无服务器 GPU 云，AI 模型推理与批处理秒级弹性。',u:'https://modal.com',tag:'无服务器·GPU',ic:'☁️'},
{c:'models',t:'模型平台',n:'Banana Dev',d:'AI 模型部署平台，几行代码将 ML 模型转化为生产 API。',u:'https://www.banana.dev',tag:'部署·API',ic:'🍌'},
{c:'models',t:'模型平台',n:'Baseten',d:'高性能开源模型推理服务，专为生产级 LLM 部署优化。',u:'https://www.baseten.co',tag:'生产·LLM',ic:'⚡'},
{c:'models',t:'模型平台',n:'Leap AI',d:'AI 模型 API 化平台，快速为图片和文本模型生成 API。',u:'https://www.tryleap.ai',tag:'API·快速',ic:'🚀'},

{c:'models',t:'开源模型',n:'Llama',d:'Meta 发布的开源大语言模型系列，当前最受欢迎的开源基座。',u:'https://llama.meta.com',tag:'Meta·开源',ic:'🦙'},
{c:'models',t:'开源模型',n:'Mistral',d:'法国 AI 公司推出的高性能开源模型，轻量高效部署友好。',u:'https://mistral.ai',tag:'欧洲·高效',ic:'🌪️'},
{c:'models',t:'开源模型',n:'Qwen',d:'阿里通义千问开源模型系列，覆盖多种尺寸与多模态。',u:'https://github.com/QwenLM/Qwen',tag:'阿里·多尺寸',ic:'🏯'},
{c:'models',t:'开源模型',n:'Gemma',d:'Google 推出的轻量开源模型系列，适合端侧部署与实验。',u:'https://ai.google.dev/gemma',tag:'Google·轻量',ic:'💎'},
{c:'models',t:'开源模型',n:'Phi',d:'微软研究院推出的小语言模型，在手机和笔记本上流畅运行。',u:'https://azure.microsoft.com/products/phi',tag:'微软·小模型',ic:'📱'},
{c:'models',t:'开源模型',n:'Yi 零一万物',d:'零一万物开源的大语言模型系列，中英文能力高度平衡。',u:'https://www.lingyiwanwu.com',tag:'零一·中英',ic:'☯'},
{c:'models',t:'开源模型',n:'DeepSeek Models',d:'深度求索开源模型系列，MoE 架构效率与性能双领先。',u:'https://huggingface.co/deepseek-ai',tag:'MoE·高效',ic:'🔮'},
{c:'models',t:'开源模型',n:'DBRX by Databricks',d:'Databricks 推出的开源 MoE 模型，高效推理与企业级性能。',u:'https://www.databricks.com',tag:'MoE·Databricks',ic:'🧱'},
{c:'models',t:'开源模型',n:'OLMo by Allen AI',d:'Allen 人工智能研究所构建的完全开源的大语言模型。',u:'https://allenai.org/olmo',tag:'学术·完全开源',ic:'🏛️'},
{c:'models',t:'开源模型',n:'IBM Granite',d:'IBM 企业级开源模型系列，专为业务工作流和编码优化。',u:'https://www.ibm.com/granite',tag:'IBM·企业',ic:'💼'},
{c:'models',t:'开源模型',n:'Snowflake Arctic',d:'Snowflake 推出的企业智能开源大模型，高效 SQL 与编码。',u:'https://www.snowflake.com',tag:'企业·编码',ic:'❄️'},

{c:'models',t:'向量数据库',n:'Pinecone',d:'全托管向量数据库，为 LLM 应用提供高性能语义检索。',u:'https://www.pinecone.io',tag:'托管·语义检索',ic:'🌲'},
{c:'models',t:'向量数据库',n:'Weaviate',d:'开源向量数据库，内置向量化模块，支持 GraphQL 查询。',u:'https://weaviate.io',tag:'开源·GraphQL',ic:'🔍'},
{c:'models',t:'向量数据库',n:'Chroma',d:'开源 AI 原生向量数据库，AI 应用开发者的入门首选。',u:'https://www.trychroma.com',tag:'开源·入门',ic:'🎨'},
{c:'models',t:'向量数据库',n:'Milvus',d:'全球最流行的开源向量数据库之一，云原生弹性架构。',u:'https://milvus.io',tag:'开源·云原生',ic:'🐘'},
{c:'models',t:'向量数据库',n:'Qdrant',d:'高性能开源向量搜索引擎，Rust 编写延迟极低。',u:'https://qdrant.tech',tag:'Rust·高性能',ic:'🦀'},
{c:'models',t:'向量数据库',n:'Elasticsearch',d:'老牌搜索引擎，向量检索与全文检索一体化，生态庞大。',u:'https://www.elastic.co',tag:'搜索·生态',ic:'🔎'},

{c:'models',t:'AI开发框架',n:'LangChain',d:'最流行的 LLM 应用开发框架，链式编排 AI 工作流。',u:'https://www.langchain.com',tag:'编排·链式',ic:'⛓️'},
{c:'models',t:'AI开发框架',n:'LlamaIndex',d:'数据索引与 RAG 框架，轻松构建知识增强型 AI 应用。',u:'https://www.llamaindex.ai',tag:'RAG·索引',ic:'📇'},
{c:'models',t:'AI开发框架',n:'Langfuse',d:'开源 LLM 应用可观测平台，追踪、监控与调试 AI 调用。',u:'https://langfuse.com',tag:'可观测·调试',ic:'📊'},
{c:'models',t:'AI开发框架',n:'Vercel AI SDK',d:'Vercel 推出的 AI 应用开发工具包，快速搭建 AI 前端。',u:'https://sdk.vercel.ai',tag:'前端·工具包',ic:'▲'},
{c:'models',t:'AI开发框架',n:'Haystack',d:'deepset 开源的 NLP 框架，构建可扩展的检索与问答系统。',u:'https://haystack.deepset.ai',tag:'NLP·检索',ic:'🧱'},

{c:'models',t:'开源 AI 项目',n:'TensorFlow',d:'Google 推出的端到端开源机器学习平台，工业界广泛使用。',u:'https://www.tensorflow.org',tag:'Google·工业',ic:'🔶'},
{c:'models',t:'开源 AI 项目',n:'PyTorch',d:'Meta 推出的开源深度学习框架，学术研究领域首选工具。',u:'https://pytorch.org',tag:'Meta·学术',ic:'🔥'},
{c:'models',t:'开源 AI 项目',n:'OpenCV',d:'开源计算机视觉库，2500+ 优化算法覆盖图像处理全流程。',u:'https://opencv.org',tag:'视觉·开源',ic:'👁️'},
{c:'models',t:'开源 AI 项目',n:'Keras',d:'高级深度学习 API，TensorFlow 上层接口极简构建神经网络。',u:'https://keras.io',tag:'API·简洁',ic:'🧠'},
{c:'models',t:'开源 AI 项目',n:'ONNX',d:'开放神经网络交换格式，跨框架模型互操作性的行业标准。',u:'https://onnx.ai',tag:'互操作·标准',ic:'🔄'},
{c:'models',t:'开源 AI 项目',n:'JAX',d:'Google 开源高性能数值计算库，自动微分与 XLA 编译加速。',u:'https://jax.readthedocs.io',tag:'Google·高性能',ic:'⚡'},

{c:'models',t:'MLOps',n:'Weights & Biases',d:'最流行的 ML 实验追踪与可视化平台，团队协作神器。',u:'https://wandb.ai',tag:'实验追踪·可视化',ic:'📈'},
{c:'models',t:'MLOps',n:'MLflow',d:'Databricks 旗下开源 ML 全生命周期管理平台，行业标准。',u:'https://mlflow.org',tag:'开源·全生命周期',ic:'⚙️'},
{c:'models',t:'MLOps',n:'Neptune.ai',d:'ML 实验追踪与模型注册中心，企业级元数据管理。',u:'https://neptune.ai',tag:'企业·元数据',ic:'🔱'},
{c:'models',t:'MLOps',n:'ClearML',d:'开源 ML/DL 实验管理与编排平台，一站式 MLOps 方案。',u:'https://clear.ml',tag:'开源·编排',ic:'🧊'},
{c:'models',t:'MLOps',n:'BentoML',d:'开源 AI 模型部署与服务框架，模型到 API 只需几分钟。',u:'https://www.bentoml.com',tag:'模型部署·API',ic:'🍱'},
{c:'models',t:'MLOps',n:'DagsHub',d:'ML 协作平台，Git 风格管理数据、模型与实验版本化。',u:'https://dagshub.com',tag:'Git·版本化',ic:'🐕'},
{c:'models',t:'MLOps',n:'Metaflow',d:'Netflix 开源的 ML 项目框架，从原型到生产的全流程管理。',u:'https://metaflow.org',tag:'Netflix·全流程',ic:'🎬'},
{c:'models',t:'MLOps',n:'Kubeflow',d:'Kubernetes 原生 ML 工作流平台，分布式训练与部署利器。',u:'https://www.kubeflow.org',tag:'K8s·分布式',ic:'☸️'},
{c:'models',t:'MLOps',n:'Seldon',d:'开源 ML 模型部署与管理平台，云原生模型服务框架。',u:'https://www.seldon.io',tag:'云原生·部署',ic:'🌐'},
{c:'models',t:'MLOps',n:'Valohai',d:'ML 训练流水线自动化平台，一键复现实验且自动部署。',u:'https://valohai.com',tag:'自动化·复现',ic:'🔁'},

{c:'models',t:'数据标注',n:'Scale AI',d:'全球最大的 AI 数据标注与数据引擎平台，估值超百亿。',u:'https://scale.com',tag:'标注·数据引擎',ic:'⚖️'},
{c:'models',t:'数据标注',n:'Labelbox',d:'企业级数据标注与 AI 数据引擎，端到端数据管理。',u:'https://labelbox.com',tag:'企业·端到端',ic:'🏷️'},
{c:'models',t:'数据标注',n:'Label Studio',d:'开源多模态数据标注平台，支持文本、图像、音频、视频。',u:'https://labelstud.io',tag:'开源·多模态',ic:'🏗️'},
{c:'models',t:'数据标注',n:'SuperAnnotate',d:'AI 辅助数据标注与模型管理，自动化标注加速迭代。',u:'https://www.superannotate.com',tag:'自动化·模型管理',ic:'🚀'},
{c:'models',t:'数据标注',n:'Snorkel AI',d:'程序化数据标注与弱监督学习平台，以编程替代手工标注。',u:'https://snorkel.ai',tag:'程序化·弱监督',ic:'🤿'},

{c:'models',t:'AI 安全',n:'Credo AI',d:'AI 治理与风险平台，自动评估模型公平性与合规性。',u:'https://www.credo.ai',tag:'治理·合规',ic:'🛡️'},
{c:'models',t:'AI 安全',n:'Robust Intelligence',d:'AI 安全平台，自动检测模型漏洞防御对抗性攻击。',u:'https://www.robustintelligence.com',tag:'攻击·防御',ic:'🔒'},
{c:'models',t:'AI 安全',n:'Arthur AI',d:'LLM 监控与安全平台，实时检测幻觉、偏见和有害输出。',u:'https://www.arthur.ai',tag:'监控·LLM安全',ic:'👑'},
{c:'models',t:'AI 安全',n:'WhyLabs',d:'AI 可观测与数据监控平台，LangKit 检测 LLM 质量问题。',u:'https://whylabs.ai',tag:'可观测·质量',ic:'🔬'},
{c:'models',t:'AI 安全',n:'Guardrails AI',d:'开源 LLM 护栏框架，以规则约束 AI 输出保障安全合规。',u:'https://www.guardrailsai.com',tag:'护栏·开源',ic:'🛤️'},

{c:'models',t:'AI 评测',n:'LMSYS Chatbot Arena',d:'UC Berkeley 主导的 LLM 竞技场，众包盲测模型排行榜。',u:'https://lmsys.org',tag:'竞技场·排行榜',ic:'🏟️'},
{c:'models',t:'AI 评测',n:'Stanford HELM',d:'斯坦福全生命周期语言模型评测，多维度全面评估 LLM。',u:'https://crfm.stanford.edu/helm',tag:'全维度·学术',ic:'🎓'},
{c:'models',t:'AI 评测',n:'Galileo',d:'AI 模型评估与可观测平台，快速发现与修复模型错误。',u:'https://www.rungalileo.io',tag:'评估·纠错',ic:'🔭'},
{c:'models',t:'AI 评测',n:'DeepEval',d:'开源 LLM 评测框架，单元测试方式量化评估模型质量。',u:'https://docs.confident-ai.com',tag:'单元测试·开源',ic:'✅'},
{c:'models',t:'AI 评测',n:'TruLens',d:'开源 LLM 应用反馈与评估框架，追踪 RAG 管道质量指标。',u:'https://www.trulens.org',tag:'RAG评估·开源',ic:'📏'},

{c:'blockchain',t:'公链平台',n:'Ethereum',d:'全球最大的智能合约平台，DeFi 与 NFT 生态的核心基础设施。',u:'https://ethereum.org',tag:'智能合约·DeFi',ic:'💎'},
{c:'blockchain',t:'公链平台',n:'Solana',d:'高性能 Layer1 公链，以高 TPS 和低费用著称，生态繁荣。',u:'https://solana.com',tag:'高性能·低费',ic:'☀️'},
{c:'blockchain',t:'公链平台',n:'Bitcoin',d:'全球第一个去中心化数字货币，区块链技术的开创者。',u:'https://bitcoin.org',tag:'P2P·数字黄金',ic:'₿'},
{c:'blockchain',t:'公链平台',n:'Polygon',d:'以太坊 Layer2 扩容解决方案，提供更快更便宜的交易。',u:'https://polygon.technology',tag:'L2·扩容',ic:'🔷'},
{c:'blockchain',t:'公链平台',n:'Arbitrum',d:'Optimistic Rollup 龙头，以太坊最受欢迎的 Layer2 网络。',u:'https://arbitrum.io',tag:'L2·Optimistic',ic:'🔵'},
{c:'blockchain',t:'公链平台',n:'Optimism',d:'以太坊 Layer2 OP Stack 核心贡献者，推动超级链愿景。',u:'https://www.optimism.io',tag:'L2·Superchain',ic:'🔴'},
{c:'blockchain',t:'公链平台',n:'Sui',d:'Meta 前团队打造的新一代高性能 Layer1，Move 语言原生。',u:'https://sui.io',tag:'Move·高性能',ic:'💧'},
{c:'blockchain',t:'公链平台',n:'Aptos',d:'由 Meta Diem 项目衍生而来的 Layer1 公链，安全可扩展。',u:'https://aptoslabs.com',tag:'Move·安全',ic:'🌊'},
{c:'blockchain',t:'公链平台',n:'Polkadot',d:'跨链互操作协议，连接多条专用区块链实现数据互通。',u:'https://polkadot.network',tag:'跨链·互操作',ic:'🔗'},
{c:'blockchain',t:'公链平台',n:'Avalanche',d:'高性能可定制区块链平台，子网架构灵活可定制。',u:'https://www.avax.network',tag:'子网·定制',ic:'❄️'},
{c:'blockchain',t:'公链平台',n:'Cardano',d:'学术研究驱动的 PoS 公链，采用 Haskell 实现高安全。',u:'https://cardano.org',tag:'学术·PoS',ic:'🔷'},
{c:'blockchain',t:'公链平台',n:'BNB Chain',d:'Binance 官方公链，交易费低廉，GameFi 与 DeFi 生态繁荣。',u:'https://www.bnbchain.org',tag:'Binance·GameFi',ic:'🟡'},
{c:'blockchain',t:'公链平台',n:'COSMOS',d:'跨链生态协议，IBC 协议实现多链资产与数据互操作。',u:'https://cosmos.network',tag:'IBC·跨链',ic:'🌌'},
{c:'blockchain',t:'公链平台',n:'Near Protocol',d:'分片技术驱动的 L1 公链，开发体验友好，生态快速增长。',u:'https://near.org',tag:'分片·开发者友好',ic:'🌙'},
{c:'blockchain',t:'公链平台',n:'Tron',d:'高吞吐量公链，USDT 流通量最大的区块链网络之一。',u:'https://tron.network',tag:'USDT·高吞吐',ic:'🔴'},
{c:'blockchain',t:'公链平台',n:'Algorand',d:'MIT 教授创立的纯 PoS 公链，碳中和且快速终局不分叉。',u:'https://www.algorand.com',tag:'纯PoS·碳中和',ic:'🟢'},
{c:'blockchain',t:'公链平台',n:'Flow',d:'Dapper Labs 推出的消费者级区块链，NBA Top Shot 同链。',u:'https://flow.com',tag:'消费者·NBA',ic:'🌊'},
{c:'blockchain',t:'公链平台',n:'Tezos',d:'自升级 PoS 公链，链上治理实现无硬分叉协议长期演进。',u:'https://tezos.com',tag:'自升级·治理',ic:'🔷'},
{c:'blockchain',t:'公链平台',n:'Hedera',d:'企业级哈希图共识公链，Google 和 IBM 均参与治理。',u:'https://hedera.com',tag:'哈希图·企业',ic:'🌿'},
{c:'blockchain',t:'公链平台',n:'Zilliqa',d:'分片技术先驱公链，高吞吐量低费用的区块链平台。',u:'https://www.zilliqa.com',tag:'分片·高吞吐',ic:'🔶'},

{c:'blockchain',t:'Layer2 网络',n:'zkSync Era',d:'零知识 Rollup 领跑者，以太坊扩容的同时保障最高安全性。',u:'https://zksync.io',tag:'ZK·安全',ic:'⚡'},
{c:'blockchain',t:'Layer2 网络',n:'StarkNet',d:'STARK 证明驱动的 ZK-Rollup，实现超大规模可扩展性。',u:'https://www.starknet.io',tag:'STARK·规模',ic:'🔲'},
{c:'blockchain',t:'Layer2 网络',n:'Base',d:'Coinbase 孵化的以太坊 L2，背靠过亿用户入口快速成长。',u:'https://www.base.org',tag:'Coinbase·用户',ic:'🔵'},
{c:'blockchain',t:'Layer2 网络',n:'Linea',d:'Consensys 推出的 zkEVM L2，深度集成 MetaMask 生态。',u:'https://linea.build',tag:'Consensys·zkEVM',ic:'📈'},
{c:'blockchain',t:'Layer2 网络',n:'Scroll',d:'字节码兼容的 zkEVM Layer2，以太坊应用零成本迁移。',u:'https://scroll.io',tag:'zkEVM·兼容',ic:'📜'},
{c:'blockchain',t:'Layer2 网络',n:'Mantle',d:'由 BitDAO 演化而来的模块化 L2，采用 EigenDA 数据可用性。',u:'https://www.mantle.xyz',tag:'模块化·EigenDA',ic:'🛡️'},

{c:'blockchain',t:'基础设施',n:'Chainlink',d:'去中心化预言机网络，为智能合约安全提供链下真实数据。',u:'https://chain.link',tag:'预言机·数据',ic:'🔮'},
{c:'blockchain',t:'基础设施',n:'Alchemy',d:'领先的区块链开发者平台，提供节点服务与增强 API。',u:'https://www.alchemy.com',tag:'节点·API',ic:'🧪'},
{c:'blockchain',t:'基础设施',n:'Infura',d:'Consensys 旗下以太坊基础设施服务，节点即服务先驱。',u:'https://infura.io',tag:'以太坊·节点',ic:'🔥'},
{c:'blockchain',t:'基础设施',n:'The Graph',d:'去中心化区块链数据索引协议，高效灵活查询链上数据。',u:'https://thegraph.com',tag:'索引·查询',ic:'📊'},
{c:'blockchain',t:'基础设施',n:'IPFS',d:'星际文件系统，点对点的分布式文件存储与共享网络协议。',u:'https://ipfs.tech',tag:'P2P·分布式',ic:'🌐'},
{c:'blockchain',t:'基础设施',n:'Arweave',d:'永久存储协议，一次付费永久保存数据构建永不忘却的网络。',u:'https://www.arweave.org',tag:'永久存储·Permaweb',ic:'🏛️'},
{c:'blockchain',t:'基础设施',n:'Tenderly',d:'以太坊全栈开发工具套件，调试、模拟与监控智能合约。',u:'https://tenderly.co',tag:'调试·模拟',ic:'🛠️'},
{c:'blockchain',t:'基础设施',n:'QuickNode',d:'高性能区块链 RPC 节点服务商，支持 30+ 主流公链。',u:'https://www.quicknode.com',tag:'RPC·多链',ic:'⚡'},
{c:'blockchain',t:'基础设施',n:'Gnosis',d:'以太坊侧链与预测市场基础设施，Safe 多签钱包发源地。',u:'https://www.gnosis.io',tag:'侧链·预测市场',ic:'🦉'},
{c:'blockchain',t:'基础设施',n:'Livepeer',d:'去中心化视频转码网络，大幅降低视频流媒体基础设施成本。',u:'https://livepeer.org',tag:'视频·转码',ic:'📺'},
{c:'blockchain',t:'基础设施',n:'Pocket Network',d:'去中心化 RPC 协议，由节点运营商网络提供多链数据访问。',u:'https://www.pokt.network',tag:'去中心化RPC·多链',ic:'📡'},
{c:'blockchain',t:'基础设施',n:'Band Protocol',d:'去中心化跨链预言机，为 Web3 应用提供可验证真实数据。',u:'https://www.bandprotocol.com',tag:'预言机·跨链',ic:'📊'},
{c:'blockchain',t:'基础设施',n:'API3',d:'第一方预言机网络，数据提供商直接运行节点保障数据源。',u:'https://api3.org',tag:'第一方·预言机',ic:'🔗'},

{c:'blockchain',t:'去中心化存储',n:'Filecoin',d:'去中心化存储网络，IPFS 的激励层实现数据永续存储。',u:'https://filecoin.io',tag:'存储·IPFS激励',ic:'💾'},
{c:'blockchain',t:'去中心化存储',n:'Storj',d:'去中心化云存储平台，闲置硬盘空间共享经济实现安全存。',u:'https://www.storj.io',tag:'共享·加密',ic:'📦'},
{c:'blockchain',t:'去中心化存储',n:'Crust Network',d:'基于 IPFS 的去中心化云存储激励层，Web3 数据永存方案。',u:'https://crust.network',tag:'IPFS·激励',ic:'🦀'},

{c:'blockchain',t:'跨链桥',n:'Wormhole',d:'通用互操作协议，已连接 30+ 条主流区块链实现跨链通信。',u:'https://wormhole.com',tag:'通用·30+链',ic:'🕳️'},
{c:'blockchain',t:'跨链桥',n:'LayerZero',d:'全链互操作协议，以超轻节点技术实现安全跨链。',u:'https://layerzero.network',tag:'全链·超轻节点',ic:'0️⃣'},
{c:'blockchain',t:'跨链桥',n:'Stargate',d:'基于 LayerZero 的跨链桥，提供统一流动性与即时确认。',u:'https://stargate.finance',tag:'统一流动性·即时',ic:'🌌'},
{c:'blockchain',t:'跨链桥',n:'Across',d:'以太坊跨链桥协议，低成本快速完成 Layer2 间资产转移。',u:'https://across.to',tag:'低成本·L2间',ic:'🌉'},
{c:'blockchain',t:'跨链桥',n:'Synapse',d:'跨链互操作与资产桥接协议，支持 20+ EVM 链安全互通。',u:'https://www.synapseprotocol.com',tag:'EVM·安全桥',ic:'🧬'},

{c:'blockchain',t:'NFT市场',n:'OpenSea',d:'全球最大的 NFT 交易市场，支持以太坊、Polygon 等多链。',u:'https://opensea.io',tag:'NFT·多链',ic:'🌊'},
{c:'blockchain',t:'NFT市场',n:'Blur',d:'专业级 NFT 聚合交易平台，以速度和深度流动性著称。',u:'https://blur.io',tag:'NFT·聚合',ic:'💨'},
{c:'blockchain',t:'NFT市场',n:'Magic Eden',d:'Solana 生态最大的 NFT 市场，跨链扩张至比特币 Ordinals。',u:'https://magiceden.io',tag:'Solana·Ordinals',ic:'🪄'},
{c:'blockchain',t:'NFT市场',n:'Rarible',d:'社区治理的去中心化 NFT 市场，支持多链创建与交易。',u:'https://rarible.com',tag:'社区治理·多链',ic:'🔶'},
{c:'blockchain',t:'NFT市场',n:'SuperRare',d:'高端加密艺术 NFT 平台，精选全球顶尖数字艺术家作品。',u:'https://superrare.com',tag:'高端艺术·精选',ic:'🖼️'},
{c:'blockchain',t:'NFT市场',n:'LooksRare',d:'以社区为核心的 NFT 交易市场，交易挖矿回馈活跃用户。',u:'https://looksrare.org',tag:'社区·交易挖矿',ic:'👀'},
{c:'blockchain',t:'NFT市场',n:'X2Y2',d:'去中心化 NFT 聚合市场，低费率并支持批量交易与挂单。',u:'https://x2y2.io',tag:'低费率·批量',ic:'🔄'},
{c:'blockchain',t:'NFT市场',n:'Foundation',d:'策展型加密艺术平台，艺术家邀请制确保作品高质量。',u:'https://foundation.app',tag:'策展·艺术',ic:'🏛️'},

{c:'blockchain',t:'区块链浏览器',n:'Etherscan',d:'以太坊最权威的区块链浏览器，查询交易与合约源码。',u:'https://etherscan.io',tag:'以太坊·交易',ic:'🔍'},
{c:'blockchain',t:'区块链浏览器',n:'Solscan',d:'Solana 生态最流行的区块链浏览器，账户与代币追踪。',u:'https://solscan.io',tag:'Solana·账户',ic:'☀️'},
{c:'blockchain',t:'区块链浏览器',n:'Polygonscan',d:'Polygon 官方区块链浏览器，查询 L2 交易与合约。',u:'https://polygonscan.com',tag:'Polygon·L2',ic:'🔷'},
{c:'blockchain',t:'区块链浏览器',n:'BscScan',d:'BNB Chain 官方区块链浏览器，追踪 BSC 所有链上活动。',u:'https://bscscan.com',tag:'BNB·BSC',ic:'🟡'},
{c:'blockchain',t:'区块链浏览器',n:'Tronscan',d:'Tron 区块链官方浏览器，查询 USDT 转账与智能合约。',u:'https://tronscan.org',tag:'Tron·USDT',ic:'🔴'},

{c:'blockchain',t:'Web3 开发',n:'Hardhat',d:'以太坊智能合约开发框架，本地测试与部署的首选工具。',u:'https://hardhat.org',tag:'合约·测试',ic:'🪖'},
{c:'blockchain',t:'Web3 开发',n:'Foundry',d:'Rust 编写的极速以太坊智能合约开发与测试工具套件。',u:'https://book.getfoundry.sh',tag:'Rust·极速',ic:'🦀'},
{c:'blockchain',t:'Web3 开发',n:'Thirdweb',d:'Web3 全栈开发平台，零门槛构建 NFT、代币与市场应用。',u:'https://thirdweb.com',tag:'全栈·零门槛',ic:'🛠️'},
{c:'blockchain',t:'Web3 开发',n:'Remix',d:'以太坊官方智能合约在线 IDE，快速编写与部署 Solidity。',u:'https://remix.ethereum.org',tag:'在线IDE·Solidity',ic:'🧩'},
{c:'blockchain',t:'Web3 开发',n:'Moralis',d:'Web3 后端即服务平台，一站式构建去中心化应用后端。',u:'https://moralis.io',tag:'BaaS·API',ic:'⚡'},

{c:'blockchain',t:'DePIN',n:'Helium',d:'去中心化物联网网络，用户共享热点赚取代币覆盖 LoRaWAN。',u:'https://www.helium.com',tag:'物联网·LoRaWAN',ic:'🎈'},
{c:'blockchain',t:'DePIN',n:'Hivemapper',d:'去中心化地图网络，行车记录仪采集街景以代币激励贡献者。',u:'https://hivemapper.com',tag:'地图·众包',ic:'🗺️'},
{c:'blockchain',t:'DePIN',n:'IoTeX',d:'Web3 物联网公链，连接真实世界设备到区块链实现数据确权。',u:'https://www.iotex.io',tag:'物联网·公链',ic:'📡'},
{c:'blockchain',t:'DePIN',n:'Akash Network',d:'去中心化云计算市场，闲置 GPU 算力共享降低 AI 训练成本。',u:'https://akash.network',tag:'云计算·共享',ic:'☁️'},
{c:'blockchain',t:'DePIN',n:'DIMO',d:'去中心化车辆数据网络，车主分享行车数据赚取 DIMO 代币。',u:'https://dimo.zone',tag:'车辆·数据',ic:'🚗'},

{c:'blockchain',t:'RWA 现实资产',n:'Ondo Finance',d:'代币化美国国债与现实资产发行平台，链上获取传统金融收益。',u:'https://ondo.finance',tag:'国债·代币化',ic:'🏦'},
{c:'blockchain',t:'RWA 现实资产',n:'Centrifuge',d:'去中心化真实资产融资协议，将发票与应收账款引入链上。',u:'https://centrifuge.io',tag:'资产融资·应收账款',ic:'🏭'},
{c:'blockchain',t:'RWA 现实资产',n:'Maple Finance',d:'去中心化机构借贷平台，高信用借款人获得低抵押贷款。',u:'https://www.maple.finance',tag:'机构·低抵押',ic:'🍁'},
{c:'blockchain',t:'RWA 现实资产',n:'Goldfinch',d:'去中心化信贷协议，为新兴市场提供无抵押加密贷款。',u:'https://goldfinch.finance',tag:'信贷·新兴市场',ic:'🐦'},
{c:'blockchain',t:'RWA 现实资产',n:'Parcl',d:'合成房地产投资协议，以代币追踪全球城市房价涨跌。',u:'https://parcl.co',tag:'地产·合成',ic:'🏘️'},

{c:'blockchain',t:'链游平台',n:'Gods Unchained',d:'免费区块链卡牌游戏，Immutable X 运行，真正的卡牌所有权。',u:'https://godsunchained.com',tag:'卡牌·Immutable',ic:'⚔️'},
{c:'blockchain',t:'链游平台',n:'Splinterlands',d:'区块链卡牌对战游戏，Hive 区块链运行，日活百万级。',u:'https://splinterlands.com',tag:'卡牌·Hive',ic:'🃏'},
{c:'blockchain',t:'链游平台',n:'Alien Worlds',d:'去中心化元宇宙挖矿游戏，跨链 NFT 探索外星世界。',u:'https://alienworlds.io',tag:'元宇宙·挖矿',ic:'👽'},
{c:'blockchain',t:'链游平台',n:'Vulcan Forged',d:'NFT 游戏工作室与去中心化应用市场，多款热门链游。',u:'https://vulcanforged.com',tag:'工作室·市场',ic:'🔨'},
{c:'blockchain',t:'链游平台',n:'My Neighbor Alice',d:'区块链多人建造游戏，社交与 NFT 农场结合治愈系风格。',u:'https://www.myneighboralice.com',tag:'建造·社交',ic:'🏡'},

{c:'blockchain',t:'隐私公链',n:'Monero',d:'最具影响力的隐私币，默认匿名保障交易发送方与接收方隐私。',u:'https://www.getmonero.org',tag:'匿名·交易',ic:'🕵️'},
{c:'blockchain',t:'隐私公链',n:'Zcash',d:'学术密码学驱动的隐私币，zk-SNARKs 零知识证明加密交易。',u:'https://z.cash',tag:'zkSNARK·学术',ic:'🔐'},
{c:'blockchain',t:'隐私公链',n:'Aleo',d:'基于零知识证明的隐私智能合约平台，默认隐私可编程。',u:'https://aleo.org',tag:'ZK·智能合约',ic:'🕶️'},
{c:'blockchain',t:'隐私公链',n:'Iron Fish',d:'全链路加密的隐私 L1 公链，所有交易默认不可见。',u:'https://ironfish.network',tag:'全链路·加密',ic:'🐟'},
{c:'blockchain',t:'隐私公链',n:'Oasis Network',d:'隐私优先的 L1 公链，TEE 与零知识技术保护用户数据。',u:'https://oasisprotocol.org',tag:'TEE·隐私',ic:'🟢'},

{c:'crypto',t:'行情数据',n:'CoinMarketCap',d:'全球最权威的加密货币市值排名与数据聚合平台。',u:'https://coinmarketcap.com',tag:'市值·排名',ic:'📊'},
{c:'crypto',t:'行情数据',n:'CoinGecko',d:'全面的加密货币数据平台，提供代币基本面的深度分析。',u:'https://www.coingecko.com',tag:'数据·分析',ic:'🦎'},
{c:'crypto',t:'行情数据',n:'TradingView',d:'专业级行情图表工具，支持加密货币与股票的技术分析。',u:'https://www.tradingview.com',tag:'图表·技术分析',ic:'📈'},
{c:'crypto',t:'行情数据',n:'DefiLlama',d:'DeFi 全链 TVL 数据聚合平台，追踪各协议总锁仓价值。',u:'https://defillama.com',tag:'TVL·DeFi',ic:'🦙'},
{c:'crypto',t:'行情数据',n:'Dune Analytics',d:'链上数据分析平台，用 SQL 查询并可视化区块链数据。',u:'https://dune.com',tag:'链上·SQL',ic:'🏜️'},
{c:'crypto',t:'行情数据',n:'Nansen',d:'链上智能分析平台，追踪 Smart Money 与巨鲸实时动向。',u:'https://www.nansen.ai',tag:'SmartMoney·巨鲸',ic:'🐋'},
{c:'crypto',t:'行情数据',n:'Glassnode',d:'专业级链上数据与研究平台，洞察市场周期与链上指标。',u:'https://glassnode.com',tag:'链上研究·周期',ic:'🔍'},
{c:'crypto',t:'行情数据',n:'Messari',d:'加密资产研究平台，提供深度行业报告与治理追踪。',u:'https://messari.io',tag:'研究·报告',ic:'📖'},
{c:'crypto',t:'行情数据',n:'Arkham',d:'链上身份追踪与情报平台，可视化实体持仓与资金流向。',u:'https://www.arkhamintelligence.com',tag:'链上情报·身份',ic:'🕵️'},
{c:'crypto',t:'行情数据',n:'Token Terminal',d:'加密项目财务报表式数据分析，对标传统金融基本面指标。',u:'https://tokenterminal.com',tag:'财务·指标',ic:'💹'},

{c:'crypto',t:'交易所',n:'Binance',d:'全球交易量最大的加密货币交易所，生态体系全面完善。',u:'https://www.binance.com',tag:'CEX·生态',ic:'🟡'},
{c:'crypto',t:'交易所',n:'OKX',d:'全球领先的加密货币交易所与 Web3 自托管钱包平台。',u:'https://www.okx.com',tag:'CEX·Web3',ic:'⚪'},
{c:'crypto',t:'交易所',n:'Coinbase',d:'美国最大的合规加密货币交易所，纳斯达克上市受 SEC 监管。',u:'https://www.coinbase.com',tag:'合规·美股',ic:'🔵'},
{c:'crypto',t:'交易所',n:'Uniswap',d:'以太坊上最大的去中心化交易所（DEX），AMM 做市先驱。',u:'https://uniswap.org',tag:'DEX·AMM',ic:'🦄'},
{c:'crypto',t:'交易所',n:'Jupiter',d:'Solana 生态最大的聚合 DEX，自动寻找最优兑换路由。',u:'https://jup.ag',tag:'Solana·聚合',ic:'🪐'},
{c:'crypto',t:'交易所',n:'Bybit',d:'全球前三的加密货币衍生品交易所，交易深度与产品线丰富。',u:'https://www.bybit.com',tag:'衍生品·深度',ic:'🌐'},
{c:'crypto',t:'交易所',n:'Kraken',d:'美国老牌合规交易所，以顶级安全和法币出入金便捷著称。',u:'https://www.kraken.com',tag:'合规·法币',ic:'🐙'},
{c:'crypto',t:'交易所',n:'Gate.io',d:'老牌交易所，币种数量超 2000，首发新资产速度优势明显。',u:'https://www.gate.io',tag:'多币种·首发',ic:'🚪'},
{c:'crypto',t:'交易所',n:'KuCoin',d:'全球知名综合性交易所，以发掘优质早期项目广受好评。',u:'https://www.kucoin.com',tag:'早期项目·综合',ic:'🪙'},
{c:'crypto',t:'交易所',n:'Bitget',d:'合约交易量全球领先的交易所，跟单交易功能业内最成熟。',u:'https://www.bitget.com',tag:'合约·跟单',ic:'💪'},
{c:'crypto',t:'交易所',n:'Crypto.com',d:'全球知名加密平台，拥有 VISA 卡与庞大用户基础的生态体系。',u:'https://crypto.com',tag:'VISA卡·生态',ic:'🔵'},
{c:'crypto',t:'交易所',n:'Gemini',d:'Winklevoss 兄弟创立的合规交易所，纽约州持牌安全优先。',u:'https://www.gemini.com',tag:'合规·纽约',ic:'♊'},
{c:'crypto',t:'交易所',n:'HTX',d:'火币全球站，亚太区老牌交易所资产储备与流动性实力雄厚。',u:'https://www.htx.com',tag:'亚太·老牌',ic:'🔥'},
{c:'crypto',t:'交易所',n:'Bitfinex',d:'老牌专业级交易平台，提供高级交易功能与深度流动性。',u:'https://www.bitfinex.com',tag:'专业·高级',ic:'💱'},
{c:'crypto',t:'交易所',n:'MEXC',d:'以闪电般上币速度和海量币种著称的全球化交易所。',u:'https://www.mexc.com',tag:'快上币·多币种',ic:'⚡'},

{c:'crypto',t:'钱包',n:'MetaMask',d:'最流行的以太坊钱包浏览器插件，玩转 DeFi 的必备入口。',u:'https://metamask.io',tag:'钱包·浏览器',ic:'🦊'},
{c:'crypto',t:'钱包',n:'Phantom',d:'Solana 生态首选钱包，支持浏览器插件与移动端无缝体验。',u:'https://phantom.app',tag:'Solana·多设备',ic:'👻'},
{c:'crypto',t:'钱包',n:'Ledger',d:'全球领先的硬件冷钱包品牌，私钥离线存储安全保障资产。',u:'https://www.ledger.com',tag:'硬件·冷存储',ic:'🔒'},
{c:'crypto',t:'钱包',n:'Trust Wallet',d:'Binance 旗下多链移动钱包，支持百万种加密资产管理。',u:'https://trustwallet.com',tag:'多链·移动',ic:'🛡️'},
{c:'crypto',t:'钱包',n:'Rabby',d:'DeBank 团队打造的以太坊钱包，交易前自动风险扫描与模拟。',u:'https://rabby.io',tag:'安全·模拟',ic:'🐰'},
{c:'crypto',t:'钱包',n:'Rainbow',d:'设计优雅的以太坊移动钱包，iOS/Android 原生交互体验出色。',u:'https://rainbow.me',tag:'设计·优美',ic:'🌈'},
{c:'crypto',t:'钱包',n:'Trezor',d:'欧洲领先的硬件冷钱包品牌，开源固件安全透明可审计。',u:'https://trezor.io',tag:'硬件·开源',ic:'🔐'},
{c:'crypto',t:'钱包',n:'Safe',d:'多签智能合约钱包，团队金库与 DAO 资产管理的行业标准。',u:'https://safe.global',tag:'多签·金库',ic:'🏦'},
{c:'crypto',t:'钱包',n:'Keplr',d:'COSMOS 生态首选钱包，跨链管理 IBC 资产与质押操作。',u:'https://www.keplr.app',tag:'COSMOS·IBC',ic:'🌌'},
{c:'crypto',t:'钱包',n:'Coin98',d:'东南亚流行的多链钱包，一站式管理 DeFi 与 NFT 资产。',u:'https://coin98.com',tag:'东南亚·多链',ic:'💰'},
{c:'crypto',t:'钱包',n:'Exodus',d:'设计精美的多链桌面与移动钱包，内置交易所与质押功能。',u:'https://www.exodus.com',tag:'设计·内置交易所',ic:'💎'},
{c:'crypto',t:'钱包',n:'Argent',d:'以太坊 StarkNet 智能合约钱包，社交恢复免助记词极简体验。',u:'https://www.argent.xyz',tag:'社交恢复·StarkNet',ic:'🦄'},

{c:'crypto',t:'DeFi',n:'Aave',d:'领先的去中心化借贷协议，支持多链存借数字资产。',u:'https://aave.com',tag:'借贷·多链',ic:'👻'},
{c:'crypto',t:'DeFi',n:'Lido',d:'最大的流动性质押协议，占据 ETH 质押量的主导份额。',u:'https://lido.fi',tag:'LSD·质押',ic:'💧'},
{c:'crypto',t:'DeFi',n:'MakerDAO',d:'去中心化稳定币 DAI 发行协议，DeFi 领域基石级应用。',u:'https://makerdao.com',tag:'稳定币·DAI',ic:'⚙️'},
{c:'crypto',t:'DeFi',n:'Curve',d:'稳定币交易 DEX，以超低滑点与深度流动性池闻名。',u:'https://curve.fi',tag:'稳定币·低滑点',ic:'📉'},
{c:'crypto',t:'DeFi',n:'PancakeSwap',d:'BNB Chain 上最大的去中心化交易所，用户活跃度极高。',u:'https://pancakeswap.finance',tag:'BSC·DEX',ic:'🥞'},
{c:'crypto',t:'DeFi',n:'EigenLayer',d:'以太坊再质押协议，释放已质押资产的额外收益潜力。',u:'https://www.eigenlayer.xyz',tag:'再质押·AVS',ic:'🔄'},
{c:'crypto',t:'DeFi',n:'Pendle',d:'收益代币化协议，将未来收益分拆为可灵活交易的数字资产。',u:'https://www.pendle.finance',tag:'收益·代币化',ic:'⏳'},
{c:'crypto',t:'DeFi',n:'1inch',d:'DEX 聚合器龙头，自动寻找最优兑换路径降低滑点成本。',u:'https://1inch.io',tag:'聚合·路由',ic:'🐉'},
{c:'crypto',t:'DeFi',n:'SushiSwap',d:'多链 DEX 与 DeFi 工具集，提供跨链兑换与借贷一体化服务。',u:'https://www.sushi.com',tag:'跨链·DEX',ic:'🍣'},
{c:'crypto',t:'DeFi',n:'Ether.fi',d:'去中心化流动性质押协议，非托管方式安全参与 ETH 质押。',u:'https://www.ether.fi',tag:'LSD·非托管',ic:'🌊'},
{c:'crypto',t:'DeFi',n:'Compound',d:'去中心化货币市场协议，存币生息与抵押借贷的去中心化实现。',u:'https://compound.finance',tag:'货币市场·生息',ic:'🏦'},
{c:'crypto',t:'DeFi',n:'Balancer',d:'可自定义权重的多资产流动性池协议，自动化投资组合再平衡。',u:'https://balancer.fi',tag:'多资产·权重',ic:'⚖️'},
{c:'crypto',t:'DeFi',n:'GMX',d:'Arbitrum 上最大的去中心化永续合约交易所，零滑点交易。',u:'https://gmx.io',tag:'永续·零滑点',ic:'📈'},
{c:'crypto',t:'DeFi',n:'dYdX',d:'专业级去中心化衍生品交易所，链下订单簿链上结算。',u:'https://dydx.trade',tag:'衍生品·订单簿',ic:'🔄'},
{c:'crypto',t:'DeFi',n:'Synthetix',d:'合成资产协议，链上发行交易追踪法币商品与加密货币的资产。',u:'https://www.synthetix.io',tag:'合成·资产',ic:'🧪'},

{c:'crypto',t:'稳定币',n:'Tether',d:'发行 USDT 的公司，全球流通量最大的稳定币发行商。',u:'https://tether.to',tag:'USDT·FirstMover',ic:'💵'},
{c:'crypto',t:'稳定币',n:'Circle',d:'USDC 发行商，美受监管的合规稳定币，储备透明可审计。',u:'https://www.circle.com',tag:'USDC·合规',ic:'⭕'},
{c:'crypto',t:'稳定币',n:'Ethena',d:'合成美元协议 USDe，通过创新的 Delta 中性策略维持锚定。',u:'https://www.ethena.fi',tag:'合成美元·Delta',ic:'🛡️'},
{c:'crypto',t:'稳定币',n:'Frax',d:'部分抵押算法稳定币协议，创新的 AMO 策略实现高效稳定。',u:'https://frax.finance',tag:'算法·AMO',ic:'🏛️'},

{c:'crypto',t:'GameFi',n:'Axie Infinity',d:'区块链游戏开创者，边玩边赚（P2E）模式的领头羊。',u:'https://axieinfinity.com',tag:'P2E·开创者',ic:'🐉'},
{c:'crypto',t:'GameFi',n:'The Sandbox',d:'去中心化虚拟世界与元宇宙平台，用户共建数字乐园。',u:'https://www.sandbox.game',tag:'元宇宙·虚拟世界',ic:'🏖️'},
{c:'crypto',t:'GameFi',n:'Immutable',d:'NFT 与链游基础设施，Immutable X 与 zkEVM 专为游戏打造。',u:'https://www.immutable.com',tag:'基础设施·游戏链',ic:'🔗'},
{c:'crypto',t:'GameFi',n:'Gala Games',d:'去中心化区块链游戏平台，玩家拥有游戏资产的真正所有权。',u:'https://www.gala.com',tag:'去中心·所有权',ic:'🎮'},
{c:'crypto',t:'GameFi',n:'STEPN',d:'首创 Move-to-Earn 运动即赚钱模式，边跑步边赚取加密资产。',u:'https://www.stepn.com',tag:'M2E·运动',ic:'👟'},

{c:'crypto',t:'质押服务',n:'Rocket Pool',d:'去中心化 ETH 流动性质押协议，节点自运营降低准入门槛。',u:'https://rocketpool.net',tag:'LSD·自运营节点',ic:'🚀'},
{c:'crypto',t:'质押服务',n:'Stader Labs',d:'跨链流动性质押平台，多链部署降低用户参与门槛。',u:'https://www.staderlabs.com',tag:'多链·LSD',ic:'🏷️'},
{c:'crypto',t:'质押服务',n:'Ankr',d:'Web3 去中心化节点与质押基础设施，支持 30+ 链质押。',u:'https://www.ankr.com',tag:'节点·30+链',ic:'⚓'},
{c:'crypto',t:'质押服务',n:'Allnodes',d:'非托管质押与节点托管平台，一键运行验证节点赚取收益。',u:'https://www.allnodes.com',tag:'非托管·一键',ic:'🔒'},
{c:'crypto',t:'质押服务',n:'Stake.fish',d:'全球专业的 PoS 验证节点运营商，横跨 20+ 主流公链。',u:'https://stake.fish',tag:'验证节点·20+链',ic:'🐟'},

{c:'crypto',t:'DAO 工具',n:'Snapshot',d:'去中心化治理投票平台，Gasless 链下投票体验丝滑。',u:'https://snapshot.org',tag:'投票·Gasless',ic:'🗳️'},
{c:'crypto',t:'DAO 工具',n:'Aragon',d:'DAO 创建与管理框架，一键启动去中心化自治组织。',u:'https://aragon.org',tag:'DAO·一键创建',ic:'🏛️'},
{c:'crypto',t:'DAO 工具',n:'Tally',d:'DAO 治理与投票界面，追踪治理提案并参与链上决策。',u:'https://www.tally.xyz',tag:'治理·界面',ic:'📋'},
{c:'crypto',t:'DAO 工具',n:'Juicebox',d:'社区金库与筹款协议，DAO 持续获得项目收入的工具。',u:'https://juicebox.money',tag:'金库·筹款',ic:'💰'},

{c:'crypto',t:'加密社交',n:'Farcaster',d:'去中心化社交协议，Einstein 架构实现足够去中心化的社交网络。',u:'https://www.farcaster.xyz',tag:'社交·协议',ic:'📯'},
{c:'crypto',t:'加密社交',n:'Lens Protocol',d:'可组合的去中心化社交图谱，开发者自由构建社交应用。',u:'https://www.lens.xyz',tag:'社交图谱·可组合',ic:'🌿'},
{c:'crypto',t:'加密社交',n:'CyberConnect',d:'去中心化社交图谱协议，跨平台复用用户社交身份与数据。',u:'https://cyberconnect.me',tag:'社交图谱·身份',ic:'🔗'},
{c:'crypto',t:'加密社交',n:'DeSo',d:'专为社交应用打造的 L1 区块链，链上存储内容与社交数据。',u:'https://www.deso.com',tag:'社交L1·存储',ic:'💎'},
{c:'crypto',t:'加密社交',n:'Paragraph',d:'Web3 内容发布与 Newsletter 平台，作者与读者直接互联互通。',u:'https://paragraph.xyz',tag:'发布·Newsletter',ic:'📰'},

{c:'crypto',t:'加密媒体',n:'The Block',d:'加密货币与区块链行业领先的新闻与研究媒体。',u:'https://www.theblock.co',tag:'新闻·研究',ic:'📰'},
{c:'crypto',t:'加密媒体',n:'Decrypt',d:'通俗易懂的 Web3 与加密货币新闻报道平台，新手友好。',u:'https://decrypt.co',tag:'新闻·入门',ic:'🔓'},
{c:'crypto',t:'加密媒体',n:'CoinDesk',d:'加密资产新闻与事件数据标杆，行业最具影响力的媒体之一。',u:'https://www.coindesk.com',tag:'标杆·影响力',ic:'📰'},
{c:'crypto',t:'加密媒体',n:'Blockworks',d:'数字资产领域的媒体与研究平台，提供专业级分析与播客。',u:'https://blockworks.co',tag:'分析·播客',ic:'🎙️'},
{c:'crypto',t:'加密媒体',n:'Bankless',d:'去中心化金融倡导者媒体，教育大众走向无需银行的未来。',u:'https://www.bankless.com',tag:'DeFi·教育',ic:'🏴'},

{c:'crypto',t:'加密支付',n:'BitPay',d:'老牌全球加密支付处理商，支持多币种支付与发票管理。',u:'https://bitpay.com',tag:'支付·老牌',ic:'💳'},
{c:'crypto',t:'加密支付',n:'Ramp Network',d:'法币到加密货币的入金通道，合规覆盖 150+ 国家和地区。',u:'https://ramp.network',tag:'法币入金·合规',ic:'🏦'},
{c:'crypto',t:'加密支付',n:'MoonPay',d:'全球领先的加密货币基础设施支付平台，服务超 500 万用户。',u:'https://www.moonpay.com',tag:'支付·基础设施',ic:'🌙'},

{c:'crypto',t:'加密基金',n:'a16z Crypto',d:'Andreessen Horowitz 加密风投基金，Web3 领域最大投资者之一。',u:'https://a16zcrypto.com',tag:'风投·Web3',ic:'💰'},
{c:'crypto',t:'加密基金',n:'Paradigm',d:'顶级加密原生风投，投资 Coinbase 与 Uniswap 等标杆项目。',u:'https://www.paradigm.xyz',tag:'风投·原生',ic:'🔮'},
{c:'crypto',t:'加密基金',n:'Pantera Capital',d:'美国第一家加密资产投资公司，专注区块链全阶段投资。',u:'https://panteracapital.com',tag:'先驱·全阶段',ic:'🐆'},
{c:'crypto',t:'加密基金',n:'Multicoin Capital',d:'以论文驱动著称的加密对冲基金，深度研究链上经济模型。',u:'https://multicoin.capital',tag:'对冲·研究',ic:'📚'},

{c:'crypto',t:'加密税务',n:'Koinly',d:'加密资产税务计算与申报平台，支持多国税法与交易所导入。',u:'https://koinly.io',tag:'税务·多国',ic:'🧾'},
{c:'crypto',t:'加密税务',n:'CoinTracker',d:'加密资产投资组合追踪与税务申报平台，覆盖万亿美元资产。',u:'https://www.cointracker.io',tag:'投资·申报',ic:'📊'},
{c:'crypto',t:'加密税务',n:'TokenTax',d:'专业加密税务软件，自动计算资本利得并生成申报表格。',u:'https://tokentax.co',tag:'自动·申报',ic:'💰'},
{c:'crypto',t:'加密税务',n:'ZenLedger',d:'加密税务计算与投资组合管理一体化，支持 DeFi 和 NFT 报税。',u:'https://www.zenledger.io',tag:'DeFi·NFT报税',ic:'🧘'},

{c:'crypto',t:'NFT 工具',n:'Gem.xyz',d:'NFT 聚合交易工具，批量扫地板价高效收集 NFT 资产。',u:'https://www.gem.xyz',tag:'聚合·批量',ic:'💎'},
{c:'crypto',t:'NFT 工具',n:'Sudoswap',d:'去中心化 NFT 自动化做市协议，即时创建与交易 NFT 池。',u:'https://sudoswap.xyz',tag:'AMM·NFT',ic:'🔄'},
{c:'crypto',t:'NFT 工具',n:'Reservoir',d:'NFT 开发者基础设施，统一 API 聚合所有市场的 NFT 数据。',u:'https://reservoir.tools',tag:'API·聚合',ic:'🔧'},

{c:'silicon',t:'芯片算力',n:'NVIDIA',d:'GPU 领域全球领导者，AI 算力基础设施的核心供应商。',u:'https://www.nvidia.com',tag:'GPU·加速计算',ic:'🟢'},
{c:'silicon',t:'芯片算力',n:'AMD',d:'高性能计算与 GPU 提供商，数据中心 AI 芯片的重要玩家。',u:'https://www.amd.com',tag:'GPU·CPU',ic:'🔴'},
{c:'silicon',t:'芯片算力',n:'Intel',d:'全球最大半导体公司之一，发力 AI PC 与数据中心芯片赛道。',u:'https://www.intel.com',tag:'CPU·代工',ic:'🔵'},
{c:'silicon',t:'芯片算力',n:'台积电 TSMC',d:'全球最大半导体代工企业，AI 芯片制造的核心枢纽。',u:'https://www.tsmc.com',tag:'代工·先进制程',ic:'🏭'},
{c:'silicon',t:'芯片算力',n:'ARM',d:'全球领先的芯片 IP 供应商，移动计算与 IoT 生态的基石。',u:'https://www.arm.com',tag:'IP·低功耗',ic:'📱'},
{c:'silicon',t:'芯片算力',n:'寒武纪',d:'中国 AI 芯片第一股，思元系列智能加速卡业界遥遥领先。',u:'https://www.cambricon.com',tag:'国产·AI加速',ic:'🧊'},
{c:'silicon',t:'芯片算力',n:'海光信息',d:'国产 x86 兼容 CPU 龙头，数据中心与服务器芯片性能强劲。',u:'https://www.hygon.cn',tag:'x86·国产',ic:'💠'},
{c:'silicon',t:'芯片算力',n:'摩尔线程',d:'国产全功能 GPU 厂商，发力 AI 训练与推理芯片市场。',u:'https://www.mthreads.com',tag:'国产GPU·训练',ic:'🧵'},
{c:'silicon',t:'芯片算力',n:'地平线',d:'边缘 AI 芯片与自动驾驶计算方案的全球领导者。',u:'https://www.horizon.auto',tag:'边缘·自动驾驶',ic:'🚘'},
{c:'silicon',t:'芯片算力',n:'Cerebras',d:'晶圆级 AI 芯片 WSE-3，单芯片集成 4 万亿晶体管。',u:'https://www.cerebras.net',tag:'晶圆级·超大',ic:'🧇'},
{c:'silicon',t:'芯片算力',n:'Graphcore',d:'英国 AI 芯片独角兽，IPU 架构专为机器学习智能设计。',u:'https://www.graphcore.ai',tag:'IPU·英国',ic:'🇬🇧'},
{c:'silicon',t:'芯片算力',n:'SambaNova',d:'企业级 AI 芯片与完整系统，创新的可重构数据流架构。',u:'https://sambanova.ai',tag:'数据流·企业',ic:'🔥'},
{c:'silicon',t:'芯片算力',n:'华为海思',d:'中国头部芯片设计公司，麒麟与昇腾系列领跑 AI 推理。',u:'https://www.hisilicon.com',tag:'国产·昇腾',ic:'🇨🇳'},
{c:'silicon',t:'芯片算力',n:'壁仞科技',d:'国产通用 GPU 创企，BR100 单芯片算力看齐国际旗舰水平。',u:'https://www.birentech.com',tag:'国产GPU·通用',ic:'💎'},
{c:'silicon',t:'芯片算力',n:'燧原科技',d:'国产云端 AI 训练与推理芯片厂商，产品已规模商用。',u:'https://www.enflame-tech.com',tag:'国产·云端',ic:'🔥'},
{c:'silicon',t:'芯片算力',n:'Imagination',d:'英国 GPU IP 头部公司，PowerVR 架构授权苹果等大厂使用。',u:'https://www.imaginationtech.com',tag:'GPU IP·英国',ic:'🇬🇧'},
{c:'silicon',t:'芯片算力',n:'昆仑芯',d:'百度旗下 AI 芯片公司，昆仑系列芯片大规模部署百度云。',u:'https://www.kunlunxin.com',tag:'百度·国产',ic:'⛰️'},

{c:'silicon',t:'神经元芯片',n:'Neuralink',d:'马斯克创办的脑机接口公司，探索人脑与计算机的直接交互。',u:'https://neuralink.com',tag:'脑机接口·BCI',ic:'🧬'},
{c:'silicon',t:'神经元芯片',n:'Synchron',d:'血管内植入式脑机接口，微创方式实现神经信号的精准读取。',u:'https://synchron.com',tag:'微创·血管内',ic:'🩸'},
{c:'silicon',t:'神经元芯片',n:'Blackrock Neurotech',d:'植入式脑机接口先驱，Utah 阵列已稳定临床使用多年。',u:'https://blackrockneurotech.com',tag:'临床·Utah阵列',ic:'⚡'},

{c:'silicon',t:'硅光芯片',n:'Lightmatter',d:'光子计算芯片先锋，用光代替电子实现超低功耗 AI 推理。',u:'https://lightmatter.co',tag:'光子·低功耗',ic:'💡'},
{c:'silicon',t:'硅光芯片',n:'Ayar Labs',d:'光互连技术领导者，用光速连接芯片间的海量数据传输。',u:'https://ayarlabs.com',tag:'光互连·数据传输',ic:'🔗'},
{c:'silicon',t:'硅光芯片',n:'曦智科技',d:'中国光子计算芯片先锋，光计算与光互连双轮驱动创新。',u:'https://www.lightelligence.io',tag:'国产·光计算',ic:'☀️'},

{c:'silicon',t:'量子计算',n:'IBM Quantum',d:'IBM 量子计算平台，提供云端量子计算服务与开源 Qiskit SDK。',u:'https://www.ibm.com/quantum',tag:'量子·云服务',ic:'⚛️'},
{c:'silicon',t:'量子计算',n:'Google Quantum AI',d:'Google 量子计算研究团队，目标构建有实用价值的量子计算机。',u:'https://quantumai.google',tag:'量子·纠错',ic:'🔬'},
{c:'silicon',t:'量子计算',n:'IonQ',d:'离子阱量子计算技术领导者，全球首家纯量子计算上市公司。',u:'https://ionq.com',tag:'离子阱·上市',ic:'💫'},
{c:'silicon',t:'量子计算',n:'Quantinuum',d:'Honeywell 量子计算部门与 CQC 合并，推出系统模型 H2。',u:'https://www.quantinuum.com',tag:'Honeywell·系统模型',ic:'🛰️'},
{c:'silicon',t:'量子计算',n:'本源量子',d:'中国量子计算第一梯队企业，已发布超导量子计算机。',u:'https://www.originqc.com.cn',tag:'国产·超导',ic:'🇨🇳'},

{c:'silicon',t:'算力云',n:'Lambda Labs',d:'专注 AI 训练的 GPU 云服务商，提供 A100/H100 实例。',u:'https://lambdalabs.com',tag:'GPU云·训练',ic:'☁️'},
{c:'silicon',t:'算力云',n:'CoreWeave',d:'NVIDIA 投资的 GPU 加速云服务商，专注大规模 AI 推理与训练。',u:'https://www.coreweave.com',tag:'GPU云·NVIDIA生态',ic:'⚡'},
{c:'silicon',t:'算力云',n:'AutoDL',d:'国内流行的 GPU 租用平台，性价比极高按量灵活计费。',u:'https://www.autodl.com',tag:'GPU租用·国产',ic:'🖥️'},
{c:'silicon',t:'算力云',n:'RunPod',d:'按需 GPU 云平台，Serverless 推理服务即时弹性伸缩。',u:'https://www.runpod.io',tag:'无服务器·弹性',ic:'🏃'},
{c:'silicon',t:'算力云',n:'Paperspace',d:'DigitalOcean 旗下的 GPU 云计算平台，深度集成 Jupyter Notebook。',u:'https://www.paperspace.com',tag:'Jupyter·GPU',ic:'📓'},
{c:'silicon',t:'算力云',n:'Vast.ai',d:'去中心化 GPU 租赁市场，全球算力资源共享低价灵活租用。',u:'https://vast.ai',tag:'去中心化·共享',ic:'🌐'},
{c:'silicon',t:'算力云',n:'JarvisLabs',d:'印度 GPU 云服务商，提供极具性价比的 A6000 和 RTX 系列 GPU。',u:'https://jarvislabs.ai',tag:'低价·RTX',ic:'🇮🇳'},

{c:'silicon',t:'芯片设计 EDA',n:'Cadence',d:'全球电子设计自动化工具巨头，AI 芯片设计流程核心工具。',u:'https://www.cadence.com',tag:'EDA·AI芯片',ic:'⚙️'},
{c:'silicon',t:'芯片设计 EDA',n:'Synopsys',d:'全球最大 EDA 与半导体 IP 供应商之一，AI 驱动 EDA 革新。',u:'https://www.synopsys.com',tag:'EDA·IP',ic:'🔧'},
{c:'silicon',t:'芯片设计 EDA',n:'Ansys',d:'多物理场仿真软件领导者，芯片电磁与散热仿真不可或缺。',u:'https://www.ansys.com',tag:'仿真·电磁',ic:'⚡'},
{c:'silicon',t:'芯片设计 EDA',n:'Keysight',d:'测试与测量巨头，芯片设计与验证全流程解决方案提供商。',u:'https://www.keysight.com',tag:'测试·验证',ic:'📡'},
{c:'silicon',t:'芯片设计 EDA',n:'Siemens EDA',d:'原 Mentor Graphics，西门子旗下 PCB 与 IC 设计全流程 EDA 方案。',u:'https://eda.sw.siemens.com',tag:'Siemens·PCB',ic:'🔌'},

{c:'silicon',t:'存储芯片',n:'Samsung Semiconductor',d:'全球最大存储芯片制造商，DRAM 与 NAND 闪存份额第一。',u:'https://semiconductor.samsung.com',tag:'DRAM·NAND',ic:'💾'},
{c:'silicon',t:'存储芯片',n:'SK Hynix',d:'韩国存储芯片巨头，HBM 高带宽内存领跑 AI 时代需求。',u:'https://www.skhynix.com',tag:'HBM·韩国',ic:'🇰🇷'},
{c:'silicon',t:'存储芯片',n:'Micron',d:'美国存储芯片巨头，全球第三大 DRAM 与 NAND 供应商。',u:'https://www.micron.com',tag:'DRAM·美国',ic:'💿'},
{c:'silicon',t:'存储芯片',n:'Western Digital',d:'全球领先的数据存储解决方案商，HDD 与 SSD 产品线全面。',u:'https://www.westerndigital.com',tag:'HDD·SSD',ic:'🖴'},
{c:'silicon',t:'存储芯片',n:'长江存储 YMTC',d:'中国 3D NAND 闪存制造商，Xtacking 架构创新领先。',u:'https://www.ymtc.com',tag:'NAND·国产',ic:'🇨🇳'},

{c:'silicon',t:'半导体设备',n:'ASML',d:'荷兰光刻机巨头，独家供应 EUV 极紫外光刻机给先进制程。',u:'https://www.asml.com',tag:'光刻机·EUV',ic:'🇳🇱'},
{c:'silicon',t:'半导体设备',n:'Applied Materials',d:'全球最大半导体设备制造商，覆盖沉积刻蚀注入全流程。',u:'https://www.appliedmaterials.com',tag:'设备·全流程',ic:'🏭'},
{c:'silicon',t:'半导体设备',n:'Lam Research',d:'刻蚀与沉积设备领导者，3D NAND 与先进逻辑制程核心供应商。',u:'https://www.lamresearch.com',tag:'刻蚀·沉积',ic:'⚡'},
{c:'silicon',t:'半导体设备',n:'Tokyo Electron',d:'日本半导体设备巨头，涂胶显影与刻蚀设备市占率全球领先。',u:'https://www.tel.com',tag:'涂胶显影·日本',ic:'🇯🇵'},
{c:'silicon',t:'半导体设备',n:'中微半导体 AMEC',d:'中国刻蚀机与 MOCVD 龙头，等离子体刻蚀机进入 5nm 产线。',u:'https://www.amec-inc.com',tag:'刻蚀·国产',ic:'🇨🇳'},

{c:'silicon',t:'RISC-V 生态',n:'SiFive',d:'RISC-V 处理器 IP 领先供应商，提供从 MCU 到高性能 CPU 方案。',u:'https://www.sifive.com',tag:'RISC-V·IP',ic:'🔮'},
{c:'silicon',t:'RISC-V 生态',n:'RISC-V International',d:'RISC-V 指令集架构基金会，管理开放 ISA 标准与生态发展。',u:'https://riscv.org',tag:'ISA·标准',ic:'🏛️'},
{c:'silicon',t:'RISC-V 生态',n:'赛昉科技 StarFive',d:'中国 RISC-V 处理器核心供应商，发力数据中心与 AI 芯片。',u:'https://www.starfivetech.com',tag:'RISC-V·国产',ic:'⭐'},
{c:'silicon',t:'RISC-V 生态',n:'芯来科技 Nuclei',d:'中国 RISC-V IP 供应商，覆盖 MCU 到应用处理器全产品线。',u:'https://www.nucleisys.com',tag:'RISC-V·IP国产',ic:'🧬'},
{c:'silicon',t:'RISC-V 生态',n:'Esperanto',d:'RISC-V 架构 AI 加速芯片公司，千核低功耗 AI 推理芯片。',u:'https://www.esperanto.ai',tag:'AI加速·千核',ic:'🧠'},

{c:'tools',t:'开发者工具',n:'GitHub',d:'全球最大的代码托管与协作平台，开源社区的精神中心。',u:'https://github.com',tag:'代码·协作',ic:'🐙'},
{c:'tools',t:'开发者工具',n:'Vercel',d:'前端部署平台领导者，支持 Next.js 等现代框架一键全球部署。',u:'https://vercel.com',tag:'部署·前端',ic:'▲'},
{c:'tools',t:'开发者工具',n:'Netlify',d:'流行的静态网站部署平台，提供 Serverless 边缘函数支持。',u:'https://www.netlify.com',tag:'静态部署·无服务器',ic:'🟣'},
{c:'tools',t:'开发者工具',n:'DeepL',d:'目前最精准的 AI 翻译工具，高质量支持 30+ 语言互译。',u:'https://www.deepl.com',tag:'翻译·精准',ic:'🌍'},
{c:'tools',t:'开发者工具',n:'Figma',d:'领先的 UI/UX 在线协作设计工具，产品设计行业事实标准。',u:'https://www.figma.com',tag:'设计·协作',ic:'🎯'},
{c:'tools',t:'开发者工具',n:'CodePen',d:'在线前端代码编辑器与分享社区，快速调试展示代码创意。',u:'https://codepen.io',tag:'前端·沙盒',ic:'✒️'},
{c:'tools',t:'开发者工具',n:'Kaggle',d:'全球最大的数据科学与机器学习竞赛平台，Google 子品牌。',u:'https://www.kaggle.com',tag:'数据科学·竞赛',ic:'🏆'},
{c:'tools',t:'开发者工具',n:'StackBlitz',d:'浏览器端全栈 Web 开发 IDE，基于 WebContainers 技术。',u:'https://stackblitz.com',tag:'在线IDE·WebContainer',ic:'⚡'},
{c:'tools',t:'开发者工具',n:'Excalidraw',d:'开源白板手绘风格绘图协作工具，支持端到端加密。',u:'https://excalidraw.com',tag:'手绘·白板',ic:'✏️'},
{c:'tools',t:'开发者工具',n:'Obsidian',d:'本地优先的知识管理工具，双向链接构建个人知识图谱。',u:'https://obsidian.md',tag:'知识管理·图谱',ic:'💎'},
{c:'tools',t:'开发者工具',n:'Raycast',d:'macOS 上的效率启动器，集成 AI 与海量插件扩展。',u:'https://www.raycast.com',tag:'效率·Mac',ic:'⚡'},
{c:'tools',t:'开发者工具',n:'Warp',d:'Rust 编写的下一代 AI 终端，智能补全与协作工作流。',u:'https://www.warp.dev',tag:'终端·Rust',ic:'⬛'},
{c:'tools',t:'开发者工具',n:'Linear',d:'现代产品管理型任务追踪工具，性能极致的设计驱动。',u:'https://linear.app',tag:'项目管理·性能',ic:'📐'},
{c:'tools',t:'开发者工具',n:'Postman',d:'全球最流行的 API 开发与测试平台，协作调试首选。',u:'https://www.postman.com',tag:'API·测试',ic:'📮'},
{c:'tools',t:'开发者工具',n:'Docker',d:'容器化平台标准，彻底改变了应用的打包、分发与部署。',u:'https://www.docker.com',tag:'容器·部署',ic:'🐳'},
{c:'tools',t:'开发者工具',n:'Supabase',d:'开源的 Firebase 替代方案，提供数据库认证与实时订阅。',u:'https://supabase.com',tag:'BaaS·开源',ic:'⚡'},
{c:'tools',t:'开发者工具',n:'Glitch',d:'社区驱动的在线协作编程平台，即时构建与分享 Web 应用。',u:'https://glitch.com',tag:'协作·社区',ic:'🐠'},

{c:'tools',t:'后端服务',n:'Cloudflare',d:'全球领先的 CDN 与边缘计算平台，Workers 无服务器函数。',u:'https://www.cloudflare.com',tag:'CDN·边缘',ic:'☁️'},
{c:'tools',t:'后端服务',n:'AWS',d:'全球最大云服务商，提供 200+ 全功能基础设施服务。',u:'https://aws.amazon.com',tag:'云计算·全栈',ic:'🟧'},
{c:'tools',t:'后端服务',n:'Firebase',d:'Google 的全托管后端平台，实时数据库与认证一键集成。',u:'https://firebase.google.com',tag:'Google·实时',ic:'🔥'},
{c:'tools',t:'后端服务',n:'PlanetScale',d:'基于 Vitess 的 MySQL 兼容 Serverless 数据库平台。',u:'https://planetscale.com',tag:'MySQL·Serverless',ic:'🪐'},
{c:'tools',t:'后端服务',n:'Neon',d:'Serverless PostgreSQL 数据库，分支式开发体验极佳。',u:'https://neon.tech',tag:'PostgreSQL·分支',ic:'💡'},
{c:'tools',t:'后端服务',n:'Railway',d:'极简部署平台，从代码到运行只需一个命令极速上线。',u:'https://railway.app',tag:'部署·极简',ic:'🚂'},
{c:'tools',t:'后端服务',n:'Fly.io',d:'全球分布式应用部署平台，将容器部署到用户附近的边缘。',u:'https://fly.io',tag:'边缘·容器',ic:'✈️'},
{c:'tools',t:'后端服务',n:'Render',d:'一体化云平台，部署 Web 服务、静态站点与数据库。',u:'https://render.com',tag:'全栈·部署',ic:'🎨'},

{c:'tools',t:'设计资源',n:'Dribbble',d:'全球设计师作品展示与灵感社区，发现顶级设计创意。',u:'https://dribbble.com',tag:'灵感·社区',ic:'🏀'},
{c:'tools',t:'设计资源',n:'Behance',d:'Adobe 旗下设计作品展示平台，全球创意人才聚集地。',u:'https://www.behance.net',tag:'Adobe·创意',ic:'🎨'},
{c:'tools',t:'设计资源',n:'Unsplash',d:'高质量免费图片素材库，摄影师社区驱动无版权使用。',u:'https://unsplash.com',tag:'图片·免费',ic:'📷'},
{c:'tools',t:'设计资源',n:'Pexels',d:'免费高质量图片与视频素材，个人和商业均可免版税使用。',u:'https://www.pexels.com',tag:'素材·免版税',ic:'🎬'},
{c:'tools',t:'设计资源',n:'Iconify',d:'统一的开源图标框架，聚合 200+ 图标集数十万 SVG。',u:'https://iconify.design',tag:'图标·SVG',ic:'🔣'},
{c:'tools',t:'设计资源',n:'LottieFiles',d:'轻量级动画资源平台，SVG/Lottie 动画创作分享与嵌入。',u:'https://lottiefiles.com',tag:'动画·Lottie',ic:'✨'},

{c:'tools',t:'监控可观测',n:'Datadog',d:'全栈可观测平台，基础设施到应用性能一体化监控。',u:'https://www.datadoghq.com',tag:'监控·APM',ic:'🐶'},
{c:'tools',t:'监控可观测',n:'Sentry',d:'实时错误追踪与性能监控，开发者排错的必备神器。',u:'https://sentry.io',tag:'错误追踪·性能',ic:'🛡️'},
{c:'tools',t:'监控可观测',n:'Grafana',d:'开源数据可视化与分析平台，构建专业级监控仪表盘。',u:'https://grafana.com',tag:'仪表盘·可视化',ic:'📊'},
{c:'tools',t:'监控可观测',n:'New Relic',d:'全栈可观测性平台，从应用性能到基础设施统一观测。',u:'https://newrelic.com',tag:'可观测·APM',ic:'📈'},
{c:'tools',t:'监控可观测',n:'LogRocket',d:'前端会话回放与性能监控，精准复现用户所见问题。',u:'https://logrocket.com',tag:'会话回放·前端',ic:'🚀'},

{c:'tools',t:'资讯社区',n:'Hacker News',d:'Y Combinator 运营的科技与创业社区，极客聚集地。',u:'https://news.ycombinator.com',tag:'科技·创业',ic:'🟠'},
{c:'tools',t:'资讯社区',n:'Product Hunt',d:'新产品发现与评选平台，每日发现最新最热的科技产品。',u:'https://www.producthunt.com',tag:'产品·发现',ic:'🐱'},
{c:'tools',t:'资讯社区',n:'Reddit r/MachineLearning',d:'Reddit 最大机器学习社区，交流前沿论文与技术讨论。',u:'https://www.reddit.com/r/MachineLearning',tag:'ML·论文',ic:'🤖'},
{c:'tools',t:'资讯社区',n:'Dev.to',d:'开发者技术博客与社区，分享编程经验与最佳实践。',u:'https://dev.to',tag:'博客·分享',ic:'👩‍💻'},
{c:'tools',t:'资讯社区',n:'Stack Overflow',d:'全球最大的编程问答社区，解决开发遇到的一切难题。',u:'https://stackoverflow.com',tag:'问答·编程',ic:'🟧'},

{c:'tools',t:'数据可视化',n:'D3.js',d:'数据驱动的文档操作库，灵活构建任意定制化图表。',u:'https://d3js.org',tag:'SVG·定制',ic:'📊'},
{c:'tools',t:'数据可视化',n:'Observable',d:'在线数据可视化与协作 Notebook 平台，D3 作者创立。',u:'https://observablehq.com',tag:'Notebook·协作',ic:'📓'},
{c:'tools',t:'数据可视化',n:'ECharts',d:'百度开源的可视化图表库，丰富的交互式图表开箱即用。',u:'https://echarts.apache.org',tag:'国产·交互',ic:'📈'},
{c:'tools',t:'数据可视化',n:'Plotly',d:'交互式科学图表库，支持 Python、R、JS 等多语言界面。',u:'https://plotly.com',tag:'科学·多语言',ic:'📉'},
{c:'tools',t:'数据可视化',n:'Chart.js',d:'简洁优雅的开源 HTML5 图表库，8 种基础图表易上手。',u:'https://www.chartjs.org',tag:'HTML5·简洁',ic:'🎯'},

{c:'tools',t:'域名托管',n:'Namecheap',d:'高性价比域名注册商，提供域名、主机与安全证书服务。',u:'https://www.namecheap.com',tag:'域名·性价比',ic:'🔖'},
{c:'tools',t:'域名托管',n:'Cloudflare Domains',d:'Cloudflare 域名注册，按成本价出售零加价保障隐私。',u:'https://www.cloudflare.com/products/registrar',tag:'成本价·隐私',ic:'☁️'},
{c:'tools',t:'域名托管',n:'GitHub Pages',d:'从 GitHub 仓库直接托管的免费静态网站服务。',u:'https://pages.github.com',tag:'免费·静态',ic:'🐙'},
{c:'tools',t:'域名托管',n:'Vercel Domains',d:'Vercel 平台内置域名管理，SSL 自动续签一键部署。',u:'https://vercel.com/docs/domains',tag:'SSL·自动',ic:'▲'},
{c:'tools',t:'域名托管',n:'Porkbun',d:'趣味域名注册商，价格透明无隐藏费用，免费 WHOIS 隐私。',u:'https://porkbun.com',tag:'透明·免费隐私',ic:'🐷'},

{c:'tools',t:'低代码/无代码',n:'Zapier',d:'全球最大的工作流自动化平台，连接 7000+ 应用零代码集成。',u:'https://zapier.com',tag:'自动化·集成',ic:'⚡'},
{c:'tools',t:'低代码/无代码',n:'Make',d:'可视化自动化平台，灵活构建复杂多步骤集成工作流。',u:'https://www.make.com',tag:'可视化·工作流',ic:'🔧'},
{c:'tools',t:'低代码/无代码',n:'Airtable',d:'电子表格与数据库的完美结合，低代码构建业务应用。',u:'https://airtable.com',tag:'表格·数据库',ic:'🗃️'},
{c:'tools',t:'低代码/无代码',n:'Bubble',d:'功能强大的无代码 Web 应用构建平台，可视化编程。',u:'https://bubble.io',tag:'Web·可视化',ic:'🫧'},
{c:'tools',t:'低代码/无代码',n:'Retool',d:'企业级内部工具快速构建平台，拖拽组件直连数据库。',u:'https://retool.com',tag:'内部工具·企业',ic:'🛠️'},

{c:'learn',t:'论文研究',n:'arXiv',d:'康奈尔大学运营的预印本论文平台，AI 前沿研究首选。',u:'https://arxiv.org',tag:'预印本·学术',ic:'📄'},
{c:'learn',t:'论文研究',n:'Papers With Code',d:'将论文与代码一一对应的平台，追踪 AI 技术最新进展。',u:'https://paperswithcode.com',tag:'论文·代码',ic:'📝'},
{c:'learn',t:'论文研究',n:'Semantic Scholar',d:'AI 驱动的学术文献搜索引擎，理解论文间引用与语义。',u:'https://www.semanticscholar.org',tag:'语义·学术搜索',ic:'🔬'},
{c:'learn',t:'论文研究',n:'Connected Papers',d:'以图谱形式可视化论文引用关系，轻松探索学术脉络。',u:'https://www.connectedpapers.com',tag:'引用图谱·可视化',ic:'🕸️'},
{c:'learn',t:'论文研究',n:'ResearchGate',d:'全球学术社交网络，研究者分享论文与同行在线交流。',u:'https://www.researchgate.net',tag:'社交·学术',ic:'🌍'},

{c:'learn',t:'在线课程',n:'Coursera',d:'全球顶级大学与企业的在线课程平台，提供专业证书与学位。',u:'https://www.coursera.org',tag:'课程·认证',ic:'🎓'},
{c:'learn',t:'在线课程',n:'edX',d:'哈佛与 MIT 创立的非营利慕课平台，海量免费大学课程。',u:'https://www.edx.org',tag:'慕课·名校',ic:'🏛️'},
{c:'learn',t:'在线课程',n:'Udacity',d:'聚焦前沿技术的纳米学位平台，AI 与数据科学精品课程。',u:'https://www.udacity.com',tag:'纳米学位·技术',ic:'🎯'},
{c:'learn',t:'在线课程',n:'Fast.ai',d:'免费的深度学习实战课程，以应用为导向的教学理念。',u:'https://www.fast.ai',tag:'免费·深度学习',ic:'⚡'},
{c:'learn',t:'在线课程',n:'DeepLearning.AI',d:'吴恩达创立的 AI 教育公司，体系化的深度学习专项课程。',u:'https://www.deeplearning.ai',tag:'吴恩达·专项',ic:'🧠'},

{c:'learn',t:'练习平台',n:'LeetCode',d:'全球最流行的算法与编程面试练习平台，大厂求职必备。',u:'https://leetcode.com',tag:'算法·面试',ic:'💻'},
{c:'learn',t:'练习平台',n:'Codecademy',d:'交互式编程学习平台，在浏览器中边学边写代码练习。',u:'https://www.codecademy.com',tag:'交互·入门',ic:'🎓'},
{c:'learn',t:'练习平台',n:'HackerRank',d:'编程练习与招聘平台，企业技术面试题库与技能认证。',u:'https://www.hackerrank.com',tag:'面试·认证',ic:'🟢'},
{c:'learn',t:'练习平台',n:'Codewars',d:'社区驱动的编程挑战平台，以段位系统激励持续编码训练。',u:'https://www.codewars.com',tag:'挑战·段位',ic:'⚔️'},
{c:'learn',t:'练习平台',n:'Exercism',d:'免费开源编程练习平台，由人类导师免费审阅你的代码。',u:'https://exercism.org',tag:'开源·导师审阅',ic:'🏋️'},

{c:'learn',t:'开放资源',n:'MIT OpenCourseWare',d:'MIT 所有课程资料的免费开放计划，知识无界共享。',u:'https://ocw.mit.edu',tag:'MIT·免费课程',ic:'🏛️'},
{c:'learn',t:'开放资源',n:'Stanford Online',d:'斯坦福大学在线课程平台，AI 与 CS 课程世界顶级。',u:'https://online.stanford.edu',tag:'斯坦福·CS',ic:'🌲'},
{c:'learn',t:'开放资源',n:'Khan Academy',d:'全球最大免费在线教育平台，科学数学到编程全覆盖。',u:'https://www.khanacademy.org',tag:'免费·K12+',ic:'🦸'},
{c:'learn',t:'开放资源',n:'OpenStax',d:'Rice 大学运营的免费开放教科书平台，高质量大学教材。',u:'https://openstax.org',tag:'教科书·免费',ic:'📚'},
{c:'learn',t:'开放资源',n:'3Blue1Brown',d:'用精美动画直观讲解数学与 AI 核心概念的 YouTube 频道。',u:'https://www.3blue1brown.com',tag:'数学·可视化',ic:'🧮'},

{c:'learn',t:'提示工程',n:'Learn Prompting',d:'免费的提示工程入门教材，系统学习如何高效驾驭 AI。',u:'https://learnprompting.org',tag:'免费·入门',ic:'📖'},
{c:'learn',t:'提示工程',n:'Prompting Guide',d:'DAIR.AI 维护的提示工程综合指南与研究论文整理。',u:'https://www.promptingguide.ai',tag:'指南·研究',ic:'🧭'},
{c:'learn',t:'提示工程',n:'Anthropic Prompt Library',d:'Anthropic 官方提示词库，精选各行各业高效 Prompt 模板。',u:'https://docs.anthropic.com/prompt-library',tag:'Anthropic·模板',ic:'📚'},
{c:'learn',t:'提示工程',n:'OpenAI Cookbook',d:'OpenAI API 官方代码示例库，覆盖常见场景最佳实践。',u:'https://cookbook.openai.com',tag:'OpenAI·代码示例',ic:'👨‍🍳'},
{c:'learn',t:'提示工程',n:'FlowGPT',d:'全球最大的 AI Prompt 社区，数百万用户分享创作 Prompt。',u:'https://flowgpt.com',tag:'社区·分享',ic:'🌟'},

{c:'learn',t:'AI资讯',n:'MIT Technology Review',d:'MIT 旗下权威科技媒体，深度报道 AI 与前沿科技动态。',u:'https://www.technologyreview.com',tag:'深度·MIT',ic:'🏛️'},
{c:'learn',t:'AI资讯',n:'The Verge AI',d:'The Verge AI 频道，用通俗语言解读最新 AI 技术趋势。',u:'https://www.theverge.com/ai-artificial-intelligence',tag:'通俗·趋势',ic:'🔺'},
{c:'learn',t:'AI资讯',n:'VentureBeat AI',d:'聚焦 AI 产业与创业的科技媒体，深度技术商业报道。',u:'https://venturebeat.com/category/ai',tag:'产业·创业',ic:'💼'},
{c:'learn',t:'AI资讯',n:'TechCrunch AI',d:'TechCrunch AI 频道，追踪全球 AI 创投与企业动态。',u:'https://techcrunch.com/category/artificial-intelligence',tag:'创投·企业',ic:'📰'},
{c:'learn',t:'AI资讯',n:'Analytics India Magazine',d:'印度最大的 AI 数据科学媒体，覆盖亚洲 AI 行业趋势。',u:'https://analyticsindiamag.com',tag:'亚洲·数据科学',ic:'🇮🇳'},

{c:'learn',t:'AI实验室',n:'Google DeepMind',d:'全球顶尖 AI 研究实验室，AlphaGo 与 AlphaFold 缔造者。',u:'https://deepmind.google',tag:'DeepMind·顶尖',ic:'🧠'},
{c:'learn',t:'AI实验室',n:'OpenAI Research',d:'OpenAI 研究主页，探索 AGI 前沿发布 GPT 系列技术。',u:'https://openai.com/research',tag:'AGI·GPT',ic:'🏢'},
{c:'learn',t:'AI实验室',n:'Meta AI Research',d:'Meta 人工智能研究中心，前沿研究覆盖基础模型与多模态。',u:'https://ai.meta.com/research',tag:'Meta·基础模型',ic:'🅵'},
{c:'learn',t:'AI实验室',n:'Anthropic Research',d:'Anthropic 安全研究方向，专注于可控可信的 AI 系统。',u:'https://www.anthropic.com/research',tag:'安全·可控',ic:'🔒'},
{c:'learn',t:'AI实验室',n:'NVIDIA Research',d:'NVIDIA 研究院，推动 GPU 计算与生成式 AI 技术前沿。',u:'https://research.nvidia.com',tag:'GPU·生成式',ic:'🟢'},

{c:'learn',t:'开源数据集',n:'Common Crawl',d:'海量互联网爬虫数据的非营利开放数据集，训练大模型基石。',u:'https://commoncrawl.org',tag:'爬虫·大模型',ic:'🌐'},
{c:'learn',t:'开源数据集',n:'Hugging Face Datasets',d:'Hugging Face 开放数据集社区，数万个 NLP/CV/语音数据集。',u:'https://huggingface.co/datasets',tag:'HuggingFace·社区',ic:'🤗'},
{c:'learn',t:'开源数据集',n:'Google Dataset Search',d:'Google 数据集搜索引擎，跨领域搜索海量开放数据。',u:'https://datasetsearch.research.google.com',tag:'Google·搜索',ic:'🔍'},
{c:'learn',t:'开源数据集',n:'ImageNet',d:'计算机视觉领域的基准图像数据库，奠定深度学习革命。',u:'https://www.image-net.org',tag:'CV·基准',ic:'🖼️'},
{c:'learn',t:'开源数据集',n:'OpenStreetMap',d:'维基百科式开源世界地图，免费的地理空间数据宝库。',u:'https://www.openstreetmap.org',tag:'地图·开源',ic:'🗺️'},

{c:'learn',t:'AI社区',n:'Hugging Face Forums',d:'Hugging Face 官方论坛，AI 开发者交流技术讨论的首选。',u:'https://discuss.huggingface.co',tag:'论坛·技术',ic:'🤗'},
{c:'learn',t:'AI社区',n:'AI Alignment Forum',d:'AI 对齐与安全领域的专业讨论社区，深度技术对话。',u:'https://www.alignmentforum.org',tag:'对齐·安全',ic:'🛡️'},
{c:'learn',t:'AI社区',n:'EleutherAI Discord',d:'EleutherAI 开源 AI 社区，聚集志愿研究者推动民主化。',u:'https://www.eleuther.ai',tag:'开源·民主化',ic:'🔓'},
{c:'learn',t:'AI社区',n:'智源社区',d:'北京智源人工智能研究院社区，中国 AI 学术交流高地。',u:'https://hub.baai.ac.cn',tag:'智源·学术',ic:'🇨🇳'},
{c:'learn',t:'AI社区',n:'OpenAI Developer Forum',d:'OpenAI 官方开发者社区，交流 API 使用与最佳实践。',u:'https://community.openai.com',tag:'OpenAI·社区',ic:'💬'},

{c:'learn',t:'编程语言',n:'Rust',d:'系统编程语言，零开销抽象与内存安全，正在重塑底层生态。',u:'https://www.rust-lang.org',tag:'系统·安全',ic:'🦀'},
{c:'learn',t:'编程语言',n:'Python',d:'人工智能与数据科学第一语言，生态极度丰富易学易用。',u:'https://www.python.org',tag:'AI·数据科学',ic:'🐍'},
{c:'learn',t:'编程语言',n:'TypeScript',d:'JavaScript 的超集，类型系统赋予前端工程级开发体验。',u:'https://www.typescriptlang.org',tag:'类型·前端',ic:'🔷'},
{c:'learn',t:'编程语言',n:'Go',d:'Google 推出的高效并发语言，云原生基础设施开发标配。',u:'https://go.dev',tag:'并发·云原生',ic:'🐹'},
{c:'learn',t:'编程语言',n:'Swift',d:'Apple 生态的主力开发语言，iOS 与 AI 端侧推理首选。',u:'https://www.swift.org',tag:'Apple·端侧',ic:'🍎'},

{c:'learn',t:'AI书籍',n:'Deep Learning Book',d:'Ian Goodfellow 等著的深度学习圣经，理论基础就此一本。',u:'https://www.deeplearningbook.org',tag:'深度学习·理论',ic:'📘'},
{c:'learn',t:'AI书籍',n:'d2l.ai',d:'李沐等人编写互动式深度学习教材，代码驱动的在线学习。',u:'https://d2l.ai',tag:'动手学·代码',ic:'📗'},
{c:'learn',t:'AI书籍',n:'Pattern Recognition and Machine Learning',d:'Christopher Bishop 的 PRML 经典，贝叶斯机器学习奠基。',u:'https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning',tag:'贝叶斯·经典',ic:'📙'},
{c:'learn',t:'AI书籍',n:'Reinforcement Learning: An Introduction',d:'Sutton & Barto 所著的强化学习入门圣经，领域奠基之作。',u:'https://incompleteideas.net/book/the-book.html',tag:'RL·经典',ic:'🎮'},
{c:'learn',t:'AI书籍',n:'The Elements of Statistical Learning',d:'Trevor Hastie 著统计学习理论经典，理解机器学习理论基础。',u:'https://hastie.su.domains/ElemStatLearn',tag:'统计·经典',ic:'📕'},

{c:'learn',t:'播客',n:'Lex Fridman Podcast',d:'MIT 研究员 Lex Fridman 深度对话 AI 科学家与哲学家的播客。',u:'https://lexfridman.com/podcast',tag:'深度·AI',ic:'🎙️'},
{c:'learn',t:'播客',n:'Machine Learning Street Talk',d:'横扫 AI 学术前沿的对话播客，深度剖析最新论文与方法。',u:'https://www.youtube.com/@MachineLearningStreetTalk',tag:'学术·深度',ic:'🎧'},
{c:'learn',t:'播客',n:'Practical AI',d:'Changelog 旗下 AI 实用播客，关注 AI 产品化与工程实践。',u:'https://changelog.com/practicalai',tag:'工程·实践',ic:'🛠️'},
{c:'learn',t:'播客',n:'Data Skeptic',d:'以怀疑论视角看数据科学前沿，通俗解读机器学习与统计。',u:'https://dataskeptic.com',tag:'科普·数据',ic:'🔍'},
{c:'learn',t:'播客',n:'This Week in Startups',d:'Jason Calacanis 主持，每周邀请顶尖科技创业者深度对话。',u:'https://www.youtube.com/@ThisWeekInStartups',tag:'创业·科技',ic:'🎯'},

{c:'ai',t:'AI提示词市场',n:'PromptBase',d:'AI 提示词交易市场，购买和出售高质量 Midjourney/DALL-E Prompt。',u:'https://promptbase.com',tag:'市场·交易',ic:'💼'},
{c:'ai',t:'AI提示词市场',n:'PromptHero',d:'最流行的 AI 图像 Prompt 搜索引擎，发现优秀提示词与作品。',u:'https://prompthero.com',tag:'搜索·图片Prompt',ic:'🏆'},
{c:'ai',t:'AI提示词市场',n:'Artbreeder',d:'AI 图像融合与基因编辑创作平台，通过混合图像创造新视觉。',u:'https://www.artbreeder.com',tag:'融合·GAN',ic:'🧬'},
{c:'ai',t:'AI提示词市场',n:'PromptFolder',d:'提示词管理工具，保存、组织与分享你的最佳 AI Prompt。',u:'https://promptfolder.com',tag:'管理·分享',ic:'📁'},
{c:'ai',t:'AI提示词市场',n:'ChatGPT Prompt Plus',d:'浏览器扩展一键保存和复用最常用的 ChatGPT 提示词模板。',u:'https://www.aiprm.com',tag:'扩展·模板',ic:'🔖'},

{c:'tools',t:'安全审计',n:'CertiK',d:'全球领先的 Web3 智能合约安全审计公司，守护百亿美元资产。',u:'https://www.certik.com',tag:'审计·合约',ic:'🛡️'},
{c:'tools',t:'安全审计',n:'OpenZeppelin',d:'开源智能合约安全框架，提供审计服务和标准化合约库。',u:'https://www.openzeppelin.com',tag:'审计·标准库',ic:'🔐'},
{c:'tools',t:'安全审计',n:'Trail of Bits',d:'顶尖信息安全研究公司，专注区块链与应用安全深度审计。',u:'https://www.trailofbits.com',tag:'安全·研究',ic:'🔍'},
{c:'tools',t:'安全审计',n:'Quantstamp',d:'智能合约安全审计与区块链安全服务，保护去中心化应用。',u:'https://quantstamp.com',tag:'审计·dApp',ic:'⚡'},
{c:'tools',t:'安全审计',n:'慢雾科技 SlowMist',d:'中国领先区块链安全公司，发现并防护大量严重漏洞。',u:'https://www.slowmist.com',tag:'国产·安全',ic:'🇨🇳'},

{c:'tools',t:'桌面工具',n:'VS Code',d:'微软开源代码编辑器，最受开发者欢迎的轻量级 IDE 应用。',u:'https://code.visualstudio.com',tag:'编辑器·开源',ic:'🔵'},
{c:'tools',t:'桌面工具',n:'Sublime Text',d:'极速跨平台高级文本编辑器，启动快如闪电支持海量插件。',u:'https://www.sublimetext.com',tag:'高速·轻量',ic:'🟠'},
{c:'tools',t:'桌面工具',n:'iTerm2',d:'macOS 终极终端模拟器，分屏与快捷键大幅提升命令行效率。',u:'https://iterm2.com',tag:'终端·macOS',ic:'🖥️'},
{c:'tools',t:'桌面工具',n:'Alacritty',d:'GPU 加速跨平台终端模拟器，性能极致的 Rust 编写之美。',u:'https://alacritty.org',tag:'GPU·Rust',ic:'⚡'},
{c:'tools',t:'桌面工具',n:'Bruno',d:'开源离线 API 测试客户端，轻量替代 Postman 数据本地存储。',u:'https://www.usebruno.com',tag:'API·离线',ic:'🧪'},

{c:'tools',t:'API 网关',n:'Kong',d:'全球最流行的开源 API 网关，管理保护与监控微服务 API。',u:'https://konghq.com',tag:'网关·微服务',ic:'🦍'},
{c:'tools',t:'API 网关',n:'Apigee',d:'Google Cloud 旗下的企业级 API 管理平台，全生命周期 API 治理。',u:'https://cloud.google.com/apigee',tag:'Google·企业',ic:'🔗'},
{c:'tools',t:'API 网关',n:'Tyk',d:'开源 API 网关与管理平台，高性能轻量级部署灵活可扩展。',u:'https://tyk.io',tag:'开源·高性能',ic:'⚡'},
{c:'tools',t:'API 网关',n:'AWS API Gateway',d:'AWS 全托管 API 管理服务，与 Lambda 等无服务器服务深度集成。',u:'https://aws.amazon.com/api-gateway',tag:'AWS·Serverless',ic:'☁️'},
{c:'tools',t:'API 网关',n:'Zuplo',d:'API 网关即服务，内置速率限制与身份验证快速部署 API。',u:'https://zuplo.com',tag:'即服务·认证',ic:'🛡️'},

{c:'tools',t:'效率工具',n:'Alfred',d:'macOS 效率神器，应用程序启动器与自动化工作流引擎。',u:'https://www.alfredapp.com',tag:'Mac·自动化',ic:'🎩'},
{c:'tools',t:'效率工具',n:'Rectangle',d:'macOS 免费窗口管理工具，用快捷键快速分屏排列应用窗口。',u:'https://rectangleapp.com',tag:'分屏·免费',ic:'🪟'},
{c:'tools',t:'效率工具',n:'AltTab',d:'macOS 窗口切换增强器，Windows 风格 Alt+Tab 更高效切换。',u:'https://alt-tab-macos.netlify.app',tag:'切换·免费',ic:'🔄'},
{c:'tools',t:'效率工具',n:'1Password',d:'行业领先的密码管理与团队安全平台，自动填充与安全共享。',u:'https://1password.com',tag:'密码·安全',ic:'🔑'},
{c:'tools',t:'效率工具',n:'Bitwarden',d:'开源免费跨平台密码管理器，端到端加密自托管灵活部署。',u:'https://bitwarden.com',tag:'开源·自托管',ic:'🔓'},

{c:'learn',t:'编程语言',n:'Zig',d:'新兴系统编程语言，与 C 深度互操作挑战 C 语言生态主导地位。',u:'https://ziglang.org',tag:'系统·C互操作',ic:'⚡'},
{c:'learn',t:'编程语言',n:'Julia',d:'高性能科学计算语言，兼顾 Python 易用与 C 速度完美平衡。',u:'https://julialang.org',tag:'科学计算·高性能',ic:'🔮'},
{c:'learn',t:'编程语言',n:'Mojo',d:'为 AI 计算的 Python 超集语言，高达 Python 35000 倍提速潜力。',u:'https://www.modular.com/mojo',tag:'AI·超高性能',ic:'🔥'},

{c:'robot',t:'仿生机器人',n:'Festo Bionic',d:'德国 Festo 仿生学习网络，以变色龙袋鼠等仿生机器人启发行业。',u:'https://www.festo.com/bionic',tag:'仿生·学习',ic:'🦎'},
{c:'robot',t:'仿生机器人',n:'Soft Robotics',d:'软体机器人抓手公司，柔性夹持适应不规则物体实现自适应抓取。',u:'https://www.softroboticsinc.com',tag:'软体·夹持',ic:'🐙'},
{c:'robot',t:'仿生机器人',n:'Piaggio Fast Forward',d:'摩托巨头比亚乔旗下机器人公司，跟随式货运机器人 Gita。',u:'https://www.piaggiofastforward.com',tag:'跟随·货运',ic:'🤖'},
{c:'robot',t:'仿生机器人',n:'Open Bionics',d:'英国轻量仿生义肢公司，Hero Arm 是首获医疗认证的 3D 打印。',u:'https://openbionics.com',tag:'义肢·3D打印',ic:'🦾'},
{c:'robot',t:'仿生机器人',n:'RoboBees',d:'哈佛微机器人实验室研制的微型飞行机器人，仿蜜蜂群智能。',u:'https://wyss.harvard.edu/technology/robobees',tag:'微型·飞行',ic:'🐝'},

{c:'tools',t:'开发者工具',n:'Notion',d:'全能型笔记与知识管理工具，集成 AI 写作辅助强大功能。',u:'https://www.notion.so',tag:'笔记·AI',ic:'📝'},

];

var catMeta={
ai:{emoji:'🤖',name:'人工智能'},
robot:{emoji:'🦾',name:'机器人'},
models:{emoji:'🧩',name:'大模型'},
blockchain:{emoji:'⛓️',name:'区块链'},
crypto:{emoji:'💰',name:'数字币'},
silicon:{emoji:'💠',name:'芯片算力'},
tools:{emoji:'🛠️',name:'开发工具'},
learn:{emoji:'📚',name:'学习资源'}
};

var catOrder=['ai','robot','models','blockchain','crypto','silicon','tools','learn'];