var cards = [
  { c:'ai', t:'大语言模型', n:'ChatGPT', d:'OpenAI 推出的顶级对话式 AI，支持文本、图像、语音多模态交互。', u:'https://chat.openai.com', tag:'GPT·多模态', ic:'💬' },
  { c:'ai', t:'大语言模型', n:'Claude', d:'Anthropic 开发的安全可靠大模型，擅长长文本分析与深度推理。', u:'https://claude.ai', tag:'长文本·安全', ic:'🧠' },
  { c:'ai', t:'大语言模型', n:'Gemini', d:'Google DeepMind 打造的新一代多模态大模型，整合搜索与推理。', u:'https://gemini.google.com', tag:'Google·多模态', ic:'♊' },
  { c:'ai', t:'大语言模型', n:'DeepSeek', d:'深度求索推出的高性能开源大模型，编程与推理能力突出。', u:'https://chat.deepseek.com', tag:'开源·编程', ic:'🔮' },
  { c:'ai', t:'大语言模型', n:'Kimi', d:'月之暗面推出的超长上下文 AI 助手，支持 200 万字输入。', u:'https://kimi.moonshot.cn', tag:'长上下文·国产', ic:'🌙' },
  { c:'ai', t:'大语言模型', n:'通义千问', d:'阿里云自研大语言模型，提供对话、编程、翻译等多场景服务。', u:'https://tongyi.aliyun.com', tag:'阿里·国产', ic:'☁️' },
  { c:'ai', t:'大语言模型', n:'文心一言', d:'百度推出的知识增强大语言模型，深度整合百度搜索生态。', u:'https://yiyan.baidu.com', tag:'百度·知识增强', ic:'📘' },
  { c:'ai', t:'大语言模型', n:'豆包', d:'字节跳动旗下 AI 对话助手，集成抖音生态与多模态能力。', u:'https://www.doubao.com', tag:'字节·多模态', ic:'🫘' },
  { c:'ai', t:'大语言模型', n:'Grok', d:'xAI（马斯克旗下）推出的幽默风格 AI 助手，实时访问 X 平台数据。', u:'https://grok.com', tag:'xAI·实时', ic:'🚀' },
  { c:'ai', t:'大语言模型', n:'Perplexity', d:'AI 驱动的智能搜索引擎，结合大模型与实时网页检索。', u:'https://www.perplexity.ai', tag:'搜索·研究', ic:'🔎' },
  { c:'ai', t:'大语言模型', n:'智谱清言', d:'智谱 AI 推出的 GLM 系列大模型对话产品，支持多模态交互。', u:'https://chatglm.cn', tag:'GLM·国产', ic:'💎' },
  { c:'ai', t:'大语言模型', n:'讯飞星火', d:'科大讯飞自研大模型，深耕语音交互与教育办公场景。', u:'https://xinghuo.xfyun.cn', tag:'讯飞·语音', ic:'🔥' },
  { c:'ai', t:'大语言模型', n:'百川智能', d:'百川 AI 推出的 Baichuan 系列大模型平台，中文评测突出。', u:'https://www.baichuan-ai.com', tag:'百川·国产', ic:'🌊' },
  { c:'ai', t:'大语言模型', n:'腾讯混元', d:'腾讯自研大模型，深度嵌入微信、腾讯会议等产品矩阵。', u:'https://hunyuan.tencent.com', tag:'腾讯·生态', ic:'🐧' },
  { c:'ai', t:'大语言模型', n:'腾讯元宝', d:'腾讯 AI 助手应用，融合混元大模型与公众号内容生态。', u:'https://yuanbao.tencent.com', tag:'腾讯·助手', ic:'💰' },
  { c:'ai', t:'大语言模型', n:'海螺 AI', d:'Minimax 推出的 AI 对话产品，语音合成能力业界领先。', u:'https://hailuoai.com', tag:'Minimax·语音', ic:'🐚' },
  { c:'ai', t:'大语言模型', n:'阶跃星辰', d:'Step 系列大模型，数学推理与多模态能力突出。', u:'https://www.stepfun.com', tag:'Step·数学', ic:'⭐' },
  { c:'ai', t:'大语言模型', n:'Cohere', d:'企业级大语言模型平台，Command R 系列专注 RAG 与多语言。', u:'https://cohere.com', tag:'企业·RAG', ic:'🏢' },
  { c:'ai', t:'大语言模型', n:'Mistral Le Chat', d:'法国 Mistral AI 官方对话产品，支持多语言与联网搜索。', u:'https://chat.mistral.ai', tag:'欧洲·Mistral', ic:'🇫🇷' },
  { c:'ai', t:'大语言模型', n:'Character.ai', d:'AI 角色扮演与对话平台，创建和互动各类虚拟角色。', u:'https://character.ai', tag:'角色·互动', ic:'🎭' },
  { c:'ai', t:'大语言模型', n:'Poe', d:'Quora 旗下多模型聚合 AI 平台，一站体验数十种大语言模型。', u:'https://poe.com', tag:'聚合·Quora', ic:'📦' },
  { c:'ai', t:'大语言模型', n:'HuggingChat', d:'Hugging Face 开源 AI 对话，可自由切换多种开源模型。', u:'https://huggingface.co/chat', tag:'开源·自由', ic:'🤗' },
  { c:'ai', t:'大语言模型', n:'Anthropic Console', d:'Claude API 开发者控制台，构建和部署 AI 应用。', u:'https://console.anthropic.com', tag:'API·开发者', ic:'🏗️' },
  { c:'ai', t:'大语言模型', n:'Meta AI', d:'Meta 推出的免费 AI 助手，集成 Llama 系列模型能力。', u:'https://www.meta.ai', tag:'Meta·免费', ic:'🅼' },
  { c:'ai', t:'大语言模型', n:'Pi', d:'Inflection AI 打造的情感化 AI 对话助手，对话自然温暖。', u:'https://pi.ai', tag:'情感·Inflection', ic:'π' },
  { c:'ai', t:'大语言模型', n:'DeepSeek 平台', d:'DeepSeek API 开发平台，提供模型推理与微调服务。', u:'https://platform.deepseek.com', tag:'API·微调', ic:'🖥️' },

  { c:'ai', t:'AI搜索', n:'秘塔 AI 搜索', d:'中文 AI 搜索引擎，可深入学术与专业领域检索。', u:'https://metaso.cn', tag:'搜索·学术', ic:'🔍' },
  { c:'ai', t:'AI搜索', n:'天工 AI 搜索', d:'昆仑万维推出的 AI 搜索产品，支持多轮深度研究。', u:'https://www.tiangong.cn', tag:'搜索·深度', ic:'🌤️' },
  { c:'ai', t:'AI搜索', n:'Devv', d:'面向开发者的 AI 搜索引擎，精准检索编程与技术文档。', u:'https://devv.ai', tag:'编程·搜索', ic:'👾' },
  { c:'ai', t:'AI搜索', n:'You.com', d:'以隐私为核心的 AI 搜索引擎，支持多种 AI 模式切换。', u:'https://you.com', tag:'隐私·搜索', ic:'🔒' },
  { c:'ai', t:'AI搜索', n:'Phind', d:'专为开发者打造的 AI 答案引擎，结合实时搜索与代码生成。', u:'https://www.phind.com', tag:'代码·搜索', ic:'💡' },
  { c:'ai', t:'AI搜索', n:'博查 AI 搜索', d:'字节旗下 AI 搜索产品，聚合全网信息智能回答。', u:'https://www.bochaai.com', tag:'字节·搜索', ic:'🎯' },

  { c:'ai', t:'AI写作办公', n:'Gamma', d:'AI 驱动的演示文稿与文档生成工具，一键创建精美 PPT。', u:'https://gamma.app', tag:'PPT·AI', ic:'📊' },
  { c:'ai', t:'AI写作办公', n:'Jasper', d:'老牌 AI 营销写作助手，支持品牌化内容批量生成。', u:'https://www.jasper.ai', tag:'营销·写作', ic:'✍️' },
  { c:'ai', t:'AI写作办公', n:'Copy.ai', d:'AI 销售与营销写作平台，专注 GTM 工作流自动化。', u:'https://www.copy.ai', tag:'销售·自动化', ic:'📋' },
  { c:'ai', t:'AI写作办公', n:'Grammarly', d:'全球领先的 AI 写作辅助工具，语法检查与风格优化。', u:'https://www.grammarly.com', tag:'语法·英文', ic:'✅' },
  { c:'ai', t:'AI写作办公', n:'通义听悟', d:'阿里云 AI 音视频转写工具，支持实时翻译与摘要生成。', u:'https://tingwu.aliyun.com', tag:'转写·翻译', ic:'👂' },
  { c:'ai', t:'AI写作办公', n:'讯飞听见', d:'科大讯飞语音转文字平台，会议记录与访谈利器。', u:'https://www.iflyrec.com', tag:'语音转写·会议', ic:'🎙️' },
  { c:'ai', t:'AI写作办公', n:'Otter.ai', d:'AI 会议记录与转录工具，实时生成会议笔记与摘要。', u:'https://otter.ai', tag:'会议·转录', ic:'🦦' },
  { c:'ai', t:'AI写作办公', n:'Notion AI', d:'Notion 内置 AI 写作助手，笔记、文档与知识库一体化。', u:'https://www.notion.so/product/ai', tag:'笔记·知识库', ic:'📝' },
  { c:'ai', t:'AI写作办公', n:'WPS AI', d:'金山办公 WPS 内置 AI 助手，文档、表格、PPT 智能处理。', u:'https://ai.wps.cn', tag:'办公套件·国产', ic:'📑' },

  { c:'ai', t:'AI设计', n:'Canva', d:'全球最流行的在线设计平台，深度集成 AI 图像与排版功能。', u:'https://www.canva.com', tag:'设计·模板', ic:'🖌️' },
  { c:'ai', t:'AI设计', n:'Microsoft Designer', d:'微软 AI 设计工具，通过自然语言生成海报、社媒图像。', u:'https://designer.microsoft.com', tag:'微软·海报', ic:'🪟' },
  { c:'ai', t:'AI设计', n:'Galileo AI', d:'用自然语言描述即可生成 UI 界面设计稿的 AI 工具。', u:'https://www.usegalileo.ai', tag:'UI生成·设计稿', ic:'🎨' },
  { c:'ai', t:'AI设计', n:'Uizard', d:'AI 驱动的产品原型设计工具，草图一键转交互原型。', u:'https://uizard.io', tag:'原型·草图', ic:'📱' },
  { c:'ai', t:'AI设计', n:'即时 AI', d:'即时设计推出的 AI UI 生成工具，中文界面设计首选。', u:'https://js.design/ai', tag:'国产·UI', ic:'🇨🇳' },

  { c:'ai', t:'AI绘画', n:'Midjourney', d:'最受欢迎的 AI 图像生成工具，以艺术风格和质量著称。', u:'https://www.midjourney.com', tag:'艺术·高质量', ic:'🎨' },
  { c:'ai', t:'AI绘画', n:'Stable Diffusion', d:'Stability AI 的开源图像生成模型，可本地部署自由创作。', u:'https://stability.ai', tag:'开源·可部署', ic:'🖼️' },
  { c:'ai', t:'AI绘画', n:'DALL·E', d:'OpenAI 开发的图像生成模型，与 ChatGPT 深度整合。', u:'https://openai.com/dall-e-3', tag:'OpenAI·精准', ic:'✨' },
  { c:'ai', t:'AI绘画', n:'ComfyUI', d:'功能强大的 Stable Diffusion 节点式工作流界面，灵活高效。', u:'https://github.com/comfyanonymous/ComfyUI', tag:'工作流·开源', ic:'🔧' },
  { c:'ai', t:'AI绘画', n:'Leonardo AI', d:'游戏资产级 AI 图像生成平台，提供模型微调与画布编辑。', u:'https://leonardo.ai', tag:'游戏·微调', ic:'🎮' },
  { c:'ai', t:'AI绘画', n:'Firefly', d:'Adobe 推出的商用安全 AI 图像生成工具，深度集成 PS。', u:'https://firefly.adobe.com', tag:'Adobe·商用安全', ic:'🦋' },
  { c:'ai', t:'AI绘画', n:'通义万相', d:'阿里云推出的 AI 创意绘画平台，支持文生图与风格迁移。', u:'https://tongyi.aliyun.com/wanxiang', tag:'阿里·创意', ic:'🖼️' },
  { c:'ai', t:'AI绘画', n:'文心一格', d:'百度出品的 AI 艺术与创意辅助平台，中文理解优秀。', u:'https://yige.baidu.com', tag:'百度·中文', ic:'🖌️' },
  { c:'ai', t:'AI绘画', n:'SeaArt', d:'专注于动漫风格的 AI 绘画平台，模型与 LoRA 资源丰富。', u:'https://www.seaart.ai', tag:'动漫·LoRA', ic:'🌸' },

  { c:'ai', t:'AI视频', n:'Runway', d:'专业级 AI 视频生成与编辑平台，支持 Gen-3 等前沿模型。', u:'https://runwayml.com', tag:'视频生成·编辑', ic:'🎬' },
  { c:'ai', t:'AI视频', n:'Pika', d:'简单易用的 AI 视频生成工具，支持文本转视频及视频编辑。', u:'https://pika.art', tag:'文生视频·易用', ic:'🎥' },
  { c:'ai', t:'AI视频', n:'可灵 Kling', d:'快手推出的 AI 视频生成大模型，支持文生视频和图生视频。', u:'https://kling.kuaishou.com', tag:'快手·国产', ic:'🎞️' },
  { c:'ai', t:'AI视频', n:'Sora', d:'OpenAI 出品的革命性文生视频模型，物理世界模拟能力极强。', u:'https://openai.com/sora', tag:'OpenAI·物理模拟', ic:'🌌' },
  { c:'ai', t:'AI视频', n:'HeyGen', d:'AI 数字人视频生成平台，支持真人克隆与多语言口型同步。', u:'https://www.heygen.com', tag:'数字人·克隆', ic:'🤖' },
  { c:'ai', t:'AI视频', n:'Synthesia', d:'企业级 AI 虚拟主播视频生成，无需真人出镜制作专业视频。', u:'https://www.synthesia.io', tag:'虚拟人·企业', ic:'🎭' },
  { c:'ai', t:'AI视频', n:'Luma AI', d:'3D 与视频生成 AI 平台，Dream Machine 效果惊艳。', u:'https://lumalabs.ai', tag:'3D·DreamMachine', ic:'📸' },
  { c:'ai', t:'AI视频', n:'即梦', d:'剪映旗下 AI 视频生成工具，文生视频与图生视频一体化。', u:'https://jimeng.jianying.com', tag:'剪映·国产', ic:'💭' },
  { c:'ai', t:'AI视频', n:'Pixverse', d:'免费 AI 视频生成平台，支持文生视频与动漫风格。', u:'https://pixverse.ai', tag:'免费·动漫', ic:'✨' },
  { c:'ai', t:'AI视频', n:'Vidu', d:'生数科技推出的长时长 AI 视频生成模型，一致性表现优异。', u:'https://www.vidu.studio', tag:'长视频·U-Net', ic:'🎯' },
  { c:'ai', t:'AI视频', n:'剪映', d:'抖音官方视频剪辑工具，AI 字幕、调色与模板一键生成。', u:'https://www.capcut.cn', tag:'剪辑·AI', ic:'✂️' },
  { c:'ai', t:'AI视频', n:'Haiper AI', d:'前 DeepMind 团队创立的 AI 视频生成平台，生成质量优秀。', u:'https://haiper.ai', tag:'DeepMind系·生成', ic:'🎬' },
  { c:'ai', t:'AI视频', n:'Genmo', d:'AI 创意视频与动画生成工具，支持交互式视频创作。', u:'https://www.genmo.ai', tag:'创意·动画', ic:'✨' },

  { c:'ai', t:'AI音频', n:'Suno', d:'AI 音乐生成平台，输入歌词或描述即可创作完整歌曲。', u:'https://suno.ai', tag:'音乐创作·歌词', ic:'🎵' },
  { c:'ai', t:'AI音频', n:'Udio', d:'高质量 AI 音乐生成工具，由前 Google DeepMind 研究员打造。', u:'https://www.udio.com', tag:'音乐·高保真', ic:'🎹' },
  { c:'ai', t:'AI音频', n:'ElevenLabs', d:'目前最逼真的 AI 语音合成与克隆平台，支持多语言。', u:'https://elevenlabs.io', tag:'语音克隆·TTS', ic:'🗣️' },
  { c:'ai', t:'AI音频', n:'魔音工坊', d:'出门问问旗下的 AI 配音工具，提供数百种拟人化音色。', u:'https://www.moyin.com', tag:'配音·中文', ic:'🎤' },
  { c:'ai', t:'AI音频', n:'Murf AI', d:'专业 AI 配音平台，适用于播客、有声书与视频配音。', u:'https://murf.ai', tag:'配音·专业', ic:'🎧' },
  { c:'ai', t:'AI音频', n:'Play.ht', d:'超现实 AI 语音生成器，支持语音克隆与多语种 TTS。', u:'https://play.ht', tag:'TTS·多语种', ic:'🔊' },
  { c:'ai', t:'AI音频', n:'Speak', d:'AI 语言学习 App，通过语音交互练习英语与韩语口语。', u:'https://www.speak.com', tag:'语言学习·口语', ic:'🗣️' },

  { c:'ai', t:'AI编程', n:'GitHub Copilot', d:'GitHub 与 OpenAI 联合推出的 AI 编程助手，深度集成 IDE。', u:'https://github.com/features/copilot', tag:'代码补全·IDE', ic:'👨‍💻' },
  { c:'ai', t:'AI编程', n:'Cursor', d:'基于 VS Code 的 AI 原生代码编辑器，编程体验极致智能。', u:'https://cursor.sh', tag:'编辑器·智能', ic:'🖱️' },
  { c:'ai', t:'AI编程', n:'Windsurf', d:'Codeium 推出的 AI 原生 IDE，支持多文件智能编辑与重构。', u:'https://codeium.com/windsurf', tag:'IDE·多文件', ic:'🌊' },
  { c:'ai', t:'AI编程', n:'v0.dev', d:'Vercel 推出的 AI 前端界面生成工具，通过自然语言生成 UI。', u:'https://v0.dev', tag:'UI生成·Vercel', ic:'🖌️' },
  { c:'ai', t:'AI编程', n:'Bolt.new', d:'StackBlitz 推出的 AI 全栈应用生成器，直接在浏览器构建应用。', u:'https://bolt.new', tag:'全栈·浏览器', ic:'⚡' },
  { c:'ai', t:'AI编程', n:'通义灵码', d:'阿里云推出的免费 AI 编程助手，兼容主流 IDE。', u:'https://tongyi.aliyun.com/lingma', tag:'阿里·免费', ic:'🐴' },
  { c:'ai', t:'AI编程', n:'Replit', d:'在线代码编辑与托管平台，AI 加持的一键应用部署。', u:'https://replit.com', tag:'在线IDE·部署', ic:'🔄' },
  { c:'ai', t:'AI编程', n:'Sourcegraph Cody', d:'基于代码图的 AI 编程助手，理解全仓库上下文。', u:'https://sourcegraph.com', tag:'代码图·上下文', ic:'📐' },
  { c:'ai', t:'AI编程', n:'CodeRabbit', d:'AI 代码审查助手，自动审查 PR 提供改进建议。', u:'https://www.coderabbit.ai', tag:'代码审查·PR', ic:'🐰' },
  { c:'ai', t:'AI编程', n:'Tabnine', d:'老牌 AI 代码补全引擎，支持本地模型保障代码隐私。', u:'https://www.tabnine.com', tag:'本地·隐私', ic:'🔐' },
  { c:'ai', t:'AI编程', n:'Zed', d:'Rust 编写的高性能代码编辑器，深度集成 AI 协作编程。', u:'https://zed.dev', tag:'Rust·高性能', ic:'⚡' },
  { c:'ai', t:'AI编程', n:'Tabby', d:'开源自托管的 AI 代码助手，数据完全可控可私有化部署。', u:'https://tabbyml.com', tag:'自托管·开源', ic:'🐈' },
  { c:'ai', t:'AI编程', n:'Cline', d:'VS Code 开源 AI 编程代理，用自然语言指挥 AI 写代码。', u:'https://cline.bot', tag:'代理·开源', ic:'🤖' },

  { c:'ai', t:'AI Agent', n:'AutoGPT', d:'开源自主 AI Agent 框架，让 AI 自动分解和执行复杂任务。', u:'https://github.com/Significant-Gravitas/AutoGPT', tag:'自主·开源', ic:'🤖' },
  { c:'ai', t:'AI Agent', n:'Dify', d:'开源的 LLM 应用开发平台，可视化编排 AI 工作流与 Agent。', u:'https://dify.ai', tag:'工作流·可视化', ic:'🧩' },
  { c:'ai', t:'AI Agent', n:'扣子 Coze', d:'字节跳动推出的 AI Bot 开发平台，零代码搭建智能助手。', u:'https://www.coze.cn', tag:'字节·零代码', ic:'🤖' },
  { c:'ai', t:'AI Agent', n:'Coze', d:'字节跳动国际版 AI Bot 平台，集成 Discord 和 Telegram。', u:'https://www.coze.com', tag:'国际版·Bot', ic:'🌐' },
  { c:'ai', t:'AI Agent', n:'Manus', d:'通用型 AI Agent，能独立完成复杂任务的自主智能体。', u:'https://manus.im', tag:'通用Agent·自主', ic:'✋' },
  { c:'ai', t:'AI Agent', n:'百宝箱', d:'百度智能云的 AI Agent 平台，快速构建智能体应用。', u:'https://agents.baidu.com', tag:'百度·Agent', ic:'🎁' },
  { c:'ai', t:'AI Agent', n:'LangGraph', d:'LangChain 出品的 Agent 编排框架，构建状态化多智能体。', u:'https://langchain.com/langgraph', tag:'编排·状态化', ic:'🕸️' },
  { c:'ai', t:'AI Agent', n:'CrewAI', d:'多 Agent 协作框架，定义角色让多个 AI 智能体协同工作。', u:'https://www.crewai.com', tag:'多Agent·协作', ic:'👥' },

  { c:'ai', t:'3D生成', n:'Meshy', d:'AI 3D 模型生成器，文字和图片一键转为高质量 3D 模型。', u:'https://www.meshy.ai', tag:'文生3D·PBR', ic:'🧊' },
  { c:'ai', t:'3D生成', n:'Tripo AI', d:'快速 3D AI 模型生成平台，文生 3D 和图生 3D 一体化。', u:'https://www.tripo3d.ai', tag:'文生3D·材质', ic:'🔺' },
  { c:'ai', t:'3D生成', n:'CSM AI', d:'Common Sense Machines，图片与视频转 3D 世界模型。', u:'https://csm.ai', tag:'图生3D·世界模型', ic:'🌍' },
  { c:'ai', t:'3D生成', n:'Rodin', d:'文本和图片生成高质量 3D 头像与数字资产的 AI 平台。', u:'https://hyper3d.ai', tag:'头像·资产', ic:'🗿' },
  { c:'ai', t:'3D生成', n:'Spline AI', d:'AI 辅助实时 3D 设计与协作平台，浏览器端零门槛创作。', u:'https://spline.design', tag:'实时·浏览器', ic:'🎮' },

  { c:'ai', t:'数字人', n:'小冰', d:'微软小冰独立后的 AI Being 平台，覆盖虚拟与数字人技术。', u:'https://www.xiaoice.com', tag:'AI Being·微软系', ic:'❄️' },
  { c:'ai', t:'数字人', n:'D-ID', d:'AI 生成式数字人视频，让照片开口说话技术开创者。', u:'https://www.d-id.com', tag:'照片说话·AI视频', ic:'🖼️' },
  { c:'ai', t:'数字人', n:'Hour One', d:'企业级 AI 虚拟主播视频生成，专业数字人制作平台。', u:'https://hourone.ai', tag:'企业·主播', ic:'🎬' },
  { c:'ai', t:'数字人', n:'DeepBrain AI', d:'AI Studios 虚拟人视频制作平台，支持多语种数字人。', u:'https://www.deepbrain.io', tag:'多语种·AI Studio', ic:'🧠' },
  { c:'ai', t:'数字人', n:'腾讯智影', d:'腾讯 AI 数字人视频创作平台，在线生成虚拟主播视频。', u:'https://zenvideo.qq.com', tag:'腾讯·创作', ic:'🎥' },

  { c:'ai', t:'AI for Science', n:'AlphaFold DB', d:'DeepMind 蛋白质结构预测数据库，加速生命科学研究。', u:'https://alphafold.ebi.ac.uk', tag:'蛋白质·DeepMind', ic:'🧬' },
  { c:'ai', t:'AI for Science', n:'RoseTTAFold', d:'华盛顿大学蛋白质结构预测工具，AI 驱动计算生物学。', u:'https://rosettafold.bakerlab.org', tag:'蛋白质·学术', ic:'🔬' },
  { c:'ai', t:'AI for Science', n:'NVIDIA BioNeMo', d:'NVIDIA AI 药物研发平台，加速分子模拟与新药发现。', u:'https://www.nvidia.com/en-us/clara/bionemo', tag:'药物·NVIDIA', ic:'💊' },
  { c:'ai', t:'AI for Science', n:'Isomorphic Labs', d:'DeepMind 分拆的 AI 药物发现公司，诺奖级团队创业。', u:'https://www.isomorphiclabs.com', tag:'药物发现·DeepMind系', ic:'🧪' },
  { c:'ai', t:'AI for Science', n:'Recursion', d:'AI 驱动的药物发现与研发平台，已上市临床阶段公司。', u:'https://www.recursion.com', tag:'药物·临床', ic:'🏥' },

  { c:'robot', t:'人形机器人', n:'Tesla Optimus', d:'特斯拉推出的通用人形机器人，旨在替代人类执行重复性劳动。', u:'https://www.tesla.com/optimus', tag:'特斯拉·通用', ic:'🤖' },
  { c:'robot', t:'人形机器人', n:'Figure AI', d:'OpenAI 投资的通用人形机器人公司，目标是商业化量产。', u:'https://www.figure.ai', tag:'OpenAI·商业化', ic:'🦿' },
  { c:'robot', t:'人形机器人', n:'Boston Dynamics', d:'全球最知名的高动态机器人公司，以 Atlas 和 Spot 著称。', u:'https://bostondynamics.com', tag:'动态·四足', ic:'🐕' },
  { c:'robot', t:'人形机器人', n:'Unitree 宇树', d:'中国领先的四足与人形机器人公司，产品覆盖消费到工业。', u:'https://www.unitree.com', tag:'四足·国产', ic:'🐾' },
  { c:'robot', t:'人形机器人', n:'1X Technologies', d:'OpenAI 投资的挪威人形机器人公司，专注于家庭服务场景。', u:'https://www.1x.tech', tag:'家庭·轻量', ic:'🏠' },
  { c:'robot', t:'人形机器人', n:'Agility Robotics', d:'Digit 人形机器人制造商，专注物流仓储场景的商业化应用。', u:'https://agilityrobotics.com', tag:'物流·仓储', ic:'📦' },
  { c:'robot', t:'人形机器人', n:'傅利叶智能', d:'中国通用人形机器人 GR-1 开发商，布局康复与通用场景。', u:'https://www.fftai.com', tag:'康复·国产', ic:'🏥' },
  { c:'robot', t:'人形机器人', n:'智元机器人', d:'华为前高管创办的具身智能公司，推动人形机器人产业化。', u:'https://www.agibot.com', tag:'具身智能·华为系', ic:'🧬' },
  { c:'robot', t:'人形机器人', n:'Apptronik', d:'NASA 合作的通用人形机器人 Apollo，聚焦物流与制造。', u:'https://apptronik.com', tag:'NASA·物流', ic:'🚀' },
  { c:'robot', t:'人形机器人', n:'优必选科技', d:'中国人形机器人第一股，Walker 系列人形机器人行业领先。', u:'https://www.ubtrobot.com', tag:'Walker·国产', ic:'🤖' },
  { c:'robot', t:'人形机器人', n:'达闼机器人', d:'云端智能机器人公司，Cloud Ginger 主打服务场景。', u:'https://www.cloudminds.com', tag:'云端智能·服务', ic:'☁️' },
  { c:'robot', t:'人形机器人', n:'逐际动力', d:'EngineAI，专注于通用人形机器人运动智能与控制。', u:'https://www.engineai.com.cn', tag:'运动智能·国产', ic:'🏃' },

  { c:'robot', t:'工业机器人', n:'ABB Robotics', d:'全球工业机器人巨头，提供全系列协作与工业机器人。', u:'https://new.abb.com/products/robotics', tag:'工业·协作', ic:'⚙️' },
  { c:'robot', t:'工业机器人', n:'FANUC', d:'日本发那科，全球装机量最大的工业机器人制造商。', u:'https://www.fanuc.com', tag:'日本·CNC', ic:'🏭' },
  { c:'robot', t:'工业机器人', n:'KUKA', d:'德国库卡机器人，汽车制造与工业自动化领域的标杆。', u:'https://www.kuka.com', tag:'德国·汽车', ic:'🚗' },
  { c:'robot', t:'工业机器人', n:'Yaskawa 安川', d:'日本安川电机，伺服电机与工业机器人全球领先。', u:'https://www.yaskawa.com', tag:'日本·伺服', ic:'🔌' },
  { c:'robot', t:'工业机器人', n:'埃斯顿自动化', d:'国产工业机器人龙头，覆盖焊接、搬运、喷涂全场景。', u:'https://www.estun.com', tag:'国产·全场景', ic:'🇨🇳' },
  { c:'robot', t:'工业机器人', n:'新松机器人', d:'中国机器人产业国家队，工业与服务机器人全覆盖。', u:'https://www.siasun.com', tag:'国家队·全面', ic:'🤖' },

  { c:'robot', t:'服务机器人', n:'普渡机器人', d:'全球餐饮配送机器人领导者，覆盖送餐、回盘、消毒。', u:'https://www.pudutech.com', tag:'餐饮·配送', ic:'🍽️' },
  { c:'robot', t:'服务机器人', n:'擎朗智能', d:'商用服务机器人公司，餐饮酒店配送机器人畅销海外。', u:'https://www.keenon.com', tag:'商用·配送', ic:'🤖' },
  { c:'robot', t:'服务机器人', n:'高仙机器人', d:'清洁机器人行业龙头，商用清洁与无人环卫全覆盖。', u:'https://www.gs-robot.com', tag:'清洁·环卫', ic:'🧹' },
  { c:'robot', t:'服务机器人', n:'追觅科技', d:'从扫地机器人到仿生四足机器人，消费机器人创新者。', u:'https://www.dreame.com', tag:'消费级·扫地', ic:'🏡' },
  { c:'robot', t:'服务机器人', n:'科沃斯', d:'中国扫地机器人领军品牌，家庭服务机器人生态完善。', u:'https://www.ecovacs.com', tag:'扫地·家庭', ic:'🧽' },
  { c:'robot', t:'服务机器人', n:'石头科技', d:'高端扫地机器人品牌，清洁算法与导航技术领先。', u:'https://www.roborock.com', tag:'高端·导航', ic:'🪨' },
  { c:'robot', t:'服务机器人', n:'大疆 RoboMaster', d:'DJI 教育机器人系列，编程与竞技一体的人工智能学习平台。', u:'https://www.dji.com/robomaster-s1', tag:'教育·竞技', ic:'🏆' },

  { c:'robot', t:'机器人平台', n:'ROS.org', d:'机器人操作系统（Robot Operating System）官方网站与社区。', u:'https://www.ros.org', tag:'开源·框架', ic:'⚙️' },
  { c:'robot', t:'机器人平台', n:'NVIDIA Isaac', d:'NVIDIA 机器人开发平台，提供仿真、训练与部署全套方案。', u:'https://developer.nvidia.com/isaac', tag:'NVIDIA·仿真', ic:'🟢' },
  { c:'robot', t:'机器人平台', n:'ROS 2', d:'下一代机器人操作系统，为工业级应用提供更强实时性。', u:'https://docs.ros.org/en/rolling', tag:'实时·工业', ic:'📡' },
  { c:'robot', t:'机器人平台', n:'Universal Robots', d:'协作机器人鼻祖，UR 系列全球装机量遥遥领先。', u:'https://www.universal-robots.com', tag:'协作·易部署', ic:'🤝' },
  { c:'robot', t:'机器人平台', n:'MuJoCo', d:'Google DeepMind 开源物理引擎，机器人仿真研究首选。', u:'https://mujoco.org', tag:'物理引擎·开源', ic:'🔬' },

  { c:'robot', t:'自动驾驶', n:'Waymo', d:'Alphabet 旗下自动驾驶公司，全球 L4 自动驾驶技术标杆。', u:'https://waymo.com', tag:'L4·Alphabet', ic:'🚗' },
  { c:'robot', t:'自动驾驶', n:'Cruise', d:'通用汽车旗下自动驾驶子公司，深耕城市 Robotaxi 运营。', u:'https://www.getcruise.com', tag:'GM·Robotaxi', ic:'🚕' },
  { c:'robot', t:'自动驾驶', n:'百度 Apollo', d:'百度自动驾驶开放平台，提供车路行云一体化方案。', u:'https://www.apollo.auto', tag:'百度·开放平台', ic:'🇨🇳' },
  { c:'robot', t:'自动驾驶', n:'文远知行 WeRide', d:'全球领先的 L4 级自动驾驶公司，覆盖出行与货运。', u:'https://www.weride.ai', tag:'L4·出行货运', ic:'🚌' },
  { c:'robot', t:'自动驾驶', n:'小马智行 Pony.ai', d:'中美两地同步运营的自动驾驶公司，技术实力强劲。', u:'https://www.pony.ai', tag:'中美·L4', ic:'🐴' },
  { c:'robot', t:'自动驾驶', n:'Mobileye', d:'英特尔旗下自动驾驶视觉芯片公司，ADAS 市场领导者。', u:'https://www.mobileye.com', tag:'视觉·ADAS', ic:'👁️' },

  { c:'robot', t:'无人机', n:'Skydio', d:'美国 AI 自主无人机领导者，全自主避障飞行无出其右。', u:'https://www.skydio.com', tag:'自主·AI避障', ic:'🛸' },
  { c:'robot', t:'无人机', n:'亿航智能 EHang', d:'全球首家上市的载人级自动驾驶飞行器公司。', u:'https://www.ehang.com', tag:'载人·eVTOL', ic:'🚁' },
  { c:'robot', t:'无人机', n:'Zipline', d:'医疗物资无人机配送全球领导者，服务非洲与美国。', u:'https://www.flyzipline.com', tag:'医疗·配送', ic:'💉' },
  { c:'robot', t:'无人机', n:'Wing', d:'Google 母公司 Alphabet 旗下无人机配送服务。', u:'https://wing.com', tag:'Alphabet·配送', ic:'📦' },
  { c:'robot', t:'无人机', n:'极飞科技 XAG', d:'中国智慧农业无人化技术领导者，农业无人机全球领先。', u:'https://www.xag.cn', tag:'农业·国产', ic:'🌾' },

  { c:'robot', t:'手术机器人', n:'Intuitive Surgical', d:'达芬奇手术机器人制造商，微创外科手术机器人的开创者。', u:'https://www.intuitive.com', tag:'达芬奇·微创', ic:'🏥' },
  { c:'robot', t:'手术机器人', n:'Medtronic Hugo', d:'美敦力 Hugo 手术机器人系统，拓展机器人辅助手术边界。', u:'https://www.medtronic.com', tag:'美敦力·RAS', ic:'⚕️' },
  { c:'robot', t:'手术机器人', n:'CMR Surgical', d:'英国手术机器人公司 Versius，模块化便携设计领先。', u:'https://cmrsurgical.com', tag:'英国·模块化', ic:'🇬🇧' },
  { c:'robot', t:'手术机器人', n:'天智航', d:'中国骨科手术机器人领导者，TiRobot 系列国内装机第一。', u:'https://www.tmed.com.cn', tag:'骨科·国产', ic:'🦴' },

  { c:'robot', t:'物流机器人', n:'极智嘉 Geek+', d:'全球仓储物流 AMR 机器人领军企业，服务 40+ 国家。', u:'https://www.geekplus.com', tag:'仓储·AMR', ic:'📦' },
  { c:'robot', t:'物流机器人', n:'Locus Robotics', d:'美国仓储 AMR 机器人公司，人机协同提升拣选效率。', u:'https://locusrobotics.com', tag:'拣选·协同', ic:'🤖' },
  { c:'robot', t:'物流机器人', n:'海柔创新', d:'HAI ROBOTICS，箱式仓储机器人首创者，ACR 系统全球领先。', u:'https://www.hairobotics.com', tag:'箱式·ACR', ic:'📬' },
  { c:'robot', t:'物流机器人', n:'Seegrid', d:'美国无人叉车与物流机器人公司，视觉导航技术深厚。', u:'https://seegrid.com', tag:'叉车·视觉导航', ic:'🛒' },

  { c:'robot', t:'外骨骼', n:'Ekso Bionics', d:'工业与医疗外骨骼先驱，EksoNR 获 FDA 批准用于康复。', u:'https://www.eksobionics.com', tag:'工业·医疗', ic:'🦾' },
  { c:'robot', t:'外骨骼', n:'ReWalk Robotics', d:'全球首个获 FDA 批准的个人外骨骼系统，助力截瘫行走。', u:'https://rewalk.com', tag:'FDA·截瘫', ic:'🚶' },
  { c:'robot', t:'外骨骼', n:'SuitX', d:'模块化工业外骨骼，Ottobock 旗下品牌降低工伤风险。', u:'https://www.suitx.com', tag:'模块·工业', ic:'🛡️' },

  { c:'models', t:'模型平台', n:'Hugging Face', d:'全球最大的 AI 模型社区与开源平台，托管数十万模型与数据集。', u:'https://huggingface.co', tag:'社区·开源', ic:'🤗' },
  { c:'models', t:'模型平台', n:'ModelScope 魔搭', d:'阿里云推出的中文 AI 模型开源社区，汇集国内优质模型。', u:'https://modelscope.cn', tag:'阿里·国产', ic:'🧩' },
  { c:'models', t:'模型平台', n:'Ollama', d:'本地运行大语言模型的最简单方式，支持 Llama、Mistral 等。', u:'https://ollama.ai', tag:'本地部署·简易', ic:'🦙' },
  { c:'models', t:'模型平台', n:'Replicate', d:'一键运行和部署开源 AI 模型的云平台，API 简单易用。', u:'https://replicate.com', tag:'云运行·API', ic:'☁️' },
  { c:'models', t:'模型平台', n:'Civitai', d:'Stable Diffusion 模型与 LoRA 的最大分享社区，创作者天堂。', u:'https://civitai.com', tag:'SD模型·社区', ic:'🏛️' },
  { c:'models', t:'模型平台', n:'OpenRouter', d:'统一的 LLM API 网关，一站调用 200+ 模型，按量付费。', u:'https://openrouter.ai', tag:'API网关·多模型', ic:'🔀' },
  { c:'models', t:'模型平台', n:'Together AI', d:'开源模型推理与微调平台，提供极速 GPU 推理 API。', u:'https://www.together.ai', tag:'推理·微调', ic:'⚡' },
  { c:'models', t:'模型平台', n:'Fireworks AI', d:'极低延迟的开源模型推理平台，专为生产环境优化。', u:'https://fireworks.ai', tag:'低延迟·生产', ic:'🎆' },
  { c:'models', t:'模型平台', n:'Groq', d:'LPU 推理引擎驱动的极速 LLM 推理服务，毫秒级响应。', u:'https://groq.com', tag:'LPU·极速', ic:'💨' },
  { c:'models', t:'模型平台', n:'OctoAI', d:'高效 AI 推理优化与模型部署平台，大幅降低部署成本。', u:'https://octo.ai', tag:'推理优化·降本', ic:'🐙' },

  { c:'models', t:'开源模型', n:'Llama', d:'Meta 发布的开源大语言模型系列，当前最受欢迎的开源基座。', u:'https://llama.meta.com', tag:'Meta·开源', ic:'🦙' },
  { c:'models', t:'开源模型', n:'Mistral', d:'法国 AI 公司推出的高性能开源模型，轻量高效部署友好。', u:'https://mistral.ai', tag:'欧洲·高效', ic:'🌪️' },
  { c:'models', t:'开源模型', n:'Qwen', d:'阿里通义千问开源模型系列，覆盖多种尺寸与多模态。', u:'https://github.com/QwenLM/Qwen', tag:'阿里·多尺寸', ic:'🏯' },
  { c:'models', t:'开源模型', n:'Gemma', d:'Google 推出的轻量开源模型系列，适合端侧部署与实验。', u:'https://ai.google.dev/gemma', tag:'Google·轻量', ic:'💎' },
  { c:'models', t:'开源模型', n:'Phi', d:'微软研究院推出的小语言模型，在手机和笔记本上流畅运行。', u:'https://azure.microsoft.com/products/phi', tag:'微软·小模型', ic:'📱' },
  { c:'models', t:'开源模型', n:'Yi 零一万物', d:'零一万物开源的大语言模型系列，中英文能力高度平衡。', u:'https://www.lingyiwanwu.com', tag:'零一·中英', ic:'☯' },
  { c:'models', t:'开源模型', n:'DeepSeek Models', d:'深度求索开源模型系列，MoE 架构效率与性能双领先。', u:'https://huggingface.co/deepseek-ai', tag:'MoE·高效', ic:'🔮' },

  { c:'models', t:'向量数据库', n:'Pinecone', d:'全托管向量数据库，为 LLM 应用提供高性能语义检索。', u:'https://www.pinecone.io', tag:'托管·语义检索', ic:'🌲' },
  { c:'models', t:'向量数据库', n:'Weaviate', d:'开源向量数据库，内置向量化模块，支持 GraphQL 查询。', u:'https://weaviate.io', tag:'开源·GraphQL', ic:'🔍' },
  { c:'models', t:'向量数据库', n:'Chroma', d:'开源 AI 原生向量数据库，AI 应用开发者的入门首选。', u:'https://www.trychroma.com', tag:'开源·入门', ic:'🎨' },
  { c:'models', t:'向量数据库', n:'Milvus', d:'全球最流行的开源向量数据库之一，云原生弹性架构。', u:'https://milvus.io', tag:'开源·云原生', ic:'🐘' },
  { c:'models', t:'向量数据库', n:'Qdrant', d:'高性能开源向量搜索引擎，Rust 编写延迟极低。', u:'https://qdrant.tech', tag:'Rust·高性能', ic:'🦀' },
  { c:'models', t:'向量数据库', n:'Elasticsearch', d:'老牌搜索引擎，向量检索与全文检索一体化，生态庞大。', u:'https://www.elastic.co', tag:'搜索·生态', ic:'🔎' },

  { c:'models', t:'AI开发框架', n:'LangChain', d:'最流行的 LLM 应用开发框架，链式编排 AI 工作流。', u:'https://www.langchain.com', tag:'编排·链式', ic:'⛓️' },
  { c:'models', t:'AI开发框架', n:'LlamaIndex', d:'数据索引与 RAG 框架，轻松构建知识增强型 AI 应用。', u:'https://www.llamaindex.ai', tag:'RAG·索引', ic:'📇' },
  { c:'models', t:'AI开发框架', n:'Langfuse', d:'开源 LLM 应用可观测平台，追踪、监控与调试 AI 调用。', u:'https://langfuse.com', tag:'可观测·调试', ic:'📊' },
  { c:'models', t:'AI开发框架', n:'Vercel AI SDK', d:'Vercel 推出的 AI 应用开发工具包，快速搭建 AI 前端。', u:'https://sdk.vercel.ai', tag:'前端·工具包', ic:'▲' },
  { c:'models', t:'AI开发框架', n:'Haystack', d:'deepset 开源的 NLP 框架，构建可扩展的检索与问答系统。', u:'https://haystack.deepset.ai', tag:'NLP·检索', ic:'🧱' },

  { c:'models', t:'MLOps', n:'Weights & Biases', d:'最流行的 ML 实验追踪与可视化平台，团队协作神器。', u:'https://wandb.ai', tag:'实验追踪·可视化', ic:'📈' },
  { c:'models', t:'MLOps', n:'MLflow', d:'Databricks 旗下开源 ML 全生命周期管理平台，行业标准。', u:'https://mlflow.org', tag:'开源·全生命周期', ic:'⚙️' },
  { c:'models', t:'MLOps', n:'Neptune.ai', d:'ML 实验追踪与模型注册中心，企业级元数据管理。', u:'https://neptune.ai', tag:'企业·元数据', ic:'🔱' },
  { c:'models', t:'MLOps', n:'ClearML', d:'开源 ML/DL 实验管理与编排平台，一站式 MLOps 方案。', u:'https://clear.ml', tag:'开源·编排', ic:'🧊' },
  { c:'models', t:'MLOps', n:'BentoML', d:'开源 AI 模型部署与服务框架，模型到 API 只需几分钟。', u:'https://www.bentoml.com', tag:'模型部署·API', ic:'🍱' },

  { c:'models', t:'数据标注', n:'Scale AI', d:'全球最大的 AI 数据标注与数据引擎平台，估值超百亿。', u:'https://scale.com', tag:'标注·数据引擎', ic:'⚖️' },
  { c:'models', t:'数据标注', n:'Labelbox', d:'企业级数据标注与 AI 数据引擎，端到端数据管理。', u:'https://labelbox.com', tag:'企业·端到端', ic:'🏷️' },
  { c:'models', t:'数据标注', n:'Label Studio', d:'开源多模态数据标注平台，支持文本、图像、音频、视频。', u:'https://labelstud.io', tag:'开源·多模态', ic:'🏗️' },
  { c:'models', t:'数据标注', n:'SuperAnnotate', d:'AI 辅助数据标注与模型管理，自动化标注加速迭代。', u:'https://www.superannotate.com', tag:'自动化·模型管理', ic:'🚀' },
  { c:'models', t:'数据标注', n:'Snorkel AI', d:'程序化数据标注与弱监督学习平台，以编程替代手工标注。', u:'https://snorkel.ai', tag:'程序化·弱监督', ic:'🤿' },

  { c:'blockchain', t:'公链平台', n:'Ethereum', d:'全球最大的智能合约平台，DeFi 与 NFT 生态的核心基础设施。', u:'https://ethereum.org', tag:'智能合约·DeFi', ic:'💎' },
  { c:'blockchain', t:'公链平台', n:'Solana', d:'高性能 Layer1 公链，以高 TPS 和低费用著称，生态繁荣。', u:'https://solana.com', tag:'高性能·低费', ic:'☀️' },
  { c:'blockchain', t:'公链平台', n:'Bitcoin', d:'全球第一个去中心化数字货币，区块链技术的开创者。', u:'https://bitcoin.org', tag:'P2P·数字黄金', ic:'₿' },
  { c:'blockchain', t:'公链平台', n:'Polygon', d:'以太坊 Layer2 扩容解决方案，提供更快更便宜的交易。', u:'https://polygon.technology', tag:'L2·扩容', ic:'🔷' },
  { c:'blockchain', t:'公链平台', n:'Arbitrum', d:'Optimistic Rollup 龙头，以太坊最受欢迎的 Layer2 网络。', u:'https://arbitrum.io', tag:'L2·Optimistic', ic:'🔵' },
  { c:'blockchain', t:'公链平台', n:'Optimism', d:'以太坊 Layer2 OP Stack 核心贡献者，推动超级链愿景。', u:'https://www.optimism.io', tag:'L2·Superchain', ic:'🔴' },
  { c:'blockchain', t:'公链平台', n:'Sui', d:'Meta 前团队打造的新一代高性能 Layer1，Move 语言原生。', u:'https://sui.io', tag:'Move·高性能', ic:'💧' },
  { c:'blockchain', t:'公链平台', n:'Aptos', d:'由 Meta Diem 项目衍生而来的 Layer1 公链，安全可扩展。', u:'https://aptoslabs.com', tag:'Move·安全', ic:'🌊' },
  { c:'blockchain', t:'公链平台', n:'Polkadot', d:'跨链互操作协议，连接多条专用区块链实现数据互通。', u:'https://polkadot.network', tag:'跨链·互操作', ic:'🔗' },
  { c:'blockchain', t:'公链平台', n:'Avalanche', d:'高性能可定制区块链平台，子网架构灵活可定制。', u:'https://www.avax.network', tag:'子网·定制', ic:'❄️' },
  { c:'blockchain', t:'公链平台', n:'Cardano', d:'学术研究驱动的 PoS 公链，采用 Haskell 实现高安全。', u:'https://cardano.org', tag:'学术·PoS', ic:'🔷' },
  { c:'blockchain', t:'公链平台', n:'BNB Chain', d:'Binance 官方公链，交易费低廉，GameFi 与 DeFi 生态繁荣。', u:'https://www.bnbchain.org', tag:'Binance·GameFi', ic:'🟡' },
  { c:'blockchain', t:'公链平台', n:'COSMOS', d:'跨链生态协议，IBC 协议实现多链资产与数据互操作。', u:'https://cosmos.network', tag:'IBC·跨链', ic:'🌌' },
  { c:'blockchain', t:'公链平台', n:'Near Protocol', d:'分片技术驱动的 L1 公链，开发体验友好，生态快速增长。', u:'https://near.org', tag:'分片·开发者友好', ic:'🌙' },
  { c:'blockchain', t:'公链平台', n:'Tron', d:'高吞吐量公链，USDT 流通量最大的区块链网络之一。', u:'https://tron.network', tag:'USDT·高吞吐', ic:'🔴' },

  { c:'blockchain', t:'Layer2 网络', n:'zkSync Era', d:'零知识 Rollup 领跑者，以太坊扩容的同时保障最高安全性。', u:'https://zksync.io', tag:'ZK·安全', ic:'⚡' },
  { c:'blockchain', t:'Layer2 网络', n:'StarkNet', d:'STARK 证明驱动的 ZK-Rollup，实现超大规模可扩展性。', u:'https://www.starknet.io', tag:'STARK·规模', ic:'🔲' },
  { c:'blockchain', t:'Layer2 网络', n:'Base', d:'Coinbase 孵化的以太坊 L2，背靠过亿用户入口快速成长。', u:'https://www.base.org', tag:'Coinbase·用户', ic:'🔵' },
  { c:'blockchain', t:'Layer2 网络', n:'Linea', d:'Consensys 推出的 zkEVM L2，深度集成 MetaMask 生态。', u:'https://linea.build', tag:'Consensys·zkEVM', ic:'📈' },
  { c:'blockchain', t:'Layer2 网络', n:'Scroll', d:'字节码兼容的 zkEVM Layer2，以太坊应用零成本迁移。', u:'https://scroll.io', tag:'zkEVM·兼容', ic:'📜' },
  { c:'blockchain', t:'Layer2 网络', n:'Mantle', d:'由 BitDAO 演化而来的模块化 L2，采用 EigenDA 数据可用性。', u:'https://www.mantle.xyz', tag:'模块化·EigenDA', ic:'🛡️' },

  { c:'blockchain', t:'基础设施', n:'Chainlink', d:'去中心化预言机网络，为智能合约安全提供链下真实数据。', u:'https://chain.link', tag:'预言机·数据', ic:'🔮' },
  { c:'blockchain', t:'基础设施', n:'Alchemy', d:'领先的区块链开发者平台，提供节点服务与增强 API。', u:'https://www.alchemy.com', tag:'节点·API', ic:'🧪' },
  { c:'blockchain', t:'基础设施', n:'Infura', d:'Consensys 旗下以太坊基础设施服务，节点即服务先驱。', u:'https://infura.io', tag:'以太坊·节点', ic:'🔥' },
  { c:'blockchain', t:'基础设施', n:'The Graph', d:'去中心化区块链数据索引协议，高效灵活查询链上数据。', u:'https://thegraph.com', tag:'索引·查询', ic:'📊' },
  { c:'blockchain', t:'基础设施', n:'Filecoin', d:'去中心化存储网络，IPFS 的激励层实现数据永续存储。', u:'https://filecoin.io', tag:'存储·去中心化', ic:'💾' },
  { c:'blockchain', t:'基础设施', n:'Arweave', d:'永久存储协议，一次付费永久保存数据构建永不忘却的网络。', u:'https://www.arweave.org', tag:'永久存储·Permaweb', ic:'🏛️' },
  { c:'blockchain', t:'基础设施', n:'Tenderly', d:'以太坊全栈开发工具套件，调试、模拟与监控智能合约。', u:'https://tenderly.co', tag:'调试·模拟', ic:'🛠️' },
  { c:'blockchain', t:'基础设施', n:'QuickNode', d:'高性能区块链 RPC 节点服务商，支持 30+ 主流公链。', u:'https://www.quicknode.com', tag:'RPC·多链', ic:'⚡' },

  { c:'blockchain', t:'NFT市场', n:'OpenSea', d:'全球最大的 NFT 交易市场，支持以太坊、Polygon 等多链。', u:'https://opensea.io', tag:'NFT·多链', ic:'🌊' },
  { c:'blockchain', t:'NFT市场', n:'Blur', d:'专业级 NFT 聚合交易平台，以速度和深度流动性著称。', u:'https://blur.io', tag:'NFT·聚合', ic:'💨' },
  { c:'blockchain', t:'NFT市场', n:'Magic Eden', d:'Solana 生态最大的 NFT 市场，跨链扩张至比特币 Ordinals。', u:'https://magiceden.io', tag:'Solana·Ordinals', ic:'🪄' },
  { c:'blockchain', t:'NFT市场', n:'Rarible', d:'社区治理的去中心化 NFT 市场，支持多链创建与交易。', u:'https://rarible.com', tag:'社区治理·多链', ic:'🔶' },
  { c:'blockchain', t:'NFT市场', n:'SuperRare', d:'高端加密艺术 NFT 平台，精选全球顶尖数字艺术家作品。', u:'https://superrare.com', tag:'高端艺术·精选', ic:'🖼️' },

  { c:'blockchain', t:'跨链桥', n:'Wormhole', d:'通用互操作协议，已连接 30+ 条主流区块链实现跨链通信。', u:'https://wormhole.com', tag:'通用·30+链', ic:'🕳️' },
  { c:'blockchain', t:'跨链桥', n:'LayerZero', d:'全链互操作协议，以超轻节点技术实现安全跨链。', u:'https://layerzero.network', tag:'全链·超轻节点', ic:'0️⃣' },
  { c:'blockchain', t:'跨链桥', n:'Stargate', d:'基于 LayerZero 的跨链桥，提供统一流动性与即时确认。', u:'https://stargate.finance', tag:'统一流动性·即时', ic:'🌌' },
  { c:'blockchain', t:'跨链桥', n:'Across', d:'以太坊跨链桥协议，低成本快速完成 Layer2 间资产转移。', u:'https://across.to', tag:'低成本·L2间', ic:'🌉' },
  { c:'blockchain', t:'跨链桥', n:'Synapse', d:'跨链互操作与资产桥接协议，支持 20+ EVM 链安全互通。', u:'https://www.synapseprotocol.com', tag:'EVM·安全桥', ic:'🧬' },

  { c:'blockchain', t:'区块链浏览器', n:'Etherscan', d:'以太坊最权威的区块链浏览器，查询交易与合约源码。', u:'https://etherscan.io', tag:'以太坊·交易', ic:'🔍' },
  { c:'blockchain', t:'区块链浏览器', n:'Solscan', d:'Solana 生态最流行的区块链浏览器，账户与代币追踪。', u:'https://solscan.io', tag:'Solana·账户', ic:'☀️' },
  { c:'blockchain', t:'区块链浏览器', n:'Polygonscan', d:'Polygon 官方区块链浏览器，查询 L2 交易与合约。', u:'https://polygonscan.com', tag:'Polygon·L2', ic:'🔷' },
  { c:'blockchain', t:'区块链浏览器', n:'BscScan', d:'BNB Chain 官方区块链浏览器，追踪 BSC 所有链上活动。', u:'https://bscscan.com', tag:'BNB·BSC', ic:'🟡' },
  { c:'blockchain', t:'区块链浏览器', n:'Tronscan', d:'Tron 区块链官方浏览器，查询 USDT 转账与智能合约。', u:'https://tronscan.org', tag:'Tron·USDT', ic:'🔴' },

  { c:'blockchain', t:'Web3 开发', n:'Hardhat', d:'以太坊智能合约开发框架，本地测试与部署的首选工具。', u:'https://hardhat.org', tag:'合约·测试', ic:'🪖' },
  { c:'blockchain', t:'Web3 开发', n:'Foundry', d:'Rust 编写的极速以太坊智能合约开发与测试工具套件。', u:'https://book.getfoundry.sh', tag:'Rust·极速', ic:'🦀' },
  { c:'blockchain', t:'Web3 开发', n:'Thirdweb', d:'Web3 全栈开发平台，零门槛构建 NFT、代币与市场应用。', u:'https://thirdweb.com', tag:'全栈·零门槛', ic:'🛠️' },
  { c:'blockchain', t:'Web3 开发', n:'Remix', d:'以太坊官方智能合约在线 IDE，快速编写与部署 Solidity。', u:'https://remix.ethereum.org', tag:'在线IDE·Solidity', ic:'🧩' },
  { c:'blockchain', t:'Web3 开发', n:'Moralis', d:'Web3 后端即服务平台，一站式构建去中心化应用后端。', u:'https://moralis.io', tag:'BaaS·API', ic:'⚡' },

  { c:'crypto', t:'行情数据', n:'CoinMarketCap', d:'全球最权威的加密货币市值排名与数据聚合平台。', u:'https://coinmarketcap.com', tag:'市值·排名', ic:'📊' },
  { c:'crypto', t:'行情数据', n:'CoinGecko', d:'全面的加密货币数据平台，提供代币基本面的深度分析。', u:'https://www.coingecko.com', tag:'数据·分析', ic:'🦎' },
  { c:'crypto', t:'行情数据', n:'TradingView', d:'专业级行情图表工具，支持加密货币与股票的技术分析。', u:'https://www.tradingview.com', tag:'图表·技术分析', ic:'📈' },
  { c:'crypto', t:'行情数据', n:'DefiLlama', d:'DeFi 全链 TVL 数据聚合平台，追踪各协议总锁仓价值。', u:'https://defillama.com', tag:'TVL·DeFi', ic:'🦙' },
  { c:'crypto', t:'行情数据', n:'Dune Analytics', d:'链上数据分析平台，用 SQL 查询并可视化区块链数据。', u:'https://dune.com', tag:'链上·SQL', ic:'🏜️' },
  { c:'crypto', t:'行情数据', n:'Nansen', d:'链上智能分析平台，追踪 Smart Money 与巨鲸实时动向。', u:'https://www.nansen.ai', tag:'SmartMoney·巨鲸', ic:'🐋' },
  { c:'crypto', t:'行情数据', n:'Glassnode', d:'专业级链上数据与研究平台，洞察市场周期与链上指标。', u:'https://glassnode.com', tag:'链上研究·周期', ic:'🔍' },
  { c:'crypto', t:'行情数据', n:'Messari', d:'加密资产研究平台，提供深度行业报告与治理追踪。', u:'https://messari.io', tag:'研究·报告', ic:'📖' },
  { c:'crypto', t:'行情数据', n:'Arkham', d:'链上身份追踪与情报平台，可视化实体持仓与资金流向。', u:'https://www.arkhamintelligence.com', tag:'链上情报·身份', ic:'🕵️' },
  { c:'crypto', t:'行情数据', n:'Token Terminal', d:'加密项目财务报表式数据分析，对标传统金融基本面指标。', u:'https://tokenterminal.com', tag:'财务·指标', ic:'💹' },

  { c:'crypto', t:'交易所', n:'Binance', d:'全球交易量最大的加密货币交易所，生态体系全面完善。', u:'https://www.binance.com', tag:'CEX·生态', ic:'🟡' },
  { c:'crypto', t:'交易所', n:'OKX', d:'全球领先的加密货币交易所与 Web3 自托管钱包平台。', u:'https://www.okx.com', tag:'CEX·Web3', ic:'⚪' },
  { c:'crypto', t:'交易所', n:'Coinbase', d:'美国最大的合规加密货币交易所，纳斯达克上市受 SEC 监管。', u:'https://www.coinbase.com', tag:'合规·美股', ic:'🔵' },
  { c:'crypto', t:'交易所', n:'Uniswap', d:'以太坊上最大的去中心化交易所（DEX），AMM 做市先驱。', u:'https://uniswap.org', tag:'DEX·AMM', ic:'🦄' },
  { c:'crypto', t:'交易所', n:'Jupiter', d:'Solana 生态最大的聚合 DEX，自动寻找最优兑换路由。', u:'https://jup.ag', tag:'Solana·聚合', ic:'🪐' },
  { c:'crypto', t:'交易所', n:'Bybit', d:'全球前三的加密货币衍生品交易所，交易深度与产品线丰富。', u:'https://www.bybit.com', tag:'衍生品·深度', ic:'🌐' },
  { c:'crypto', t:'交易所', n:'Kraken', d:'美国老牌合规交易所，以顶级安全和法币出入金便捷著称。', u:'https://www.kraken.com', tag:'合规·法币', ic:'🐙' },
  { c:'crypto', t:'交易所', n:'Gate.io', d:'老牌交易所，币种数量超 2000，首发新资产速度优势明显。', u:'https://www.gate.io', tag:'多币种·首发', ic:'🚪' },
  { c:'crypto', t:'交易所', n:'KuCoin', d:'全球知名综合性交易所，以发掘优质早期项目广受好评。', u:'https://www.kucoin.com', tag:'早期项目·综合', ic:'🪙' },
  { c:'crypto', t:'交易所', n:'Bitget', d:'合约交易量全球领先的交易所，跟单交易功能业内最成熟。', u:'https://www.bitget.com', tag:'合约·跟单', ic:'💪' },

  { c:'crypto', t:'钱包', n:'MetaMask', d:'最流行的以太坊钱包浏览器插件，玩转 DeFi 的必备入口。', u:'https://metamask.io', tag:'钱包·浏览器', ic:'🦊' },
  { c:'crypto', t:'钱包', n:'Phantom', d:'Solana 生态首选钱包，支持浏览器插件与移动端无缝体验。', u:'https://phantom.app', tag:'Solana·多设备', ic:'👻' },
  { c:'crypto', t:'钱包', n:'Ledger', d:'全球领先的硬件冷钱包品牌，私钥离线存储安全保障资产。', u:'https://www.ledger.com', tag:'硬件·冷存储', ic:'🔒' },
  { c:'crypto', t:'钱包', n:'Trust Wallet', d:'Binance 旗下多链移动钱包，支持百万种加密资产管理。', u:'https://trustwallet.com', tag:'多链·移动', ic:'🛡️' },
  { c:'crypto', t:'钱包', n:'Rabby', d:'DeBank 团队打造的以太坊钱包，交易前自动风险扫描与模拟。', u:'https://rabby.io', tag:'安全·模拟', ic:'🐰' },
  { c:'crypto', t:'钱包', n:'Rainbow', d:'设计优雅的以太坊移动钱包，iOS/Android 原生交互体验出色。', u:'https://rainbow.me', tag:'设计·优美', ic:'🌈' },
  { c:'crypto', t:'钱包', n:'Trezor', d:'欧洲领先的硬件冷钱包品牌，开源固件安全透明可审计。', u:'https://trezor.io', tag:'硬件·开源', ic:'🔐' },
  { c:'crypto', t:'钱包', n:'Safe', d:'多签智能合约钱包，团队金库与 DAO 资产管理的行业标准。', u:'https://safe.global', tag:'多签·金库', ic:'🏦' },

  { c:'crypto', t:'DeFi', n:'Aave', d:'领先的去中心化借贷协议，支持多链存借数字资产。', u:'https://aave.com', tag:'借贷·多链', ic:'👻' },
  { c:'crypto', t:'DeFi', n:'Lido', d:'最大的流动性质押协议，占据 ETH 质押量的主导份额。', u:'https://lido.fi', tag:'LSD·质押', ic:'💧' },
  { c:'crypto', t:'DeFi', n:'MakerDAO', d:'去中心化稳定币 DAI 发行协议，DeFi 领域基石级应用。', u:'https://makerdao.com', tag:'稳定币·DAI', ic:'⚙️' },
  { c:'crypto', t:'DeFi', n:'Curve', d:'稳定币交易 DEX，以超低滑点与深度流动性池闻名。', u:'https://curve.fi', tag:'稳定币·低滑点', ic:'📉' },
  { c:'crypto', t:'DeFi', n:'PancakeSwap', d:'BNB Chain 上最大的去中心化交易所，用户活跃度极高。', u:'https://pancakeswap.finance', tag:'BSC·DEX', ic:'🥞' },
  { c:'crypto', t:'DeFi', n:'EigenLayer', d:'以太坊再质押协议，释放已质押资产的额外收益潜力。', u:'https://www.eigenlayer.xyz', tag:'再质押·AVS', ic:'🔄' },
  { c:'crypto', t:'DeFi', n:'Pendle', d:'收益代币化协议，将未来收益分拆为可灵活交易的数字资产。', u:'https://www.pendle.finance', tag:'收益·代币化', ic:'⏳' },
  { c:'crypto', t:'DeFi', n:'1inch', d:'DEX 聚合器龙头，自动寻找最优兑换路径降低滑点成本。', u:'https://1inch.io', tag:'聚合·路由', ic:'🐉' },
  { c:'crypto', t:'DeFi', n:'SushiSwap', d:'多链 DEX 与 DeFi 工具集，提供跨链兑换与借贷一体化服务。', u:'https://www.sushi.com', tag:'跨链·DEX', ic:'🍣' },
  { c:'crypto', t:'DeFi', n:'Ether.fi', d:'去中心化流动性质押协议，非托管方式安全参与 ETH 质押。', u:'https://www.ether.fi', tag:'LSD·非托管', ic:'🌊' },

  { c:'crypto', t:'稳定币', n:'Tether', d:'发行 USDT 的公司，全球流通量最大的稳定币发行商。', u:'https://tether.to', tag:'USDT·FirstMover', ic:'💵' },
  { c:'crypto', t:'稳定币', n:'Circle', d:'USDC 发行商，美受监管的合规稳定币，储备透明可审计。', u:'https://www.circle.com', tag:'USDC·合规', ic:'⭕' },
  { c:'crypto', t:'稳定币', n:'Ethena', d:'合成美元协议 USDe，通过创新的 Delta 中性策略维持锚定。', u:'https://www.ethena.fi', tag:'合成美元·Delta', ic:'🛡️' },
  { c:'crypto', t:'稳定币', n:'Frax', d:'部分抵押算法稳定币协议，创新的 AMO 策略实现高效稳定。', u:'https://frax.finance', tag:'算法·AMO', ic:'🏛️' },

  { c:'crypto', t:'GameFi', n:'Axie Infinity', d:'区块链游戏开创者，边玩边赚（P2E）模式的领头羊。', u:'https://axieinfinity.com', tag:'P2E·开创者', ic:'🐉' },
  { c:'crypto', t:'GameFi', n:'The Sandbox', d:'去中心化虚拟世界与元宇宙平台，用户共建数字乐园。', u:'https://www.sandbox.game', tag:'元宇宙·虚拟世界', ic:'🏖️' },
  { c:'crypto', t:'GameFi', n:'Immutable', d:'NFT 与链游基础设施，Immutable X 与 zkEVM 专为游戏打造。', u:'https://www.immutable.com', tag:'基础设施·游戏链', ic:'🔗' },
  { c:'crypto', t:'GameFi', n:'Gala Games', d:'去中心化区块链游戏平台，玩家拥有游戏资产的真正所有权。', u:'https://www.gala.com', tag:'去中心·所有权', ic:'🎮' },
  { c:'crypto', t:'GameFi', n:'STEPN', d:'首创 Move-to-Earn 运动即赚钱模式，边跑步边赚取加密资产。', u:'https://www.stepn.com', tag:'M2E·运动', ic:'👟' },

  { c:'crypto', t:'DAO 工具', n:'Snapshot', d:'去中心化治理投票平台，Gasless 链下投票体验丝滑。', u:'https://snapshot.org', tag:'投票·Gasless', ic:'🗳️' },
  { c:'crypto', t:'DAO 工具', n:'Aragon', d:'DAO 创建与管理框架，一键启动去中心化自治组织。', u:'https://aragon.org', tag:'DAO·一键创建', ic:'🏛️' },
  { c:'crypto', t:'DAO 工具', n:'Tally', d:'DAO 治理与投票界面，追踪治理提案并参与链上决策。', u:'https://www.tally.xyz', tag:'治理·界面', ic:'📋' },
  { c:'crypto', t:'DAO 工具', n:'Juicebox', d:'社区金库与筹款协议，DAO 持续获得项目收入的工具。', u:'https://juicebox.money', tag:'金库·筹款', ic:'💰' },

  { c:'crypto', t:'加密支付', n:'BitPay', d:'老牌全球加密支付处理商，支持多币种支付与发票管理。', u:'https://bitpay.com', tag:'支付·老牌', ic:'💳' },
  { c:'crypto', t:'加密支付', n:'Ramp Network', d:'法币到加密货币的入金通道，合规覆盖 150+ 国家和地区。', u:'https://ramp.network', tag:'法币入金·合规', ic:'🏦' },
  { c:'crypto', t:'加密支付', n:'MoonPay', d:'全球领先的加密货币基础设施支付平台，服务超 500 万用户。', u:'https://www.moonpay.com', tag:'支付·基础设施', ic:'🌙' },

  { c:'silicon', t:'芯片算力', n:'NVIDIA', d:'GPU 领域全球领导者，AI 算力基础设施的核心供应商。', u:'https://www.nvidia.com', tag:'GPU·加速计算', ic:'🟢' },
  { c:'silicon', t:'芯片算力', n:'AMD', d:'高性能计算与 GPU 提供商，数据中心 AI 芯片的重要玩家。', u:'https://www.amd.com', tag:'GPU·CPU', ic:'🔴' },
  { c:'silicon', t:'芯片算力', n:'Intel', d:'全球最大半导体公司之一，发力 AI PC 与数据中心芯片赛道。', u:'https://www.intel.com', tag:'CPU·代工', ic:'🔵' },
  { c:'silicon', t:'芯片算力', n:'台积电 TSMC', d:'全球最大半导体代工企业，AI 芯片制造的核心枢纽。', u:'https://www.tsmc.com', tag:'代工·先进制程', ic:'🏭' },
  { c:'silicon', t:'芯片算力', n:'ARM', d:'全球领先的芯片 IP 供应商，移动计算与 IoT 生态的基石。', u:'https://www.arm.com', tag:'IP·低功耗', ic:'📱' },
  { c:'silicon', t:'芯片算力', n:'寒武纪', d:'中国 AI 芯片第一股，思元系列智能加速卡业界遥遥领先。', u:'https://www.cambricon.com', tag:'国产·AI加速', ic:'🧊' },
  { c:'silicon', t:'芯片算力', n:'海光信息', d:'国产 x86 兼容 CPU 龙头，数据中心与服务器芯片性能强劲。', u:'https://www.hygon.cn', tag:'x86·国产', ic:'💠' },
  { c:'silicon', t:'芯片算力', n:'摩尔线程', d:'国产全功能 GPU 厂商，发力 AI 训练与推理芯片市场。', u:'https://www.mthreads.com', tag:'国产GPU·训练', ic:'🧵' },
  { c:'silicon', t:'芯片算力', n:'地平线', d:'边缘 AI 芯片与自动驾驶计算方案的全球领导者。', u:'https://www.horizon.auto', tag:'边缘·自动驾驶', ic:'🚘' },
  { c:'silicon', t:'芯片算力', n:'Cerebras', d:'晶圆级 AI 芯片 WSE-3，单芯片集成 4 万亿晶体管。', u:'https://www.cerebras.net', tag:'晶圆级·超大', ic:'🧇' },
  { c:'silicon', t:'芯片算力', n:'Graphcore', d:'英国 AI 芯片独角兽，IPU 架构专为机器学习智能设计。', u:'https://www.graphcore.ai', tag:'IPU·英国', ic:'🇬🇧' },
  { c:'silicon', t:'芯片算力', n:'SambaNova', d:'企业级 AI 芯片与完整系统，创新的可重构数据流架构。', u:'https://sambanova.ai', tag:'数据流·企业', ic:'🔥' },

  { c:'silicon', t:'神经元芯片', n:'Neuralink', d:'马斯克创办的脑机接口公司，探索人脑与计算机的直接交互。', u:'https://neuralink.com', tag:'脑机接口·BCI', ic:'🧬' },
  { c:'silicon', t:'神经元芯片', n:'Synchron', d:'血管内植入式脑机接口，微创方式实现神经信号的精准读取。', u:'https://synchron.com', tag:'微创·血管内', ic:'🩸' },
  { c:'silicon', t:'神经元芯片', n:'Blackrock Neurotech', d:'植入式脑机接口先驱，Utah 阵列已稳定临床使用多年。', u:'https://blackrockneurotech.com', tag:'临床·Utah阵列', ic:'⚡' },

  { c:'silicon', t:'硅光芯片', n:'Lightmatter', d:'光子计算芯片先锋，用光代替电子实现超低功耗 AI 推理。', u:'https://lightmatter.co', tag:'光子·低功耗', ic:'💡' },
  { c:'silicon', t:'硅光芯片', n:'Ayar Labs', d:'光互连技术领导者，用光速连接芯片间的海量数据传输。', u:'https://ayarlabs.com', tag:'光互连·数据传输', ic:'🔗' },
  { c:'silicon', t:'硅光芯片', n:'曦智科技', d:'中国光子计算芯片先锋，光计算与光互连双轮驱动创新。', u:'https://www.lightelligence.io', tag:'国产·光计算', ic:'☀️' },

  { c:'silicon', t:'量子计算', n:'IBM Quantum', d:'IBM 量子计算平台，提供云端量子计算服务与开源 Qiskit SDK。', u:'https://www.ibm.com/quantum', tag:'量子·云服务', ic:'⚛️' },
  { c:'silicon', t:'量子计算', n:'Google Quantum AI', d:'Google 量子计算研究团队，目标构建有实用价值的量子计算机。', u:'https://quantumai.google', tag:'量子·纠错', ic:'🔬' },
  { c:'silicon', t:'量子计算', n:'IonQ', d:'离子阱量子计算技术领导者，全球首家纯量子计算上市公司。', u:'https://ionq.com', tag:'离子阱·上市', ic:'💫' },
  { c:'silicon', t:'量子计算', n:'Quantinuum', d:'Honeywell 量子计算部门与 CQC 合并，推出系统模型 H2。', u:'https://www.quantinuum.com', tag:'Honeywell·系统模型', ic:'🛰️' },
  { c:'silicon', t:'量子计算', n:'本源量子', d:'中国量子计算第一梯队企业，已发布超导量子计算机。', u:'https://www.originqc.com.cn', tag:'国产·超导', ic:'🇨🇳' },

  { c:'silicon', t:'算力云', n:'Lambda Labs', d:'专注 AI 训练的 GPU 云服务商，提供 A100/H100 实例。', u:'https://lambdalabs.com', tag:'GPU云·训练', ic:'☁️' },
  { c:'silicon', t:'算力云', n:'CoreWeave', d:'NVIDIA 投资的 GPU 加速云服务商，专注大规模 AI 推理与训练。', u:'https://www.coreweave.com', tag:'GPU云·NVIDIA生态', ic:'⚡' },
  { c:'silicon', t:'算力云', n:'AutoDL', d:'国内流行的 GPU 租用平台，性价比极高按量灵活计费。', u:'https://www.autodl.com', tag:'GPU租用·国产', ic:'🖥️' },
  { c:'silicon', t:'算力云', n:'RunPod', d:'按需 GPU 云平台，Serverless 推理服务即时弹性伸缩。', u:'https://www.runpod.io', tag:'无服务器·弹性', ic:'🏃' },
  { c:'silicon', t:'算力云', n:'Paperspace', d:'DigitalOcean 旗下的 GPU 云计算平台，深度集成 Jupyter Notebook。', u:'https://www.paperspace.com', tag:'Jupyter·GPU', ic:'📓' },
  { c:'silicon', t:'算力云', n:'Vast.ai', d:'去中心化 GPU 租赁市场，全球算力资源共享低价灵活租用。', u:'https://vast.ai', tag:'去中心化·共享', ic:'🌐' },
  { c:'silicon', t:'算力云', n:'JarvisLabs', d:'印度 GPU 云服务商，提供极具性价比的 A6000 和 RTX 系列 GPU。', u:'https://jarvislabs.ai', tag:'低价·RTX', ic:'🇮🇳' },

  { c:'tools', t:'开发者工具', n:'GitHub', d:'全球最大的代码托管与协作平台，开源社区的精神中心。', u:'https://github.com', tag:'代码·协作', ic:'🐙' },
  { c:'tools', t:'开发者工具', n:'Vercel', d:'前端部署平台领导者，支持 Next.js 等现代框架一键全球部署。', u:'https://vercel.com', tag:'部署·前端', ic:'▲' },
  { c:'tools', t:'开发者工具', n:'Netlify', d:'流行的静态网站部署平台，提供 Serverless 边缘函数支持。', u:'https://www.netlify.com', tag:'静态部署·无服务器', ic:'🟣' },
  { c:'tools', t:'开发者工具', n:'DeepL', d:'目前最精准的 AI 翻译工具，高质量支持 30+ 语言互译。', u:'https://www.deepl.com', tag:'翻译·精准', ic:'🌍' },
  { c:'tools', t:'开发者工具', n:'Notion', d:'全能型笔记与知识管理工具，集成 AI 写作辅助强大功能。', u:'https://www.notion.so', tag:'笔记·AI', ic:'📝' },
  { c:'tools', t:'开发者工具', n:'Figma', d:'领先的 UI/UX 在线协作设计工具，产品设计行业事实标准。', u:'https://www.figma.com', tag:'设计·协作', ic:'🎯' },
  { c:'tools', t:'开发者工具', n:'CodePen', d:'在线前端代码编辑器与分享社区，快速调试展示代码创意。', u:'https://codepen.io', tag:'前端·沙盒', ic:'✒️' },
  { c:'tools', t:'开发者工具', n:'Kaggle', d:'全球最大的数据科学与机器学习竞赛平台，Google 子品牌。', u:'https://www.kaggle.com', tag:'数据科学·竞赛', ic:'🏆' },
  { c:'tools', t:'开发者工具', n:'Colab', d:'Google Colaboratory，免费云端 Jupyter Notebook 含 GPU 算力。', u:'https://colab.research.google.com', tag:'Notebook·免费GPU', ic:'📓' },
  { c:'tools', t:'开发者工具', n:'Docker', d:'容器化平台领导者，标准化应用打包与跨平台一键部署。', u:'https://www.docker.com', tag:'容器·部署', ic:'🐳' },
  { c:'tools', t:'开发者工具', n:'Cloudflare', d:'全球 CDN 与网络安全领导者，Workers 平台支持边缘计算。', u:'https://www.cloudflare.com', tag:'CDN·安全', ic:'☁️' },
  { c:'tools', t:'开发者工具', n:'VS Code', d:'微软免费开源代码编辑器，全球开发者装机量稳居第一。', u:'https://code.visualstudio.com', tag:'编辑器·免费', ic:'💻' },
  { c:'tools', t:'开发者工具', n:'Linear', d:'极简高效的项目管理工具，科技团队 Issue 与 Sprint 跟踪首选。', u:'https://linear.app', tag:'项目管理·极简', ic:'📐' },
  { c:'tools', t:'开发者工具', n:'Postman', d:'API 全生命周期开发与测试工具，构建调试接口的首选工作平台。', u:'https://www.postman.com', tag:'API·测试', ic:'📮' },
  { c:'tools', t:'开发者工具', n:'Obsidian', d:'本地 Markdown 知识库工具，创新双向链接构建你的第二大脑。', u:'https://obsidian.md', tag:'笔记·知识图谱', ic:'💎' },
  { c:'tools', t:'开发者工具', n:'Excalidraw', d:'手绘风格在线协作白板工具，简洁高效的可视化创意表达。', u:'https://excalidraw.com', tag:'白板·手绘', ic:'✏️' },
  { c:'tools', t:'开发者工具', n:'Warp', d:'基于 Rust 的新一代现代化终端，内置 AI 命令辅助与协作。', u:'https://www.warp.dev', tag:'终端·AI', ic:'⚡' },

  { c:'tools', t:'后端服务', n:'Supabase', d:'开源 Firebase 替代品，基于 Postgres 数据库快速构建应用。', u:'https://supabase.com', tag:'BaaS·Postgres', ic:'⚡' },
  { c:'tools', t:'后端服务', n:'Firebase', d:'Google 后端即服务平台，实时数据库助力开发者极快速开发。', u:'https://firebase.google.com', tag:'BaaS·Google', ic:'🔥' },
  { c:'tools', t:'后端服务', n:'Railway', d:'简洁优雅的全栈部署平台，一键部署代码与托管数据库服务。', u:'https://railway.app', tag:'部署·全栈', ic:'🚂' },
  { c:'tools', t:'后端服务', n:'Render', d:'零 DevOps 云平台，Web 服务与数据库自动部署与自动 SSL。', u:'https://render.com', tag:'自动部署·SSL', ic:'🔧' },
  { c:'tools', t:'后端服务', n:'Fly.io', d:'边缘分布式应用部署平台，全球多区域部署就近极速服务用户。', u:'https://fly.io', tag:'边缘·全球', ic:'🪰' },
  { c:'tools', t:'后端服务', n:'Clerk', d:'现代化用户认证管理平台，深度集成 Next.js 极速接入。', u:'https://clerk.com', tag:'认证·用户管理', ic:'🔑' },
  { c:'tools', t:'后端服务', n:'Resend', d:'开发者友好的邮件发送 API，现代化 React 邮件模板支持。', u:'https://resend.com', tag:'邮件·API', ic:'📧' },
  { c:'tools', t:'后端服务', n:'Neon', d:'Serverless Postgres 数据库方案，秒级分支创建与按需计费。', u:'https://neon.tech', tag:'Serverless·Postgres', ic:'💡' },

  { c:'tools', t:'设计资源', n:'Dribbble', d:'全球最大的设计师互动社区，超丰富 UI/UX 灵感作品大全。', u:'https://dribbble.com', tag:'设计·灵感', ic:'🏀' },
  { c:'tools', t:'设计资源', n:'Behance', d:'Adobe 旗下全球创意作品展示平台，汇聚顶尖设计案例。', u:'https://www.behance.net', tag:'Adobe·创意', ic:'🎨' },
  { c:'tools', t:'设计资源', n:'Unsplash', d:'高质量免费商用摄影图片库，AI 搜索精准匹配创作需求。', u:'https://unsplash.com', tag:'图片·免费', ic:'📷' },
  { c:'tools', t:'设计资源', n:'Pexels', d:'免费高清素材图片与视频素材库，中文搜索体验良好。', u:'https://www.pexels.com', tag:'素材·视频', ic:'🎥' },
  { c:'tools', t:'设计资源', n:'SVG Repo', d:'免费 SVG 矢量图标大全，超过 50 万个可商用矢量图标。', u:'https://www.svgrepo.com', tag:'SVG·图标', ic:'🖼️' },
  { c:'tools', t:'设计资源', n:'Google Fonts', d:'Google 免费开源 Web 字体库，高质量字体加速网页加载。', u:'https://fonts.google.com', tag:'字体·开源', ic:'🔤' },

  { c:'tools', t:'监控可观测', n:'Grafana', d:'全球最流行的开源可观测性与数据可视化平台，仪表盘首选。', u:'https://grafana.com', tag:'可视化·仪表盘', ic:'📊' },
  { c:'tools', t:'监控可观测', n:'Datadog', d:'云端全栈应用监控与安全平台，实时洞察基础设施健康状况。', u:'https://www.datadoghq.com', tag:'云监控·全栈', ic:'🐕' },
  { c:'tools', t:'监控可观测', n:'Sentry', d:'应用错误追踪与性能监控平台，实时发现和定位线上 Bug。', u:'https://sentry.io', tag:'错误追踪·性能', ic:'🔍' },
  { c:'tools', t:'监控可观测', n:'New Relic', d:'全栈可观测性平台，代码级性能分析与全链路追踪利器。', u:'https://newrelic.com', tag:'全栈·APM', ic:'📈' },
  { c:'tools', t:'监控可观测', n:'PagerDuty', d:'事件管理与智能告警平台，自动化 Incident 响应与管理。', u:'https://www.pagerduty.com', tag:'告警·Incident', ic:'🚨' },

  { c:'tools', t:'资讯社区', n:'Reddit', d:'全球最大的论坛社区，拥有丰富的 AI/Crypto 深度讨论板块。', u:'https://www.reddit.com', tag:'论坛·讨论', ic:'🤖' },
  { c:'tools', t:'资讯社区', n:'Product Hunt', d:'发现全球最新科技产品与工具的社区，每日精选创新应用。', u:'https://www.producthunt.com', tag:'新产品·发现', ic:'🏹' },
  { c:'tools', t:'资讯社区', n:'Hacker News', d:'Y Combinator 运营的前沿科技新闻社区，开发者每日必读。', u:'https://news.ycombinator.com', tag:'科技·开发者', ic:'📰' },
  { c:'tools', t:'资讯社区', n:'Twitter/X', d:'全球 AI 与 Crypto 领域实时信息流，行业大佬深度活跃。', u:'https://x.com', tag:'社交·实时', ic:'🐦' },
  { c:'tools', t:'资讯社区', n:'V2EX', d:'中文技术创意社区，国内开发者高质量交流分享活跃平台。', u:'https://www.v2ex.com', tag:'中文·技术', ic:'💡' },
  { c:'tools', t:'资讯社区', n:'掘金', d:'中文前端与全栈技术社区，开发者持续成长与深度分享平台。', u:'https://juejin.cn', tag:'前端·全栈', ic:'⛏️' },

  { c:'learn', t:'论文研究', n:'arXiv', d:'康奈尔大学运营的预印本论文库，AI/ML 最新研究首选。', u:'https://arxiv.org', tag:'论文·预印本', ic:'📄' },
  { c:'learn', t:'论文研究', n:'Papers with Code', d:'将论文与代码实现关联的平台，追踪各任务 SOTA 模型。', u:'https://paperswithcode.com', tag:'论文+代码·SOTA', ic:'📋' },
  { c:'learn', t:'论文研究', n:'Google Scholar', d:'谷歌学术搜索引擎，全球最大最全面的学术文献检索平台。', u:'https://scholar.google.com', tag:'学术·检索', ic:'🎓' },
  { c:'learn', t:'论文研究', n:'Semantic Scholar', d:'AI 驱动的学术搜索引擎，智能论文摘要与引文影响力分析。', u:'https://www.semanticscholar.org', tag:'AI·引文', ic:'🔬' },
  { c:'learn', t:'论文研究', n:'Connected Papers', d:'可视化论文引文关系图谱，快速探索相关研究方向与脉络。', u:'https://www.connectedpapers.com', tag:'引文图·探索', ic:'🕸️' },
  { c:'learn', t:'论文研究', n:'ResearchGate', d:'全球科学家社交网络，分享论文与协作研究的专业平台。', u:'https://www.researchgate.net', tag:'学术社交·协作', ic:'🌐' },

  { c:'learn', t:'在线课程', n:'Coursera', d:'全球领先的在线学习平台，AI/ML 课程由世界顶尖大学教授授课。', u:'https://www.coursera.org', tag:'课程·大学', ic:'🎓' },
  { c:'learn', t:'在线课程', n:'Fast.ai', d:'免费的深度学习实战课程，让每个人都能民主化使用 AI。', u:'https://www.fast.ai', tag:'免费·实战', ic:'⚡' },
  { c:'learn', t:'在线课程', n:'DeepLearning.AI', d:'吴恩达创立的 AI 教育平台，提供系统化深度学习课程。', u:'https://www.deeplearning.ai', tag:'吴恩达·体系化', ic:'📚' },
  { c:'learn', t:'在线课程', n:'GitHub Education', d:'GitHub 教育平台，为学生提供开发者包和开源课程资源。', u:'https://education.github.com', tag:'学生·开源', ic:'🎒' },
  { c:'learn', t:'在线课程', n:'Udemy', d:'全球最大的在线课程市集，海量 AI 与编程实战课程。', u:'https://www.udemy.com', tag:'市集·实战', ic:'🛒' },
  { c:'learn', t:'在线课程', n:'edX', d:'哈佛与 MIT 联合创办的慕课平台，名校课程免费在线学习。', u:'https://www.edx.org', tag:'名校·慕课', ic:'🏫' },
  { c:'learn', t:'在线课程', n:'Khan Academy', d:'非营利教育平台，从基础数学到 AI 通识教育全覆盖。', u:'https://www.khanacademy.org', tag:'非营利·通识', ic:'🌱' },
  { c:'learn', t:'在线课程', n:'DataCamp', d:'数据科学与 AI 互动学习平台，边学边练上手即编码。', u:'https://www.datacamp.com', tag:'数据科学·互动', ic:'📊' },
  { c:'learn', t:'在线课程', n:'freeCodeCamp', d:'免费学编程的全栈开源课程，获得业界认证并构建实战项目。', u:'https://www.freecodecamp.org', tag:'免费·认证', ic:'🔥' },
  { c:'learn', t:'在线课程', n:'Codecademy', d:'交互式编程学习平台，从零基础入门到全栈开发进阶。', u:'https://www.codecademy.com', tag:'交互·零基础', ic:'💻' },

  { c:'learn', t:'练习平台', n:'LeetCode', d:'全球最大的编程面试刷题平台，AI 周赛系统性锻炼算法。', u:'https://leetcode.com', tag:'面试·算法', ic:'🏆' },
  { c:'learn', t:'练习平台', n:'HackerRank', d:'编程挑战与面试准备平台，众多企业笔试的常用官方系统。', u:'https://www.hackerrank.com', tag:'挑战·笔试', ic:'💪' },
  { c:'learn', t:'练习平台', n:'Codewars', d:'游戏化编程挑战社区，用实战 Kata 系统提升编程各方面能力。', u:'https://www.codewars.com', tag:'游戏化·挑战', ic:'⚔️' },

  { c:'learn', t:'开放资源', n:'MIT OpenCourseWare', d:'麻省理工学院开放课程，免费学习全球顶级 CS/AI 课程。', u:'https://ocw.mit.edu', tag:'MIT·免费', ic:'🏛️' },
  { c:'learn', t:'开放资源', n:'Stanford Online', d:'斯坦福大学在线课程平台，AI 与 ML 课程全球知名度最高。', u:'https://online.stanford.edu', tag:'斯坦福·在线', ic:'🌲' },
  { c:'learn', t:'开放资源', n:'Hugging Face Course', d:'Hugging Face 官方 NLP 与 Transformers 课程，免费开放学习。', u:'https://huggingface.co/learn', tag:'NLP·Transformers', ic:'🤗' },

  { c:'learn', t:'提示工程', n:'Prompt Engineering Guide', d:'提示工程综合指南，DAIR.AI 维护的最全提示词方法论资源。', u:'https://www.promptingguide.ai', tag:'指南·综合', ic:'📖' },
  { c:'learn', t:'提示工程', n:'Learn Prompting', d:'免费提示工程学习课程，从入门到进阶全面提升提示词技巧。', u:'https://learnprompting.org', tag:'免费·课程', ic:'🎓' },
  { c:'learn', t:'提示工程', n:'PromptPerfect', d:'Jina AI 推出的 AI 提示词专业优化工具，自动优化到最佳效果。', u:'https://promptperfect.jina.ai', tag:'优化·Jina', ic:'✨' },
  { c:'learn', t:'提示工程', n:'PromptBase', d:'AI 提示词交易市场，购买和出售高质量 Midjourney/GPT 提示词。', u:'https://promptbase.com', tag:'市场·交易', ic:'🛒' },
  { c:'learn', t:'提示工程', n:'Anthropic Prompt Library', d:'Anthropic 官方提示词库，精选高质量 Claude 提示词模板与最佳实践。', u:'https://docs.anthropic.com/en/prompt-library', tag:'官方·模板', ic:'📚' },

  { c:'learn', t:'AI资讯', n:'机器之心', d:'中文 AI 媒体第一品牌，深度报道全球人工智能前沿发展动态。', u:'https://www.jiqizhixin.com', tag:'媒体·前沿', ic:'🤖' },
  { c:'learn', t:'AI资讯', n:'量子位', d:'关注 AI 与前沿科技的中文媒体，追踪报道新技术与新公司。', u:'https://www.qbitai.com', tag:'科技·动态', ic:'⚛️' },
  { c:'learn', t:'AI资讯', n:'新智元', d:'中文人工智能垂直媒体，AI 领域权威信息聚合与深度解读平台。', u:'https://www.aiera.com.cn', tag:'权威·AI', ic:'🧠' },
  { c:'learn', t:'AI资讯', n:'The Batch', d:'吴恩达 DeepLearning.AI 出品的 AI 周刊，每周精选行业要闻。', u:'https://www.deeplearning.ai/the-batch', tag:'周刊·精选', ic:'📧' },
  { c:'learn', t:'AI资讯', n:'TLDR AI', d:'每日 AI 快讯 Newsletter，5 分钟快速掌握全球 AI 行业动态。', u:'https://tldr.tech/ai', tag:'日报·快讯', ic:'⚡' }
];

var catMeta = {
  ai:        { emoji:'🤖', name:'人工智能应用', desc:'大语言模型、AI 搜索、AI 写作办公、AI 设计、AI 绘画、AI 视频、AI 音频、AI 编程、AI Agent、3D 生成、数字人、AI for Science' },
  robot:     { emoji:'🦾', name:'机器人',       desc:'人形机器人、工业机器人、服务机器人、机器人平台、自动驾驶、无人机、手术机器人、物流机器人、外骨骼' },
  models:    { emoji:'🧠', name:'模型与开源',   desc:'模型平台、开源模型、向量数据库、AI 开发框架、MLOps、数据标注' },
  blockchain:{ emoji:'⛓️', name:'区块链',       desc:'公链平台、Layer2 网络、基础设施、NFT 市场、跨链桥、区块链浏览器、Web3 开发' },
  crypto:    { emoji:'💰', name:'数字币',       desc:'行情数据、交易所、钱包、DeFi 协议、稳定币、GameFi、DAO 工具、加密支付' },
  silicon:   { emoji:'💎', name:'芯片与算力',   desc:'芯片算力、神经元芯片、硅光芯片、量子计算、算力云' },
  tools:     { emoji:'🔧', name:'开发工具',     desc:'开发者工具、后端服务、设计资源、监控可观测、资讯社区' },
  learn:     { emoji:'📚', name:'学习资源',     desc:'论文研究、在线课程、练习平台、开放资源、提示工程、AI 资讯' }
};

var catOrder = ['ai','robot','models','blockchain','crypto','silicon','tools','learn'];